<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use TwilioApIsLib\Models\ApiV2010AccountMessage;

/**
 * Builder for model ApiV2010AccountMessage
 *
 * @see ApiV2010AccountMessage
 */
class ApiV2010AccountMessageBuilder
{
    /**
     * @var ApiV2010AccountMessage
     */
    private $instance;

    private function __construct(ApiV2010AccountMessage $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Api V2010 Account Message Builder object.
     */
    public static function init(): self
    {
        return new self(new ApiV2010AccountMessage());
    }

    /**
     * Sets body field.
     *
     * @param string|null $value
     */
    public function body(?string $value): self
    {
        $this->instance->setBody($value);
        return $this;
    }

    /**
     * Unsets body field.
     */
    public function unsetBody(): self
    {
        $this->instance->unsetBody();
        return $this;
    }

    /**
     * Sets num segments field.
     *
     * @param string|null $value
     */
    public function numSegments(?string $value): self
    {
        $this->instance->setNumSegments($value);
        return $this;
    }

    /**
     * Unsets num segments field.
     */
    public function unsetNumSegments(): self
    {
        $this->instance->unsetNumSegments();
        return $this;
    }

    /**
     * Sets direction field.
     *
     * @param string|null $value
     */
    public function direction(?string $value): self
    {
        $this->instance->setDirection($value);
        return $this;
    }

    /**
     * Sets from field.
     *
     * @param string|null $value
     */
    public function from(?string $value): self
    {
        $this->instance->setFrom($value);
        return $this;
    }

    /**
     * Unsets from field.
     */
    public function unsetFrom(): self
    {
        $this->instance->unsetFrom();
        return $this;
    }

    /**
     * Sets to field.
     *
     * @param string|null $value
     */
    public function to(?string $value): self
    {
        $this->instance->setTo($value);
        return $this;
    }

    /**
     * Unsets to field.
     */
    public function unsetTo(): self
    {
        $this->instance->unsetTo();
        return $this;
    }

    /**
     * Sets date updated field.
     *
     * @param string|null $value
     */
    public function dateUpdated(?string $value): self
    {
        $this->instance->setDateUpdated($value);
        return $this;
    }

    /**
     * Unsets date updated field.
     */
    public function unsetDateUpdated(): self
    {
        $this->instance->unsetDateUpdated();
        return $this;
    }

    /**
     * Sets price field.
     *
     * @param string|null $value
     */
    public function price(?string $value): self
    {
        $this->instance->setPrice($value);
        return $this;
    }

    /**
     * Unsets price field.
     */
    public function unsetPrice(): self
    {
        $this->instance->unsetPrice();
        return $this;
    }

    /**
     * Sets error message field.
     *
     * @param string|null $value
     */
    public function errorMessage(?string $value): self
    {
        $this->instance->setErrorMessage($value);
        return $this;
    }

    /**
     * Unsets error message field.
     */
    public function unsetErrorMessage(): self
    {
        $this->instance->unsetErrorMessage();
        return $this;
    }

    /**
     * Sets uri field.
     *
     * @param string|null $value
     */
    public function uri(?string $value): self
    {
        $this->instance->setUri($value);
        return $this;
    }

    /**
     * Unsets uri field.
     */
    public function unsetUri(): self
    {
        $this->instance->unsetUri();
        return $this;
    }

    /**
     * Sets account sid field.
     *
     * @param string|null $value
     */
    public function accountSid(?string $value): self
    {
        $this->instance->setAccountSid($value);
        return $this;
    }

    /**
     * Unsets account sid field.
     */
    public function unsetAccountSid(): self
    {
        $this->instance->unsetAccountSid();
        return $this;
    }

    /**
     * Sets num media field.
     *
     * @param string|null $value
     */
    public function numMedia(?string $value): self
    {
        $this->instance->setNumMedia($value);
        return $this;
    }

    /**
     * Unsets num media field.
     */
    public function unsetNumMedia(): self
    {
        $this->instance->unsetNumMedia();
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets messaging service sid field.
     *
     * @param string|null $value
     */
    public function messagingServiceSid(?string $value): self
    {
        $this->instance->setMessagingServiceSid($value);
        return $this;
    }

    /**
     * Unsets messaging service sid field.
     */
    public function unsetMessagingServiceSid(): self
    {
        $this->instance->unsetMessagingServiceSid();
        return $this;
    }

    /**
     * Sets sid field.
     *
     * @param string|null $value
     */
    public function sid(?string $value): self
    {
        $this->instance->setSid($value);
        return $this;
    }

    /**
     * Unsets sid field.
     */
    public function unsetSid(): self
    {
        $this->instance->unsetSid();
        return $this;
    }

    /**
     * Sets date sent field.
     *
     * @param string|null $value
     */
    public function dateSent(?string $value): self
    {
        $this->instance->setDateSent($value);
        return $this;
    }

    /**
     * Unsets date sent field.
     */
    public function unsetDateSent(): self
    {
        $this->instance->unsetDateSent();
        return $this;
    }

    /**
     * Sets date created field.
     *
     * @param string|null $value
     */
    public function dateCreated(?string $value): self
    {
        $this->instance->setDateCreated($value);
        return $this;
    }

    /**
     * Unsets date created field.
     */
    public function unsetDateCreated(): self
    {
        $this->instance->unsetDateCreated();
        return $this;
    }

    /**
     * Sets error code field.
     *
     * @param int|null $value
     */
    public function errorCode(?int $value): self
    {
        $this->instance->setErrorCode($value);
        return $this;
    }

    /**
     * Unsets error code field.
     */
    public function unsetErrorCode(): self
    {
        $this->instance->unsetErrorCode();
        return $this;
    }

    /**
     * Sets price unit field.
     *
     * @param string|null $value
     */
    public function priceUnit(?string $value): self
    {
        $this->instance->setPriceUnit($value);
        return $this;
    }

    /**
     * Unsets price unit field.
     */
    public function unsetPriceUnit(): self
    {
        $this->instance->unsetPriceUnit();
        return $this;
    }

    /**
     * Sets api version field.
     *
     * @param string|null $value
     */
    public function apiVersion(?string $value): self
    {
        $this->instance->setApiVersion($value);
        return $this;
    }

    /**
     * Unsets api version field.
     */
    public function unsetApiVersion(): self
    {
        $this->instance->unsetApiVersion();
        return $this;
    }

    /**
     * Sets subresource uris field.
     *
     * @param array|null $value
     */
    public function subresourceUris(?array $value): self
    {
        $this->instance->setSubresourceUris($value);
        return $this;
    }

    /**
     * Unsets subresource uris field.
     */
    public function unsetSubresourceUris(): self
    {
        $this->instance->unsetSubresourceUris();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Api V2010 Account Message object.
     */
    public function build(): ApiV2010AccountMessage
    {
        return CoreHelper::clone($this->instance);
    }
}
