<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use TwilioApIsLib\Models\Binding;

/**
 * Builder for model Binding
 *
 * @see Binding
 */
class BindingBuilder
{
    /**
     * @var Binding
     */
    private $instance;

    private function __construct(Binding $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Binding Builder object.
     */
    public static function init(): self
    {
        return new self(new Binding());
    }

    /**
     * Sets sid field.
     *
     * @param string|null $value
     */
    public function sid(?string $value): self
    {
        $this->instance->setSid($value);
        return $this;
    }

    /**
     * Unsets sid field.
     */
    public function unsetSid(): self
    {
        $this->instance->unsetSid();
        return $this;
    }

    /**
     * Sets account sid field.
     *
     * @param string|null $value
     */
    public function accountSid(?string $value): self
    {
        $this->instance->setAccountSid($value);
        return $this;
    }

    /**
     * Unsets account sid field.
     */
    public function unsetAccountSid(): self
    {
        $this->instance->unsetAccountSid();
        return $this;
    }

    /**
     * Sets service sid field.
     *
     * @param string|null $value
     */
    public function serviceSid(?string $value): self
    {
        $this->instance->setServiceSid($value);
        return $this;
    }

    /**
     * Unsets service sid field.
     */
    public function unsetServiceSid(): self
    {
        $this->instance->unsetServiceSid();
        return $this;
    }

    /**
     * Sets credential sid field.
     *
     * @param string|null $value
     */
    public function credentialSid(?string $value): self
    {
        $this->instance->setCredentialSid($value);
        return $this;
    }

    /**
     * Unsets credential sid field.
     */
    public function unsetCredentialSid(): self
    {
        $this->instance->unsetCredentialSid();
        return $this;
    }

    /**
     * Sets date created field.
     *
     * @param \DateTime|null $value
     */
    public function dateCreated(?\DateTime $value): self
    {
        $this->instance->setDateCreated($value);
        return $this;
    }

    /**
     * Unsets date created field.
     */
    public function unsetDateCreated(): self
    {
        $this->instance->unsetDateCreated();
        return $this;
    }

    /**
     * Sets date updated field.
     *
     * @param \DateTime|null $value
     */
    public function dateUpdated(?\DateTime $value): self
    {
        $this->instance->setDateUpdated($value);
        return $this;
    }

    /**
     * Unsets date updated field.
     */
    public function unsetDateUpdated(): self
    {
        $this->instance->unsetDateUpdated();
        return $this;
    }

    /**
     * Sets notification protocol version field.
     *
     * @param string|null $value
     */
    public function notificationProtocolVersion(?string $value): self
    {
        $this->instance->setNotificationProtocolVersion($value);
        return $this;
    }

    /**
     * Unsets notification protocol version field.
     */
    public function unsetNotificationProtocolVersion(): self
    {
        $this->instance->unsetNotificationProtocolVersion();
        return $this;
    }

    /**
     * Sets endpoint field.
     *
     * @param string|null $value
     */
    public function endpoint(?string $value): self
    {
        $this->instance->setEndpoint($value);
        return $this;
    }

    /**
     * Unsets endpoint field.
     */
    public function unsetEndpoint(): self
    {
        $this->instance->unsetEndpoint();
        return $this;
    }

    /**
     * Sets identity field.
     *
     * @param string|null $value
     */
    public function identity(?string $value): self
    {
        $this->instance->setIdentity($value);
        return $this;
    }

    /**
     * Unsets identity field.
     */
    public function unsetIdentity(): self
    {
        $this->instance->unsetIdentity();
        return $this;
    }

    /**
     * Sets binding type field.
     *
     * @param string|null $value
     */
    public function bindingType(?string $value): self
    {
        $this->instance->setBindingType($value);
        return $this;
    }

    /**
     * Unsets binding type field.
     */
    public function unsetBindingType(): self
    {
        $this->instance->unsetBindingType();
        return $this;
    }

    /**
     * Sets address field.
     *
     * @param string|null $value
     */
    public function address(?string $value): self
    {
        $this->instance->setAddress($value);
        return $this;
    }

    /**
     * Unsets address field.
     */
    public function unsetAddress(): self
    {
        $this->instance->unsetAddress();
        return $this;
    }

    /**
     * Sets tags field.
     *
     * @param string[]|null $value
     */
    public function tags(?array $value): self
    {
        $this->instance->setTags($value);
        return $this;
    }

    /**
     * Unsets tags field.
     */
    public function unsetTags(): self
    {
        $this->instance->unsetTags();
        return $this;
    }

    /**
     * Sets url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Unsets url field.
     */
    public function unsetUrl(): self
    {
        $this->instance->unsetUrl();
        return $this;
    }

    /**
     * Sets links field.
     *
     * @param array|null $value
     */
    public function links(?array $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Unsets links field.
     */
    public function unsetLinks(): self
    {
        $this->instance->unsetLinks();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Binding object.
     */
    public function build(): Binding
    {
        return CoreHelper::clone($this->instance);
    }
}
