<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use TwilioApIsLib\Models\ConversationWithParticipants;

/**
 * Builder for model ConversationWithParticipants
 *
 * @see ConversationWithParticipants
 */
class ConversationWithParticipantsBuilder
{
    /**
     * @var ConversationWithParticipants
     */
    private $instance;

    private function __construct(ConversationWithParticipants $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Conversation With Participants Builder object.
     */
    public static function init(): self
    {
        return new self(new ConversationWithParticipants());
    }

    /**
     * Sets account sid field.
     *
     * @param string|null $value
     */
    public function accountSid(?string $value): self
    {
        $this->instance->setAccountSid($value);
        return $this;
    }

    /**
     * Unsets account sid field.
     */
    public function unsetAccountSid(): self
    {
        $this->instance->unsetAccountSid();
        return $this;
    }

    /**
     * Sets chat service sid field.
     *
     * @param string|null $value
     */
    public function chatServiceSid(?string $value): self
    {
        $this->instance->setChatServiceSid($value);
        return $this;
    }

    /**
     * Unsets chat service sid field.
     */
    public function unsetChatServiceSid(): self
    {
        $this->instance->unsetChatServiceSid();
        return $this;
    }

    /**
     * Sets messaging service sid field.
     *
     * @param string|null $value
     */
    public function messagingServiceSid(?string $value): self
    {
        $this->instance->setMessagingServiceSid($value);
        return $this;
    }

    /**
     * Unsets messaging service sid field.
     */
    public function unsetMessagingServiceSid(): self
    {
        $this->instance->unsetMessagingServiceSid();
        return $this;
    }

    /**
     * Sets sid field.
     *
     * @param string|null $value
     */
    public function sid(?string $value): self
    {
        $this->instance->setSid($value);
        return $this;
    }

    /**
     * Unsets sid field.
     */
    public function unsetSid(): self
    {
        $this->instance->unsetSid();
        return $this;
    }

    /**
     * Sets friendly name field.
     *
     * @param string|null $value
     */
    public function friendlyName(?string $value): self
    {
        $this->instance->setFriendlyName($value);
        return $this;
    }

    /**
     * Unsets friendly name field.
     */
    public function unsetFriendlyName(): self
    {
        $this->instance->unsetFriendlyName();
        return $this;
    }

    /**
     * Sets unique name field.
     *
     * @param string|null $value
     */
    public function uniqueName(?string $value): self
    {
        $this->instance->setUniqueName($value);
        return $this;
    }

    /**
     * Unsets unique name field.
     */
    public function unsetUniqueName(): self
    {
        $this->instance->unsetUniqueName();
        return $this;
    }

    /**
     * Sets attributes field.
     *
     * @param string|null $value
     */
    public function attributes(?string $value): self
    {
        $this->instance->setAttributes($value);
        return $this;
    }

    /**
     * Unsets attributes field.
     */
    public function unsetAttributes(): self
    {
        $this->instance->unsetAttributes();
        return $this;
    }

    /**
     * Sets state field.
     *
     * @param string|null $value
     */
    public function state(?string $value): self
    {
        $this->instance->setState($value);
        return $this;
    }

    /**
     * Sets date created field.
     *
     * @param \DateTime|null $value
     */
    public function dateCreated(?\DateTime $value): self
    {
        $this->instance->setDateCreated($value);
        return $this;
    }

    /**
     * Unsets date created field.
     */
    public function unsetDateCreated(): self
    {
        $this->instance->unsetDateCreated();
        return $this;
    }

    /**
     * Sets date updated field.
     *
     * @param \DateTime|null $value
     */
    public function dateUpdated(?\DateTime $value): self
    {
        $this->instance->setDateUpdated($value);
        return $this;
    }

    /**
     * Unsets date updated field.
     */
    public function unsetDateUpdated(): self
    {
        $this->instance->unsetDateUpdated();
        return $this;
    }

    /**
     * Sets timers field.
     *
     * @param array|null $value
     */
    public function timers(?array $value): self
    {
        $this->instance->setTimers($value);
        return $this;
    }

    /**
     * Unsets timers field.
     */
    public function unsetTimers(): self
    {
        $this->instance->unsetTimers();
        return $this;
    }

    /**
     * Sets links field.
     *
     * @param array|null $value
     */
    public function links(?array $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Unsets links field.
     */
    public function unsetLinks(): self
    {
        $this->instance->unsetLinks();
        return $this;
    }

    /**
     * Sets bindings field.
     *
     * @param array|null $value
     */
    public function bindings(?array $value): self
    {
        $this->instance->setBindings($value);
        return $this;
    }

    /**
     * Unsets bindings field.
     */
    public function unsetBindings(): self
    {
        $this->instance->unsetBindings();
        return $this;
    }

    /**
     * Sets url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Unsets url field.
     */
    public function unsetUrl(): self
    {
        $this->instance->unsetUrl();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Conversation With Participants object.
     */
    public function build(): ConversationWithParticipants
    {
        return CoreHelper::clone($this->instance);
    }
}
