<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use TwilioApIsLib\Models\ListTaskQueueResponse;
use TwilioApIsLib\Models\Meta;
use TwilioApIsLib\Models\TaskQueue;

/**
 * Builder for model ListTaskQueueResponse
 *
 * @see ListTaskQueueResponse
 */
class ListTaskQueueResponseBuilder
{
    /**
     * @var ListTaskQueueResponse
     */
    private $instance;

    private function __construct(ListTaskQueueResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new List Task Queue Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ListTaskQueueResponse());
    }

    /**
     * Sets task queues field.
     *
     * @param TaskQueue[]|null $value
     */
    public function taskQueues(?array $value): self
    {
        $this->instance->setTaskQueues($value);
        return $this;
    }

    /**
     * Sets meta field.
     *
     * @param Meta|null $value
     */
    public function meta(?Meta $value): self
    {
        $this->instance->setMeta($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new List Task Queue Response object.
     */
    public function build(): ListTaskQueueResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
