<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use TwilioApIsLib\Models\ListTaskChannelResponse;
use TwilioApIsLib\Models\Meta;
use TwilioApIsLib\Models\TaskChannel;

/**
 * Builder for model ListTaskChannelResponse
 *
 * @see ListTaskChannelResponse
 */
class ListTaskChannelResponseBuilder
{
    /**
     * @var ListTaskChannelResponse
     */
    private $instance;

    private function __construct(ListTaskChannelResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new List Task Channel Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ListTaskChannelResponse());
    }

    /**
     * Sets channels field.
     *
     * @param TaskChannel[]|null $value
     */
    public function channels(?array $value): self
    {
        $this->instance->setChannels($value);
        return $this;
    }

    /**
     * Sets meta field.
     *
     * @param Meta|null $value
     */
    public function meta(?Meta $value): self
    {
        $this->instance->setMeta($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new List Task Channel Response object.
     */
    public function build(): ListTaskChannelResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
