<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use TwilioApIsLib\Models\ListWorkspaceResponse;
use TwilioApIsLib\Models\Meta;
use TwilioApIsLib\Models\Workspace;

/**
 * Builder for model ListWorkspaceResponse
 *
 * @see ListWorkspaceResponse
 */
class ListWorkspaceResponseBuilder
{
    /**
     * @var ListWorkspaceResponse
     */
    private $instance;

    private function __construct(ListWorkspaceResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new List Workspace Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ListWorkspaceResponse());
    }

    /**
     * Sets workspaces field.
     *
     * @param Workspace[]|null $value
     */
    public function workspaces(?array $value): self
    {
        $this->instance->setWorkspaces($value);
        return $this;
    }

    /**
     * Sets meta field.
     *
     * @param Meta|null $value
     */
    public function meta(?Meta $value): self
    {
        $this->instance->setMeta($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new List Workspace Response object.
     */
    public function build(): ListWorkspaceResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
