<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use TwilioApIsLib\Models\ConversationScopedWebhook;
use TwilioApIsLib\Models\ListConversationScopedWebhookResponse;
use TwilioApIsLib\Models\Meta;

/**
 * Builder for model ListConversationScopedWebhookResponse
 *
 * @see ListConversationScopedWebhookResponse
 */
class ListConversationScopedWebhookResponseBuilder
{
    /**
     * @var ListConversationScopedWebhookResponse
     */
    private $instance;

    private function __construct(ListConversationScopedWebhookResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new List Conversation Scoped Webhook Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ListConversationScopedWebhookResponse());
    }

    /**
     * Sets webhooks field.
     *
     * @param ConversationScopedWebhook[]|null $value
     */
    public function webhooks(?array $value): self
    {
        $this->instance->setWebhooks($value);
        return $this;
    }

    /**
     * Sets meta field.
     *
     * @param Meta|null $value
     */
    public function meta(?Meta $value): self
    {
        $this->instance->setMeta($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new List Conversation Scoped Webhook Response object.
     */
    public function build(): ListConversationScopedWebhookResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
