<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use TwilioApIsLib\Models\ParticipantConversation;

/**
 * Builder for model ParticipantConversation
 *
 * @see ParticipantConversation
 */
class ParticipantConversationBuilder
{
    /**
     * @var ParticipantConversation
     */
    private $instance;

    private function __construct(ParticipantConversation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Participant Conversation Builder object.
     */
    public static function init(): self
    {
        return new self(new ParticipantConversation());
    }

    /**
     * Sets account sid field.
     *
     * @param string|null $value
     */
    public function accountSid(?string $value): self
    {
        $this->instance->setAccountSid($value);
        return $this;
    }

    /**
     * Unsets account sid field.
     */
    public function unsetAccountSid(): self
    {
        $this->instance->unsetAccountSid();
        return $this;
    }

    /**
     * Sets chat service sid field.
     *
     * @param string|null $value
     */
    public function chatServiceSid(?string $value): self
    {
        $this->instance->setChatServiceSid($value);
        return $this;
    }

    /**
     * Unsets chat service sid field.
     */
    public function unsetChatServiceSid(): self
    {
        $this->instance->unsetChatServiceSid();
        return $this;
    }

    /**
     * Sets participant sid field.
     *
     * @param string|null $value
     */
    public function participantSid(?string $value): self
    {
        $this->instance->setParticipantSid($value);
        return $this;
    }

    /**
     * Unsets participant sid field.
     */
    public function unsetParticipantSid(): self
    {
        $this->instance->unsetParticipantSid();
        return $this;
    }

    /**
     * Sets participant user sid field.
     *
     * @param string|null $value
     */
    public function participantUserSid(?string $value): self
    {
        $this->instance->setParticipantUserSid($value);
        return $this;
    }

    /**
     * Unsets participant user sid field.
     */
    public function unsetParticipantUserSid(): self
    {
        $this->instance->unsetParticipantUserSid();
        return $this;
    }

    /**
     * Sets participant identity field.
     *
     * @param string|null $value
     */
    public function participantIdentity(?string $value): self
    {
        $this->instance->setParticipantIdentity($value);
        return $this;
    }

    /**
     * Unsets participant identity field.
     */
    public function unsetParticipantIdentity(): self
    {
        $this->instance->unsetParticipantIdentity();
        return $this;
    }

    /**
     * Sets participant messaging binding field.
     *
     * @param array|null $value
     */
    public function participantMessagingBinding(?array $value): self
    {
        $this->instance->setParticipantMessagingBinding($value);
        return $this;
    }

    /**
     * Unsets participant messaging binding field.
     */
    public function unsetParticipantMessagingBinding(): self
    {
        $this->instance->unsetParticipantMessagingBinding();
        return $this;
    }

    /**
     * Sets conversation sid field.
     *
     * @param string|null $value
     */
    public function conversationSid(?string $value): self
    {
        $this->instance->setConversationSid($value);
        return $this;
    }

    /**
     * Unsets conversation sid field.
     */
    public function unsetConversationSid(): self
    {
        $this->instance->unsetConversationSid();
        return $this;
    }

    /**
     * Sets conversation unique name field.
     *
     * @param string|null $value
     */
    public function conversationUniqueName(?string $value): self
    {
        $this->instance->setConversationUniqueName($value);
        return $this;
    }

    /**
     * Unsets conversation unique name field.
     */
    public function unsetConversationUniqueName(): self
    {
        $this->instance->unsetConversationUniqueName();
        return $this;
    }

    /**
     * Sets conversation friendly name field.
     *
     * @param string|null $value
     */
    public function conversationFriendlyName(?string $value): self
    {
        $this->instance->setConversationFriendlyName($value);
        return $this;
    }

    /**
     * Unsets conversation friendly name field.
     */
    public function unsetConversationFriendlyName(): self
    {
        $this->instance->unsetConversationFriendlyName();
        return $this;
    }

    /**
     * Sets conversation attributes field.
     *
     * @param string|null $value
     */
    public function conversationAttributes(?string $value): self
    {
        $this->instance->setConversationAttributes($value);
        return $this;
    }

    /**
     * Unsets conversation attributes field.
     */
    public function unsetConversationAttributes(): self
    {
        $this->instance->unsetConversationAttributes();
        return $this;
    }

    /**
     * Sets conversation date created field.
     *
     * @param \DateTime|null $value
     */
    public function conversationDateCreated(?\DateTime $value): self
    {
        $this->instance->setConversationDateCreated($value);
        return $this;
    }

    /**
     * Unsets conversation date created field.
     */
    public function unsetConversationDateCreated(): self
    {
        $this->instance->unsetConversationDateCreated();
        return $this;
    }

    /**
     * Sets conversation date updated field.
     *
     * @param \DateTime|null $value
     */
    public function conversationDateUpdated(?\DateTime $value): self
    {
        $this->instance->setConversationDateUpdated($value);
        return $this;
    }

    /**
     * Unsets conversation date updated field.
     */
    public function unsetConversationDateUpdated(): self
    {
        $this->instance->unsetConversationDateUpdated();
        return $this;
    }

    /**
     * Sets conversation created by field.
     *
     * @param string|null $value
     */
    public function conversationCreatedBy(?string $value): self
    {
        $this->instance->setConversationCreatedBy($value);
        return $this;
    }

    /**
     * Unsets conversation created by field.
     */
    public function unsetConversationCreatedBy(): self
    {
        $this->instance->unsetConversationCreatedBy();
        return $this;
    }

    /**
     * Sets conversation state field.
     *
     * @param string|null $value
     */
    public function conversationState(?string $value): self
    {
        $this->instance->setConversationState($value);
        return $this;
    }

    /**
     * Sets conversation timers field.
     *
     * @param array|null $value
     */
    public function conversationTimers(?array $value): self
    {
        $this->instance->setConversationTimers($value);
        return $this;
    }

    /**
     * Unsets conversation timers field.
     */
    public function unsetConversationTimers(): self
    {
        $this->instance->unsetConversationTimers();
        return $this;
    }

    /**
     * Sets links field.
     *
     * @param array|null $value
     */
    public function links(?array $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Unsets links field.
     */
    public function unsetLinks(): self
    {
        $this->instance->unsetLinks();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Participant Conversation object.
     */
    public function build(): ParticipantConversation
    {
        return CoreHelper::clone($this->instance);
    }
}
