<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use TwilioApIsLib\Models\ServiceWebhookConfiguration;

/**
 * Builder for model ServiceWebhookConfiguration
 *
 * @see ServiceWebhookConfiguration
 */
class ServiceWebhookConfigurationBuilder
{
    /**
     * @var ServiceWebhookConfiguration
     */
    private $instance;

    private function __construct(ServiceWebhookConfiguration $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Service Webhook Configuration Builder object.
     */
    public static function init(): self
    {
        return new self(new ServiceWebhookConfiguration());
    }

    /**
     * Sets account sid field.
     *
     * @param string|null $value
     */
    public function accountSid(?string $value): self
    {
        $this->instance->setAccountSid($value);
        return $this;
    }

    /**
     * Unsets account sid field.
     */
    public function unsetAccountSid(): self
    {
        $this->instance->unsetAccountSid();
        return $this;
    }

    /**
     * Sets chat service sid field.
     *
     * @param string|null $value
     */
    public function chatServiceSid(?string $value): self
    {
        $this->instance->setChatServiceSid($value);
        return $this;
    }

    /**
     * Unsets chat service sid field.
     */
    public function unsetChatServiceSid(): self
    {
        $this->instance->unsetChatServiceSid();
        return $this;
    }

    /**
     * Sets pre webhook url field.
     *
     * @param string|null $value
     */
    public function preWebhookUrl(?string $value): self
    {
        $this->instance->setPreWebhookUrl($value);
        return $this;
    }

    /**
     * Unsets pre webhook url field.
     */
    public function unsetPreWebhookUrl(): self
    {
        $this->instance->unsetPreWebhookUrl();
        return $this;
    }

    /**
     * Sets post webhook url field.
     *
     * @param string|null $value
     */
    public function postWebhookUrl(?string $value): self
    {
        $this->instance->setPostWebhookUrl($value);
        return $this;
    }

    /**
     * Unsets post webhook url field.
     */
    public function unsetPostWebhookUrl(): self
    {
        $this->instance->unsetPostWebhookUrl();
        return $this;
    }

    /**
     * Sets filters field.
     *
     * @param string[]|null $value
     */
    public function filters(?array $value): self
    {
        $this->instance->setFilters($value);
        return $this;
    }

    /**
     * Unsets filters field.
     */
    public function unsetFilters(): self
    {
        $this->instance->unsetFilters();
        return $this;
    }

    /**
     * Sets method field.
     *
     * @param string|null $value
     */
    public function method(?string $value): self
    {
        $this->instance->setMethod($value);
        return $this;
    }

    /**
     * Sets url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Unsets url field.
     */
    public function unsetUrl(): self
    {
        $this->instance->unsetUrl();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Service Webhook Configuration object.
     */
    public function build(): ServiceWebhookConfiguration
    {
        return CoreHelper::clone($this->instance);
    }
}
