<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use TwilioApIsLib\Models\ServiceRole;

/**
 * Builder for model ServiceRole
 *
 * @see ServiceRole
 */
class ServiceRoleBuilder
{
    /**
     * @var ServiceRole
     */
    private $instance;

    private function __construct(ServiceRole $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Service Role Builder object.
     */
    public static function init(): self
    {
        return new self(new ServiceRole());
    }

    /**
     * Sets sid field.
     *
     * @param string|null $value
     */
    public function sid(?string $value): self
    {
        $this->instance->setSid($value);
        return $this;
    }

    /**
     * Unsets sid field.
     */
    public function unsetSid(): self
    {
        $this->instance->unsetSid();
        return $this;
    }

    /**
     * Sets account sid field.
     *
     * @param string|null $value
     */
    public function accountSid(?string $value): self
    {
        $this->instance->setAccountSid($value);
        return $this;
    }

    /**
     * Unsets account sid field.
     */
    public function unsetAccountSid(): self
    {
        $this->instance->unsetAccountSid();
        return $this;
    }

    /**
     * Sets chat service sid field.
     *
     * @param string|null $value
     */
    public function chatServiceSid(?string $value): self
    {
        $this->instance->setChatServiceSid($value);
        return $this;
    }

    /**
     * Unsets chat service sid field.
     */
    public function unsetChatServiceSid(): self
    {
        $this->instance->unsetChatServiceSid();
        return $this;
    }

    /**
     * Sets friendly name field.
     *
     * @param string|null $value
     */
    public function friendlyName(?string $value): self
    {
        $this->instance->setFriendlyName($value);
        return $this;
    }

    /**
     * Unsets friendly name field.
     */
    public function unsetFriendlyName(): self
    {
        $this->instance->unsetFriendlyName();
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets permissions field.
     *
     * @param string[]|null $value
     */
    public function permissions(?array $value): self
    {
        $this->instance->setPermissions($value);
        return $this;
    }

    /**
     * Unsets permissions field.
     */
    public function unsetPermissions(): self
    {
        $this->instance->unsetPermissions();
        return $this;
    }

    /**
     * Sets date created field.
     *
     * @param \DateTime|null $value
     */
    public function dateCreated(?\DateTime $value): self
    {
        $this->instance->setDateCreated($value);
        return $this;
    }

    /**
     * Unsets date created field.
     */
    public function unsetDateCreated(): self
    {
        $this->instance->unsetDateCreated();
        return $this;
    }

    /**
     * Sets date updated field.
     *
     * @param \DateTime|null $value
     */
    public function dateUpdated(?\DateTime $value): self
    {
        $this->instance->setDateUpdated($value);
        return $this;
    }

    /**
     * Unsets date updated field.
     */
    public function unsetDateUpdated(): self
    {
        $this->instance->unsetDateUpdated();
        return $this;
    }

    /**
     * Sets url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Unsets url field.
     */
    public function unsetUrl(): self
    {
        $this->instance->unsetUrl();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Service Role object.
     */
    public function build(): ServiceRole
    {
        return CoreHelper::clone($this->instance);
    }
}
