<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use TwilioApIsLib\Models\TaskQueuesStats;

/**
 * Builder for model TaskQueuesStats
 *
 * @see TaskQueuesStats
 */
class TaskQueuesStatsBuilder
{
    /**
     * @var TaskQueuesStats
     */
    private $instance;

    private function __construct(TaskQueuesStats $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Task Queues Stats Builder object.
     */
    public static function init(): self
    {
        return new self(new TaskQueuesStats());
    }

    /**
     * Sets account sid field.
     *
     * @param string|null $value
     */
    public function accountSid(?string $value): self
    {
        $this->instance->setAccountSid($value);
        return $this;
    }

    /**
     * Unsets account sid field.
     */
    public function unsetAccountSid(): self
    {
        $this->instance->unsetAccountSid();
        return $this;
    }

    /**
     * Sets cumulative field.
     *
     * @param array|null $value
     */
    public function cumulative(?array $value): self
    {
        $this->instance->setCumulative($value);
        return $this;
    }

    /**
     * Unsets cumulative field.
     */
    public function unsetCumulative(): self
    {
        $this->instance->unsetCumulative();
        return $this;
    }

    /**
     * Sets realtime field.
     *
     * @param array|null $value
     */
    public function realtime(?array $value): self
    {
        $this->instance->setRealtime($value);
        return $this;
    }

    /**
     * Unsets realtime field.
     */
    public function unsetRealtime(): self
    {
        $this->instance->unsetRealtime();
        return $this;
    }

    /**
     * Sets task queue sid field.
     *
     * @param string|null $value
     */
    public function taskQueueSid(?string $value): self
    {
        $this->instance->setTaskQueueSid($value);
        return $this;
    }

    /**
     * Unsets task queue sid field.
     */
    public function unsetTaskQueueSid(): self
    {
        $this->instance->unsetTaskQueueSid();
        return $this;
    }

    /**
     * Sets workspace sid field.
     *
     * @param string|null $value
     */
    public function workspaceSid(?string $value): self
    {
        $this->instance->setWorkspaceSid($value);
        return $this;
    }

    /**
     * Unsets workspace sid field.
     */
    public function unsetWorkspaceSid(): self
    {
        $this->instance->unsetWorkspaceSid();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Task Queues Stats object.
     */
    public function build(): TaskQueuesStats
    {
        return CoreHelper::clone($this->instance);
    }
}
