<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use TwilioApIsLib\Models\TaskQueueCumulative;

/**
 * Builder for model TaskQueueCumulative
 *
 * @see TaskQueueCumulative
 */
class TaskQueueCumulativeBuilder
{
    /**
     * @var TaskQueueCumulative
     */
    private $instance;

    private function __construct(TaskQueueCumulative $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Task Queue Cumulative Builder object.
     */
    public static function init(): self
    {
        return new self(new TaskQueueCumulative());
    }

    /**
     * Sets account sid field.
     *
     * @param string|null $value
     */
    public function accountSid(?string $value): self
    {
        $this->instance->setAccountSid($value);
        return $this;
    }

    /**
     * Unsets account sid field.
     */
    public function unsetAccountSid(): self
    {
        $this->instance->unsetAccountSid();
        return $this;
    }

    /**
     * Sets avg task acceptance time field.
     *
     * @param int|null $value
     */
    public function avgTaskAcceptanceTime(?int $value): self
    {
        $this->instance->setAvgTaskAcceptanceTime($value);
        return $this;
    }

    /**
     * Sets start time field.
     *
     * @param \DateTime|null $value
     */
    public function startTime(?\DateTime $value): self
    {
        $this->instance->setStartTime($value);
        return $this;
    }

    /**
     * Unsets start time field.
     */
    public function unsetStartTime(): self
    {
        $this->instance->unsetStartTime();
        return $this;
    }

    /**
     * Sets end time field.
     *
     * @param \DateTime|null $value
     */
    public function endTime(?\DateTime $value): self
    {
        $this->instance->setEndTime($value);
        return $this;
    }

    /**
     * Unsets end time field.
     */
    public function unsetEndTime(): self
    {
        $this->instance->unsetEndTime();
        return $this;
    }

    /**
     * Sets reservations created field.
     *
     * @param int|null $value
     */
    public function reservationsCreated(?int $value): self
    {
        $this->instance->setReservationsCreated($value);
        return $this;
    }

    /**
     * Sets reservations accepted field.
     *
     * @param int|null $value
     */
    public function reservationsAccepted(?int $value): self
    {
        $this->instance->setReservationsAccepted($value);
        return $this;
    }

    /**
     * Sets reservations rejected field.
     *
     * @param int|null $value
     */
    public function reservationsRejected(?int $value): self
    {
        $this->instance->setReservationsRejected($value);
        return $this;
    }

    /**
     * Sets reservations timed out field.
     *
     * @param int|null $value
     */
    public function reservationsTimedOut(?int $value): self
    {
        $this->instance->setReservationsTimedOut($value);
        return $this;
    }

    /**
     * Sets reservations canceled field.
     *
     * @param int|null $value
     */
    public function reservationsCanceled(?int $value): self
    {
        $this->instance->setReservationsCanceled($value);
        return $this;
    }

    /**
     * Sets reservations rescinded field.
     *
     * @param int|null $value
     */
    public function reservationsRescinded(?int $value): self
    {
        $this->instance->setReservationsRescinded($value);
        return $this;
    }

    /**
     * Sets split by wait time field.
     *
     * @param array|null $value
     */
    public function splitByWaitTime(?array $value): self
    {
        $this->instance->setSplitByWaitTime($value);
        return $this;
    }

    /**
     * Unsets split by wait time field.
     */
    public function unsetSplitByWaitTime(): self
    {
        $this->instance->unsetSplitByWaitTime();
        return $this;
    }

    /**
     * Sets task queue sid field.
     *
     * @param string|null $value
     */
    public function taskQueueSid(?string $value): self
    {
        $this->instance->setTaskQueueSid($value);
        return $this;
    }

    /**
     * Unsets task queue sid field.
     */
    public function unsetTaskQueueSid(): self
    {
        $this->instance->unsetTaskQueueSid();
        return $this;
    }

    /**
     * Sets wait duration until accepted field.
     *
     * @param array|null $value
     */
    public function waitDurationUntilAccepted(?array $value): self
    {
        $this->instance->setWaitDurationUntilAccepted($value);
        return $this;
    }

    /**
     * Unsets wait duration until accepted field.
     */
    public function unsetWaitDurationUntilAccepted(): self
    {
        $this->instance->unsetWaitDurationUntilAccepted();
        return $this;
    }

    /**
     * Sets wait duration until canceled field.
     *
     * @param array|null $value
     */
    public function waitDurationUntilCanceled(?array $value): self
    {
        $this->instance->setWaitDurationUntilCanceled($value);
        return $this;
    }

    /**
     * Unsets wait duration until canceled field.
     */
    public function unsetWaitDurationUntilCanceled(): self
    {
        $this->instance->unsetWaitDurationUntilCanceled();
        return $this;
    }

    /**
     * Sets wait duration in queue until accepted field.
     *
     * @param array|null $value
     */
    public function waitDurationInQueueUntilAccepted(?array $value): self
    {
        $this->instance->setWaitDurationInQueueUntilAccepted($value);
        return $this;
    }

    /**
     * Unsets wait duration in queue until accepted field.
     */
    public function unsetWaitDurationInQueueUntilAccepted(): self
    {
        $this->instance->unsetWaitDurationInQueueUntilAccepted();
        return $this;
    }

    /**
     * Sets tasks canceled field.
     *
     * @param int|null $value
     */
    public function tasksCanceled(?int $value): self
    {
        $this->instance->setTasksCanceled($value);
        return $this;
    }

    /**
     * Sets tasks completed field.
     *
     * @param int|null $value
     */
    public function tasksCompleted(?int $value): self
    {
        $this->instance->setTasksCompleted($value);
        return $this;
    }

    /**
     * Sets tasks deleted field.
     *
     * @param int|null $value
     */
    public function tasksDeleted(?int $value): self
    {
        $this->instance->setTasksDeleted($value);
        return $this;
    }

    /**
     * Sets tasks entered field.
     *
     * @param int|null $value
     */
    public function tasksEntered(?int $value): self
    {
        $this->instance->setTasksEntered($value);
        return $this;
    }

    /**
     * Sets tasks moved field.
     *
     * @param int|null $value
     */
    public function tasksMoved(?int $value): self
    {
        $this->instance->setTasksMoved($value);
        return $this;
    }

    /**
     * Sets workspace sid field.
     *
     * @param string|null $value
     */
    public function workspaceSid(?string $value): self
    {
        $this->instance->setWorkspaceSid($value);
        return $this;
    }

    /**
     * Unsets workspace sid field.
     */
    public function unsetWorkspaceSid(): self
    {
        $this->instance->unsetWorkspaceSid();
        return $this;
    }

    /**
     * Sets url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Unsets url field.
     */
    public function unsetUrl(): self
    {
        $this->instance->unsetUrl();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Task Queue Cumulative object.
     */
    public function build(): TaskQueueCumulative
    {
        return CoreHelper::clone($this->instance);
    }
}
