<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use TwilioApIsLib\Models\WorkerInstanceStatistics;

/**
 * Builder for model WorkerInstanceStatistics
 *
 * @see WorkerInstanceStatistics
 */
class WorkerInstanceStatisticsBuilder
{
    /**
     * @var WorkerInstanceStatistics
     */
    private $instance;

    private function __construct(WorkerInstanceStatistics $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Worker Instance Statistics Builder object.
     */
    public static function init(): self
    {
        return new self(new WorkerInstanceStatistics());
    }

    /**
     * Sets account sid field.
     *
     * @param string|null $value
     */
    public function accountSid(?string $value): self
    {
        $this->instance->setAccountSid($value);
        return $this;
    }

    /**
     * Unsets account sid field.
     */
    public function unsetAccountSid(): self
    {
        $this->instance->unsetAccountSid();
        return $this;
    }

    /**
     * Sets cumulative field.
     *
     * @param array|null $value
     */
    public function cumulative(?array $value): self
    {
        $this->instance->setCumulative($value);
        return $this;
    }

    /**
     * Unsets cumulative field.
     */
    public function unsetCumulative(): self
    {
        $this->instance->unsetCumulative();
        return $this;
    }

    /**
     * Sets worker sid field.
     *
     * @param string|null $value
     */
    public function workerSid(?string $value): self
    {
        $this->instance->setWorkerSid($value);
        return $this;
    }

    /**
     * Unsets worker sid field.
     */
    public function unsetWorkerSid(): self
    {
        $this->instance->unsetWorkerSid();
        return $this;
    }

    /**
     * Sets workspace sid field.
     *
     * @param string|null $value
     */
    public function workspaceSid(?string $value): self
    {
        $this->instance->setWorkspaceSid($value);
        return $this;
    }

    /**
     * Unsets workspace sid field.
     */
    public function unsetWorkspaceSid(): self
    {
        $this->instance->unsetWorkspaceSid();
        return $this;
    }

    /**
     * Sets url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Unsets url field.
     */
    public function unsetUrl(): self
    {
        $this->instance->unsetUrl();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Worker Instance Statistics object.
     */
    public function build(): WorkerInstanceStatistics
    {
        return CoreHelper::clone($this->instance);
    }
}
