<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use TwilioApIsLib\Models\Worker;

/**
 * Builder for model Worker
 *
 * @see Worker
 */
class WorkerBuilder
{
    /**
     * @var Worker
     */
    private $instance;

    private function __construct(Worker $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Worker Builder object.
     */
    public static function init(): self
    {
        return new self(new Worker());
    }

    /**
     * Sets account sid field.
     *
     * @param string|null $value
     */
    public function accountSid(?string $value): self
    {
        $this->instance->setAccountSid($value);
        return $this;
    }

    /**
     * Unsets account sid field.
     */
    public function unsetAccountSid(): self
    {
        $this->instance->unsetAccountSid();
        return $this;
    }

    /**
     * Sets activity name field.
     *
     * @param string|null $value
     */
    public function activityName(?string $value): self
    {
        $this->instance->setActivityName($value);
        return $this;
    }

    /**
     * Unsets activity name field.
     */
    public function unsetActivityName(): self
    {
        $this->instance->unsetActivityName();
        return $this;
    }

    /**
     * Sets activity sid field.
     *
     * @param string|null $value
     */
    public function activitySid(?string $value): self
    {
        $this->instance->setActivitySid($value);
        return $this;
    }

    /**
     * Unsets activity sid field.
     */
    public function unsetActivitySid(): self
    {
        $this->instance->unsetActivitySid();
        return $this;
    }

    /**
     * Sets attributes field.
     *
     * @param string|null $value
     */
    public function attributes(?string $value): self
    {
        $this->instance->setAttributes($value);
        return $this;
    }

    /**
     * Unsets attributes field.
     */
    public function unsetAttributes(): self
    {
        $this->instance->unsetAttributes();
        return $this;
    }

    /**
     * Sets available field.
     *
     * @param bool|null $value
     */
    public function available(?bool $value): self
    {
        $this->instance->setAvailable($value);
        return $this;
    }

    /**
     * Unsets available field.
     */
    public function unsetAvailable(): self
    {
        $this->instance->unsetAvailable();
        return $this;
    }

    /**
     * Sets date created field.
     *
     * @param \DateTime|null $value
     */
    public function dateCreated(?\DateTime $value): self
    {
        $this->instance->setDateCreated($value);
        return $this;
    }

    /**
     * Unsets date created field.
     */
    public function unsetDateCreated(): self
    {
        $this->instance->unsetDateCreated();
        return $this;
    }

    /**
     * Sets date status changed field.
     *
     * @param \DateTime|null $value
     */
    public function dateStatusChanged(?\DateTime $value): self
    {
        $this->instance->setDateStatusChanged($value);
        return $this;
    }

    /**
     * Unsets date status changed field.
     */
    public function unsetDateStatusChanged(): self
    {
        $this->instance->unsetDateStatusChanged();
        return $this;
    }

    /**
     * Sets date updated field.
     *
     * @param \DateTime|null $value
     */
    public function dateUpdated(?\DateTime $value): self
    {
        $this->instance->setDateUpdated($value);
        return $this;
    }

    /**
     * Unsets date updated field.
     */
    public function unsetDateUpdated(): self
    {
        $this->instance->unsetDateUpdated();
        return $this;
    }

    /**
     * Sets friendly name field.
     *
     * @param string|null $value
     */
    public function friendlyName(?string $value): self
    {
        $this->instance->setFriendlyName($value);
        return $this;
    }

    /**
     * Unsets friendly name field.
     */
    public function unsetFriendlyName(): self
    {
        $this->instance->unsetFriendlyName();
        return $this;
    }

    /**
     * Sets sid field.
     *
     * @param string|null $value
     */
    public function sid(?string $value): self
    {
        $this->instance->setSid($value);
        return $this;
    }

    /**
     * Unsets sid field.
     */
    public function unsetSid(): self
    {
        $this->instance->unsetSid();
        return $this;
    }

    /**
     * Sets workspace sid field.
     *
     * @param string|null $value
     */
    public function workspaceSid(?string $value): self
    {
        $this->instance->setWorkspaceSid($value);
        return $this;
    }

    /**
     * Unsets workspace sid field.
     */
    public function unsetWorkspaceSid(): self
    {
        $this->instance->unsetWorkspaceSid();
        return $this;
    }

    /**
     * Sets url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Unsets url field.
     */
    public function unsetUrl(): self
    {
        $this->instance->unsetUrl();
        return $this;
    }

    /**
     * Sets links field.
     *
     * @param array|null $value
     */
    public function links(?array $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Unsets links field.
     */
    public function unsetLinks(): self
    {
        $this->instance->unsetLinks();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Worker object.
     */
    public function build(): Worker
    {
        return CoreHelper::clone($this->instance);
    }
}
