<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use TwilioApIsLib\Models\WorkerChannel;

/**
 * Builder for model WorkerChannel
 *
 * @see WorkerChannel
 */
class WorkerChannelBuilder
{
    /**
     * @var WorkerChannel
     */
    private $instance;

    private function __construct(WorkerChannel $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Worker Channel Builder object.
     */
    public static function init(): self
    {
        return new self(new WorkerChannel());
    }

    /**
     * Sets account sid field.
     *
     * @param string|null $value
     */
    public function accountSid(?string $value): self
    {
        $this->instance->setAccountSid($value);
        return $this;
    }

    /**
     * Unsets account sid field.
     */
    public function unsetAccountSid(): self
    {
        $this->instance->unsetAccountSid();
        return $this;
    }

    /**
     * Sets assigned tasks field.
     *
     * @param int|null $value
     */
    public function assignedTasks(?int $value): self
    {
        $this->instance->setAssignedTasks($value);
        return $this;
    }

    /**
     * Sets available field.
     *
     * @param bool|null $value
     */
    public function available(?bool $value): self
    {
        $this->instance->setAvailable($value);
        return $this;
    }

    /**
     * Unsets available field.
     */
    public function unsetAvailable(): self
    {
        $this->instance->unsetAvailable();
        return $this;
    }

    /**
     * Sets available capacity percentage field.
     *
     * @param int|null $value
     */
    public function availableCapacityPercentage(?int $value): self
    {
        $this->instance->setAvailableCapacityPercentage($value);
        return $this;
    }

    /**
     * Sets configured capacity field.
     *
     * @param int|null $value
     */
    public function configuredCapacity(?int $value): self
    {
        $this->instance->setConfiguredCapacity($value);
        return $this;
    }

    /**
     * Sets date created field.
     *
     * @param \DateTime|null $value
     */
    public function dateCreated(?\DateTime $value): self
    {
        $this->instance->setDateCreated($value);
        return $this;
    }

    /**
     * Unsets date created field.
     */
    public function unsetDateCreated(): self
    {
        $this->instance->unsetDateCreated();
        return $this;
    }

    /**
     * Sets date updated field.
     *
     * @param \DateTime|null $value
     */
    public function dateUpdated(?\DateTime $value): self
    {
        $this->instance->setDateUpdated($value);
        return $this;
    }

    /**
     * Unsets date updated field.
     */
    public function unsetDateUpdated(): self
    {
        $this->instance->unsetDateUpdated();
        return $this;
    }

    /**
     * Sets sid field.
     *
     * @param string|null $value
     */
    public function sid(?string $value): self
    {
        $this->instance->setSid($value);
        return $this;
    }

    /**
     * Unsets sid field.
     */
    public function unsetSid(): self
    {
        $this->instance->unsetSid();
        return $this;
    }

    /**
     * Sets task channel sid field.
     *
     * @param string|null $value
     */
    public function taskChannelSid(?string $value): self
    {
        $this->instance->setTaskChannelSid($value);
        return $this;
    }

    /**
     * Unsets task channel sid field.
     */
    public function unsetTaskChannelSid(): self
    {
        $this->instance->unsetTaskChannelSid();
        return $this;
    }

    /**
     * Sets task channel unique name field.
     *
     * @param string|null $value
     */
    public function taskChannelUniqueName(?string $value): self
    {
        $this->instance->setTaskChannelUniqueName($value);
        return $this;
    }

    /**
     * Unsets task channel unique name field.
     */
    public function unsetTaskChannelUniqueName(): self
    {
        $this->instance->unsetTaskChannelUniqueName();
        return $this;
    }

    /**
     * Sets worker sid field.
     *
     * @param string|null $value
     */
    public function workerSid(?string $value): self
    {
        $this->instance->setWorkerSid($value);
        return $this;
    }

    /**
     * Unsets worker sid field.
     */
    public function unsetWorkerSid(): self
    {
        $this->instance->unsetWorkerSid();
        return $this;
    }

    /**
     * Sets workspace sid field.
     *
     * @param string|null $value
     */
    public function workspaceSid(?string $value): self
    {
        $this->instance->setWorkspaceSid($value);
        return $this;
    }

    /**
     * Unsets workspace sid field.
     */
    public function unsetWorkspaceSid(): self
    {
        $this->instance->unsetWorkspaceSid();
        return $this;
    }

    /**
     * Sets url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Unsets url field.
     */
    public function unsetUrl(): self
    {
        $this->instance->unsetUrl();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Worker Channel object.
     */
    public function build(): WorkerChannel
    {
        return CoreHelper::clone($this->instance);
    }
}
