<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use TwilioApIsLib\Models\Workspace;

/**
 * Builder for model Workspace
 *
 * @see Workspace
 */
class WorkspaceBuilder
{
    /**
     * @var Workspace
     */
    private $instance;

    private function __construct(Workspace $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Workspace Builder object.
     */
    public static function init(): self
    {
        return new self(new Workspace());
    }

    /**
     * Sets account sid field.
     *
     * @param string|null $value
     */
    public function accountSid(?string $value): self
    {
        $this->instance->setAccountSid($value);
        return $this;
    }

    /**
     * Unsets account sid field.
     */
    public function unsetAccountSid(): self
    {
        $this->instance->unsetAccountSid();
        return $this;
    }

    /**
     * Sets date created field.
     *
     * @param \DateTime|null $value
     */
    public function dateCreated(?\DateTime $value): self
    {
        $this->instance->setDateCreated($value);
        return $this;
    }

    /**
     * Unsets date created field.
     */
    public function unsetDateCreated(): self
    {
        $this->instance->unsetDateCreated();
        return $this;
    }

    /**
     * Sets date updated field.
     *
     * @param \DateTime|null $value
     */
    public function dateUpdated(?\DateTime $value): self
    {
        $this->instance->setDateUpdated($value);
        return $this;
    }

    /**
     * Unsets date updated field.
     */
    public function unsetDateUpdated(): self
    {
        $this->instance->unsetDateUpdated();
        return $this;
    }

    /**
     * Sets default activity name field.
     *
     * @param string|null $value
     */
    public function defaultActivityName(?string $value): self
    {
        $this->instance->setDefaultActivityName($value);
        return $this;
    }

    /**
     * Unsets default activity name field.
     */
    public function unsetDefaultActivityName(): self
    {
        $this->instance->unsetDefaultActivityName();
        return $this;
    }

    /**
     * Sets default activity sid field.
     *
     * @param string|null $value
     */
    public function defaultActivitySid(?string $value): self
    {
        $this->instance->setDefaultActivitySid($value);
        return $this;
    }

    /**
     * Unsets default activity sid field.
     */
    public function unsetDefaultActivitySid(): self
    {
        $this->instance->unsetDefaultActivitySid();
        return $this;
    }

    /**
     * Sets event callback url field.
     *
     * @param string|null $value
     */
    public function eventCallbackUrl(?string $value): self
    {
        $this->instance->setEventCallbackUrl($value);
        return $this;
    }

    /**
     * Unsets event callback url field.
     */
    public function unsetEventCallbackUrl(): self
    {
        $this->instance->unsetEventCallbackUrl();
        return $this;
    }

    /**
     * Sets events filter field.
     *
     * @param string|null $value
     */
    public function eventsFilter(?string $value): self
    {
        $this->instance->setEventsFilter($value);
        return $this;
    }

    /**
     * Unsets events filter field.
     */
    public function unsetEventsFilter(): self
    {
        $this->instance->unsetEventsFilter();
        return $this;
    }

    /**
     * Sets friendly name field.
     *
     * @param string|null $value
     */
    public function friendlyName(?string $value): self
    {
        $this->instance->setFriendlyName($value);
        return $this;
    }

    /**
     * Unsets friendly name field.
     */
    public function unsetFriendlyName(): self
    {
        $this->instance->unsetFriendlyName();
        return $this;
    }

    /**
     * Sets multi task enabled field.
     *
     * @param bool|null $value
     */
    public function multiTaskEnabled(?bool $value): self
    {
        $this->instance->setMultiTaskEnabled($value);
        return $this;
    }

    /**
     * Unsets multi task enabled field.
     */
    public function unsetMultiTaskEnabled(): self
    {
        $this->instance->unsetMultiTaskEnabled();
        return $this;
    }

    /**
     * Sets sid field.
     *
     * @param string|null $value
     */
    public function sid(?string $value): self
    {
        $this->instance->setSid($value);
        return $this;
    }

    /**
     * Unsets sid field.
     */
    public function unsetSid(): self
    {
        $this->instance->unsetSid();
        return $this;
    }

    /**
     * Sets timeout activity name field.
     *
     * @param string|null $value
     */
    public function timeoutActivityName(?string $value): self
    {
        $this->instance->setTimeoutActivityName($value);
        return $this;
    }

    /**
     * Unsets timeout activity name field.
     */
    public function unsetTimeoutActivityName(): self
    {
        $this->instance->unsetTimeoutActivityName();
        return $this;
    }

    /**
     * Sets timeout activity sid field.
     *
     * @param string|null $value
     */
    public function timeoutActivitySid(?string $value): self
    {
        $this->instance->setTimeoutActivitySid($value);
        return $this;
    }

    /**
     * Unsets timeout activity sid field.
     */
    public function unsetTimeoutActivitySid(): self
    {
        $this->instance->unsetTimeoutActivitySid();
        return $this;
    }

    /**
     * Sets prioritize queue order field.
     *
     * @param string|null $value
     */
    public function prioritizeQueueOrder(?string $value): self
    {
        $this->instance->setPrioritizeQueueOrder($value);
        return $this;
    }

    /**
     * Sets url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Unsets url field.
     */
    public function unsetUrl(): self
    {
        $this->instance->unsetUrl();
        return $this;
    }

    /**
     * Sets links field.
     *
     * @param array|null $value
     */
    public function links(?array $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Unsets links field.
     */
    public function unsetLinks(): self
    {
        $this->instance->unsetLinks();
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Workspace object.
     */
    public function build(): Workspace
    {
        return CoreHelper::clone($this->instance);
    }
}
