<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Apis;

use Core\Request\Parameters\FormParam;
use Core\Request\Parameters\HeaderParam;
use Core\Request\Parameters\TemplateParam;
use CoreInterfaces\Core\Request\RequestMethod;
use TwilioApIsLib\Http\ApiResponse;
use TwilioApIsLib\Models\ApiV2010AccountMessage;
use TwilioApIsLib\Models\MessageEnumAddressRetention;
use TwilioApIsLib\Models\MessageEnumContentRetention;
use TwilioApIsLib\Models\MessageEnumScheduleType;
use TwilioApIsLib\Models\MessageEnumTrafficType;
use TwilioApIsLib\Models\VerificationEnumRiskCheck;
use TwilioApIsLib\Server;
use TwilioApIsLib\Utils\DateTimeHelper;

class SmsApi extends BaseApi
{
    /**
     * Send a message
     *
     * @param string $accountSid The SID of the
     *        [Account](https://www.twilio.com/docs/iam/api/account) creating the Message resource.
     * @param string $to The recipient's phone number in
     *        [E.164](https://www.twilio.com/docs/glossary/what-e164) format (for SMS/MMS) or
     *        [channel address](https://www.twilio.com/docs/messaging/channels), e.g. `whatsapp:
     *        +15552229999`.
     * @param string|null $statusCallback The URL of the endpoint to which Twilio sends [Message
     *        status callback requests](https://www.twilio.com/docs/sms/api/message-
     *        resource#twilios-request-to-the-statuscallback-url). URL must contain a valid
     *        hostname and underscores are not allowed. If you include this parameter with the
     *        `messaging_service_sid`, Twilio uses this URL instead of the Status Callback URL of
     *        the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource).
     * @param string|null $applicationSid The SID of the associated [TwiML
     *        Application](https://www.twilio.com/docs/usage/api/applications). [Message status
     *        callback requests](https://www.twilio.com/docs/sms/api/message-resource#twilios-
     *        request-to-the-statuscallback-url) are sent to the TwiML App's
     *        `message_status_callback` URL. Note that the `status_callback` parameter of a
     *        request takes priority over the `application_sid` parameter; if both are included
     *        `application_sid` is ignored.
     * @param float|null $maxPrice [OBSOLETE] This parameter will no longer have any effect as of
     *        2024-06-03.
     * @param bool|null $provideFeedback Boolean indicating whether or not you intend to provide
     *        delivery confirmation feedback to Twilio (used in conjunction with the [Message
     *        Feedback subresource](https://www.twilio.com/docs/sms/api/message-feedback-
     *        resource)). Default value is `false`.
     * @param int|null $attempt Total number of attempts made (including this request) to send the
     *        message regardless of the provider used
     * @param int|null $validityPeriod The maximum length in seconds that the Message can remain in
     *        Twilio's outgoing message queue. If a queued Message exceeds the `validity_period`,
     *        the Message is not sent. Accepted values are integers from `1` to `36000`. Default
     *        value is `36000`. A `validity_period` greater than `5` is recommended. [Learn more
     *        about the validity period](https://www.twilio.com/blog/take-more-control-of-outbound-
     *        messages-using-validity-period-html)
     * @param bool|null $forceDelivery Reserved
     * @param string|null $contentRetention Determines if the message content can be stored or
     *        redacted based on privacy settings
     * @param string|null $addressRetention Determines if the address can be stored or obfuscated
     *        based on privacy settings
     * @param bool|null $smartEncoded Whether to detect Unicode characters that have a similar GSM-7
     *        character and replace them. Can be: `true` or `false`.
     * @param string[]|null $persistentAction Rich actions for non-SMS/MMS channels. Used for
     *        [sending location in WhatsApp messages](https://www.twilio.com/docs/whatsapp/message-
     *        features#location-messages-with-whatsapp).
     * @param string|null $trafficType
     * @param bool|null $shortenUrls For Messaging Services with [Link Shortening
     *        configured](https://www.twilio.com/docs/messaging/features/link-shortening) only: A
     *        Boolean indicating whether or not Twilio should shorten links in the `body` of the
     *        Message. Default value is `false`. If `true`, the `messaging_service_sid` parameter
     *        must also be provided.
     * @param string|null $scheduleType For Messaging Services only: Include this parameter with a
     *        value of `fixed` in conjuction with the `send_time` parameter in order to [schedule
     *        a Message](https://www.twilio.com/docs/messaging/features/message-scheduling).
     * @param \DateTime|null $sendAt The time that Twilio will send the message. Must be in ISO 8601
     *        format.
     * @param bool|null $sendAsMms If set to `true`, Twilio delivers the message as a single MMS
     *        message, regardless of the presence of media.
     * @param string|null $contentVariables For [Content
     *        Editor/API](https://www.twilio.com/docs/content) only: Key-value pairs of [Template
     *        variables](https://www.twilio.com/docs/content/using-variables-with-content-api) and
     *        their substitution values. `content_sid` parameter must also be provided. If values
     *        are not defined in the `content_variables` parameter, the [Template's default
     *        placeholder values](https://www.twilio.com/docs/content/content-api-resources#create-
     *        templates) are used.
     * @param string|null $riskCheck Include this parameter with a value of `disable` to skip any
     *        kind of risk check on the respective message request.
     * @param string|null $from The sender's Twilio phone number (in
     *        [E.164](https://en.wikipedia.org/wiki/E.164) format), [alphanumeric sender ID](https:
     *        //www.twilio.com/docs/sms/quickstart), [Wireless SIM](https://www.twilio.
     *        com/docs/iot/wireless/programmable-wireless-send-machine-machine-sms-commands),
     *        [short code](https://www.twilio.com/en-us/messaging/channels/sms/short-codes), or
     *        [channel address](https://www.twilio.com/docs/messaging/channels) (e.g., `whatsapp:
     *        +15554449999`). The value of the `from` parameter must be a sender that is hosted
     *        within Twilio and belongs to the Account creating the Message. If you are using
     *        `messaging_service_sid`, this parameter can be empty (Twilio assigns a `from` value
     *        from the Messaging Service's Sender Pool) or you can provide a specific sender from
     *        your Sender Pool.
     * @param string|null $messagingServiceSid The SID of the [Messaging
     *        Service](https://www.twilio.com/docs/messaging/services) you want to associate with
     *        the Message. When this parameter is provided and the `from` parameter is omitted,
     *        Twilio selects the optimal sender from the Messaging Service's Sender Pool. You may
     *        also provide a `from` parameter if you want to use a specific Sender from the Sender
     *        Pool.
     * @param string|null $body The text content of the outgoing message. Can be up to 1,600
     *        characters in length. SMS only: If the `body` contains more than 160 [GSM-7](https:
     *        //www.twilio.com/docs/glossary/what-is-gsm-7-character-encoding) characters (or 70
     *        [UCS-2](https://www.twilio.com/docs/glossary/what-is-ucs-2-character-encoding)
     *        characters), the message is segmented and charged accordingly. For long `body` text,
     *        consider using the [send_as_mms parameter](https://www.twilio.com/blog/mms-for-long-
     *        text-messages).
     * @param string[]|null $mediaUrl The URL of media to include in the Message content. `jpeg`,
     *        `jpg`, `gif`, and `png` file types are fully supported by Twilio and content is
     *        formatted for delivery on destination devices. The media size limit is 5 MB for
     *        supported file types (`jpeg`, `jpg`, `png`, `gif`) and 500 KB for [other
     *        types](https://www.twilio.com/docs/messaging/guides/accepted-mime-types) of accepted
     *        media. To send more than one image in the message, provide multiple `media_url`
     *        parameters in the POST request. You can include up to ten `media_url` parameters per
     *        message. [International](https://support.twilio.com/hc/en-us/articles/223179808-
     *        Sending-and-receiving-MMS-messages) and [carrier](https://support.twilio.com/hc/en-
     *        us/articles/223133707-Is-MMS-supported-for-all-carriers-in-US-and-Canada-) limits
     *        apply.
     * @param string|null $contentSid For [Content Editor/API](https://www.twilio.com/docs/content)
     *        only: The SID of the Content Template to be used with the Message, e.g.,
     *        `HXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`. If this parameter is not provided, a Content
     *        Template is not used. Find the SID in the Console on the Content Editor page. For
     *        Content API users, the SID is found in Twilio's response when [creating the
     *        Template](https://www.twilio.com/docs/content/content-api-resources#create-
     *        templates) or by [fetching your Templates](https://www.twilio.
     *        com/docs/content/content-api-resources#fetch-all-content-resources).
     *
     * @return ApiResponse Response from the API call
     */
    public function createMessage(
        string $accountSid,
        string $to,
        ?string $statusCallback = null,
        ?string $applicationSid = null,
        ?float $maxPrice = null,
        ?bool $provideFeedback = null,
        ?int $attempt = null,
        ?int $validityPeriod = null,
        ?bool $forceDelivery = null,
        ?string $contentRetention = null,
        ?string $addressRetention = null,
        ?bool $smartEncoded = null,
        ?array $persistentAction = null,
        ?string $trafficType = null,
        ?bool $shortenUrls = null,
        ?string $scheduleType = null,
        ?\DateTime $sendAt = null,
        ?bool $sendAsMms = null,
        ?string $contentVariables = null,
        ?string $riskCheck = null,
        ?string $from = null,
        ?string $messagingServiceSid = null,
        ?string $body = null,
        ?array $mediaUrl = null,
        ?string $contentSid = null
    ): ApiResponse {
        $_reqBuilder = $this->requestBuilder(
            RequestMethod::POST,
            '/2010-04-01/Accounts/{AccountSid}/Messages.json'
        )
            ->server(Server::DEFAULT6)
            ->auth('accountSid_authToken')
            ->parameters(
                TemplateParam::init('AccountSid', $accountSid)->required(),
                HeaderParam::init('Content-Type', 'application/x-www-form-urlencoded'),
                FormParam::init('To', $to)->required(),
                FormParam::init('StatusCallback', $statusCallback),
                FormParam::init('ApplicationSid', $applicationSid),
                FormParam::init('MaxPrice', $maxPrice),
                FormParam::init('ProvideFeedback', $provideFeedback),
                FormParam::init('Attempt', $attempt),
                FormParam::init('ValidityPeriod', $validityPeriod),
                FormParam::init('ForceDelivery', $forceDelivery),
                FormParam::init('ContentRetention', $contentRetention)
                    ->serializeBy([MessageEnumContentRetention::class, 'checkValue']),
                FormParam::init('AddressRetention', $addressRetention)
                    ->serializeBy([MessageEnumAddressRetention::class, 'checkValue']),
                FormParam::init('SmartEncoded', $smartEncoded),
                FormParam::init('PersistentAction', $persistentAction),
                FormParam::init('TrafficType', $trafficType)
                    ->serializeBy([MessageEnumTrafficType::class, 'checkValue']),
                FormParam::init('ShortenUrls', $shortenUrls),
                FormParam::init('ScheduleType', $scheduleType)
                    ->serializeBy([MessageEnumScheduleType::class, 'checkValue']),
                FormParam::init('SendAt', $sendAt)->serializeBy([DateTimeHelper::class, 'toRfc3339DateTime']),
                FormParam::init('SendAsMms', $sendAsMms),
                FormParam::init('ContentVariables', $contentVariables),
                FormParam::init('RiskCheck', $riskCheck)
                    ->serializeBy([VerificationEnumRiskCheck::class, 'checkValue']),
                FormParam::init('From', $from),
                FormParam::init('MessagingServiceSid', $messagingServiceSid),
                FormParam::init('Body', $body),
                FormParam::init('MediaUrl', $mediaUrl),
                FormParam::init('ContentSid', $contentSid)
            );

        $_resHandler = $this->responseHandler()->type(ApiV2010AccountMessage::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
