<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Apis;

use Core\Request\Parameters\FormParam;
use Core\Request\Parameters\HeaderParam;
use CoreInterfaces\Core\Request\RequestMethod;
use TwilioApIsLib\Http\ApiResponse;
use TwilioApIsLib\Models\Service2;
use TwilioApIsLib\Server;

class VerifyV2ServiceApi extends BaseApi
{
    /**
     * Create a new Verification Service.
     *
     * @param string $friendlyName A descriptive string that you create to describe the verification
     *        service. It can be up to 32 characters long. **This value should not contain PII.**
     * @param int|null $codeLength The length of the verification code to generate. Must be an
     *        integer value between 4 and 10, inclusive.
     * @param bool|null $lookupEnabled Whether to perform a lookup with each verification started
     *        and return info about the phone number.
     * @param bool|null $skipSmsToLandlines Whether to skip sending SMS verifications to landlines.
     *        Requires `lookup_enabled`.
     * @param bool|null $dtmfInputRequired Whether to ask the user to press a number before
     *        delivering the verify code in a phone call.
     * @param string|null $ttsName The name of an alternative text-to-speech service to use in phone
     *        calls. Applies only to TTS languages.
     * @param bool|null $psd2Enabled Whether to pass PSD2 transaction parameters when starting a
     *        verification.
     * @param bool|null $doNotShareWarningEnabled Whether to add a security warning at the end of an
     *        SMS verification body. Disabled by default and applies only to SMS. Example SMS body:
     *        `Your AppName verification code is: 1234. Don’t share this code with anyone; our
     *        employees will never ask for the code`
     * @param bool|null $customCodeEnabled Whether to allow sending verifications with a custom code
     *        instead of a randomly generated one.
     * @param bool|null $pushIncludeDate Optional configuration for the Push factors. If true,
     *        include the date in the Challenge's response. Otherwise, the date is omitted from
     *        the response. See [Challenge](https://www.twilio.com/docs/verify/api/challenge)
     *        resource’s details parameter for more info. Default: false. **Deprecated** do not
     *        use this parameter. This timestamp value is the same one as the one found in
     *        `date_created`, please use that one instead.
     * @param string|null $pushApnCredentialSid Optional configuration for the Push factors. Set the
     *        APN Credential for this service. This will allow to send push notifications to iOS
     *        devices. See [Credential Resource](https://www.twilio.com/docs/notify/api/credential-
     *        resource)
     * @param string|null $pushFcmCredentialSid Optional configuration for the Push factors. Set the
     *        FCM Credential for this service. This will allow to send push notifications to
     *        Android devices. See [Credential Resource](https://www.twilio.
     *        com/docs/notify/api/credential-resource)
     * @param string|null $totpIssuer Optional configuration for the TOTP factors. Set TOTP Issuer
     *        for this service. This will allow to configure the issuer of the TOTP URI. Defaults
     *        to the service friendly name if not provided.
     * @param int|null $totpTimeStep Optional configuration for the TOTP factors. Defines how often,
     *        in seconds, are TOTP codes generated. i.e, a new TOTP code is generated every
     *        time_step seconds. Must be between 20 and 60 seconds, inclusive. Defaults to 30
     *        seconds
     * @param int|null $totpCodeLength Optional configuration for the TOTP factors. Number of digits
     *        for generated TOTP codes. Must be between 3 and 8, inclusive. Defaults to 6
     * @param int|null $totpSkew Optional configuration for the TOTP factors. The number of
     *        time-steps, past and future, that are valid for validation of TOTP codes. Must be
     *        between 0 and 2, inclusive. Defaults to 1
     * @param string|null $defaultTemplateSid The default message
     *        [template](https://www.twilio.com/docs/verify/api/templates). Will be used for all
     *        SMS verifications unless explicitly overriden. SMS channel only.
     * @param string|null $whatsappMsgServiceSid The SID of the Messaging Service containing
     *        WhatsApp Sender(s) that Verify will use to send WhatsApp messages to your users.
     * @param string|null $whatsappFrom The number to use as the WhatsApp Sender that Verify will
     *        use to send WhatsApp messages to your users.This WhatsApp Sender must be associated
     *        with a Messaging Service SID.
     * @param string|null $passkeysRelyingPartyId The Relying Party ID for Passkeys. This is the
     *        domain of your application, e.g. `example.com`. It is used to identify your
     *        application when creating Passkeys.
     * @param string|null $passkeysRelyingPartyName The Relying Party Name for Passkeys. This is the
     *        name of your application, e.g. `Example App`. It is used to identify your
     *        application when creating Passkeys.
     * @param string|null $passkeysRelyingPartyOrigins The Relying Party Origins for Passkeys. This
     *        is the origin of your application, e.g. `login.example.com,www.example.com`. It is
     *        used to identify your application when creating Passkeys, it can have multiple
     *        origins split by `,`.
     * @param string|null $passkeysAuthenticatorAttachment The Authenticator Attachment for
     *        Passkeys. This is the type of authenticator that will be used to create Passkeys. It
     *        can be empty or it can have the values `platform`, `cross-platform` or `any`.
     * @param string|null $passkeysDiscoverableCredentials Indicates whether credentials must be
     *        discoverable by the authenticator. It can be empty or it can have the values
     *        `required`, `preferred` or `discouraged`.
     * @param string|null $passkeysUserVerification The User Verification for Passkeys. This is the
     *        type of user verification that will be used to create Passkeys. It can be empty or
     *        it can have the values `required`, `preferred` or `discouraged`.
     * @param bool|null $verifyEventSubscriptionEnabled Whether to allow verifications from the
     *        service to reach the stream-events sinks if configured
     *
     * @return ApiResponse Response from the API call
     */
    public function createService(
        string $friendlyName,
        ?int $codeLength = null,
        ?bool $lookupEnabled = null,
        ?bool $skipSmsToLandlines = null,
        ?bool $dtmfInputRequired = null,
        ?string $ttsName = null,
        ?bool $psd2Enabled = null,
        ?bool $doNotShareWarningEnabled = null,
        ?bool $customCodeEnabled = null,
        ?bool $pushIncludeDate = null,
        ?string $pushApnCredentialSid = null,
        ?string $pushFcmCredentialSid = null,
        ?string $totpIssuer = null,
        ?int $totpTimeStep = null,
        ?int $totpCodeLength = null,
        ?int $totpSkew = null,
        ?string $defaultTemplateSid = null,
        ?string $whatsappMsgServiceSid = null,
        ?string $whatsappFrom = null,
        ?string $passkeysRelyingPartyId = null,
        ?string $passkeysRelyingPartyName = null,
        ?string $passkeysRelyingPartyOrigins = null,
        ?string $passkeysAuthenticatorAttachment = null,
        ?string $passkeysDiscoverableCredentials = null,
        ?string $passkeysUserVerification = null,
        ?bool $verifyEventSubscriptionEnabled = null
    ): ApiResponse {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/v2/Services')
            ->server(Server::DEFAULT5)
            ->auth('accountSid_authToken')
            ->parameters(
                HeaderParam::init('Content-Type', 'application/x-www-form-urlencoded'),
                FormParam::init('FriendlyName', $friendlyName)->required(),
                FormParam::init('CodeLength', $codeLength),
                FormParam::init('LookupEnabled', $lookupEnabled),
                FormParam::init('SkipSmsToLandlines', $skipSmsToLandlines),
                FormParam::init('DtmfInputRequired', $dtmfInputRequired),
                FormParam::init('TtsName', $ttsName),
                FormParam::init('Psd2Enabled', $psd2Enabled),
                FormParam::init('DoNotShareWarningEnabled', $doNotShareWarningEnabled),
                FormParam::init('CustomCodeEnabled', $customCodeEnabled),
                FormParam::init('Push.IncludeDate', $pushIncludeDate),
                FormParam::init('Push.ApnCredentialSid', $pushApnCredentialSid),
                FormParam::init('Push.FcmCredentialSid', $pushFcmCredentialSid),
                FormParam::init('Totp.Issuer', $totpIssuer),
                FormParam::init('Totp.TimeStep', $totpTimeStep),
                FormParam::init('Totp.CodeLength', $totpCodeLength),
                FormParam::init('Totp.Skew', $totpSkew),
                FormParam::init('DefaultTemplateSid', $defaultTemplateSid),
                FormParam::init('Whatsapp.MsgServiceSid', $whatsappMsgServiceSid),
                FormParam::init('Whatsapp.From', $whatsappFrom),
                FormParam::init('Passkeys.RelyingParty.Id', $passkeysRelyingPartyId),
                FormParam::init('Passkeys.RelyingParty.Name', $passkeysRelyingPartyName),
                FormParam::init('Passkeys.RelyingParty.Origins', $passkeysRelyingPartyOrigins),
                FormParam::init('Passkeys.AuthenticatorAttachment', $passkeysAuthenticatorAttachment),
                FormParam::init('Passkeys.DiscoverableCredentials', $passkeysDiscoverableCredentials),
                FormParam::init('Passkeys.UserVerification', $passkeysUserVerification),
                FormParam::init('VerifyEventSubscriptionEnabled', $verifyEventSubscriptionEnabled)
            );

        $_resHandler = $this->responseHandler()->type(Service2::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
