<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Exceptions;

use TwilioApIsLib\ApiHelper;

class V2ServicesVerifications429ErrorException extends ApiException
{
    /**
     * @var int|null
     */
    private $codeProperty;

    /**
     * @var string|null
     */
    private $messageProperty;

    /**
     * @var string|null
     */
    private $moreInfo;

    /**
     * @var int|null
     */
    private $status;

    /**
     * Returns Code Property.
     * Twilio-specific error code
     */
    public function getCodeProperty(): ?int
    {
        return $this->codeProperty;
    }

    /**
     * Sets Code Property.
     * Twilio-specific error code
     *
     * @maps code
     */
    public function setCodeProperty(?int $codeProperty): void
    {
        $this->codeProperty = $codeProperty;
    }

    /**
     * Returns Message Property.
     * Error message
     */
    public function getMessageProperty(): ?string
    {
        return $this->messageProperty;
    }

    /**
     * Sets Message Property.
     * Error message
     *
     * @maps message
     */
    public function setMessageProperty(?string $messageProperty): void
    {
        $this->messageProperty = $messageProperty;
    }

    /**
     * Returns More Info.
     * Link to Error Code References
     */
    public function getMoreInfo(): ?string
    {
        return $this->moreInfo;
    }

    /**
     * Sets More Info.
     * Link to Error Code References
     *
     * @maps more_info
     */
    public function setMoreInfo(?string $moreInfo): void
    {
        $this->moreInfo = $moreInfo;
    }

    /**
     * Returns Status.
     * HTTP response status code
     */
    public function getStatus(): ?int
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * HTTP response status code
     *
     * @maps status
     */
    public function setStatus(?int $status): void
    {
        $this->status = $status;
    }

    /**
     * Converts the V2ServicesVerifications429ErrorException object to a human-readable string
     * representation.
     *
     * @return string The string representation of the V2ServicesVerifications429ErrorException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'V2ServicesVerifications429ErrorException',
            [
                'codeProperty' => $this->codeProperty,
                'messageProperty' => $this->messageProperty,
                'moreInfo' => $this->moreInfo,
                'status' => $this->status,
                'additionalProperties' => $this->additionalProperties
            ],
            parent::__toString()
        );
    }

    protected $propertyNames = ['code', 'message', 'more_info', 'status'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }
}
