<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models;

use stdClass;
use TwilioApIsLib\ApiHelper;
use TwilioApIsLib\Utils\DateTimeHelper;

class ConversationParticipant implements \JsonSerializable
{
    /**
     * @var array
     */
    private $accountSid = [];

    /**
     * @var array
     */
    private $conversationSid = [];

    /**
     * @var array
     */
    private $sid = [];

    /**
     * @var array
     */
    private $identity = [];

    /**
     * @var array
     */
    private $attributes = [];

    /**
     * @var array
     */
    private $messagingBinding = [];

    /**
     * @var array
     */
    private $roleSid = [];

    /**
     * @var array
     */
    private $dateCreated = [];

    /**
     * @var array
     */
    private $dateUpdated = [];

    /**
     * @var array
     */
    private $url = [];

    /**
     * @var array
     */
    private $lastReadMessageIndex = [];

    /**
     * @var array
     */
    private $lastReadTimestamp = [];

    /**
     * Returns Account Sid.
     * The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this
     * participant.
     */
    public function getAccountSid(): ?string
    {
        if (count($this->accountSid) == 0) {
            return null;
        }
        return $this->accountSid['value'];
    }

    /**
     * Sets Account Sid.
     * The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this
     * participant.
     *
     * @maps account_sid
     */
    public function setAccountSid(?string $accountSid): void
    {
        $this->accountSid['value'] = $accountSid;
    }

    /**
     * Unsets Account Sid.
     * The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this
     * participant.
     */
    public function unsetAccountSid(): void
    {
        $this->accountSid = [];
    }

    /**
     * Returns Conversation Sid.
     * The unique ID of the [Conversation](https://www.twilio.com/docs/conversations/api/conversation-
     * resource) for this participant.
     */
    public function getConversationSid(): ?string
    {
        if (count($this->conversationSid) == 0) {
            return null;
        }
        return $this->conversationSid['value'];
    }

    /**
     * Sets Conversation Sid.
     * The unique ID of the [Conversation](https://www.twilio.com/docs/conversations/api/conversation-
     * resource) for this participant.
     *
     * @maps conversation_sid
     */
    public function setConversationSid(?string $conversationSid): void
    {
        $this->conversationSid['value'] = $conversationSid;
    }

    /**
     * Unsets Conversation Sid.
     * The unique ID of the [Conversation](https://www.twilio.com/docs/conversations/api/conversation-
     * resource) for this participant.
     */
    public function unsetConversationSid(): void
    {
        $this->conversationSid = [];
    }

    /**
     * Returns Sid.
     * A 34 character string that uniquely identifies this resource.
     */
    public function getSid(): ?string
    {
        if (count($this->sid) == 0) {
            return null;
        }
        return $this->sid['value'];
    }

    /**
     * Sets Sid.
     * A 34 character string that uniquely identifies this resource.
     *
     * @maps sid
     */
    public function setSid(?string $sid): void
    {
        $this->sid['value'] = $sid;
    }

    /**
     * Unsets Sid.
     * A 34 character string that uniquely identifies this resource.
     */
    public function unsetSid(): void
    {
        $this->sid = [];
    }

    /**
     * Returns Identity.
     * A unique string identifier for the conversation participant as [Conversation User](https://www.
     * twilio.com/docs/conversations/api/user-resource). This parameter is non-null if (and only if) the
     * participant is using the Conversations SDK to communicate. Limited to 256 characters.
     */
    public function getIdentity(): ?string
    {
        if (count($this->identity) == 0) {
            return null;
        }
        return $this->identity['value'];
    }

    /**
     * Sets Identity.
     * A unique string identifier for the conversation participant as [Conversation User](https://www.
     * twilio.com/docs/conversations/api/user-resource). This parameter is non-null if (and only if) the
     * participant is using the Conversations SDK to communicate. Limited to 256 characters.
     *
     * @maps identity
     */
    public function setIdentity(?string $identity): void
    {
        $this->identity['value'] = $identity;
    }

    /**
     * Unsets Identity.
     * A unique string identifier for the conversation participant as [Conversation User](https://www.
     * twilio.com/docs/conversations/api/user-resource). This parameter is non-null if (and only if) the
     * participant is using the Conversations SDK to communicate. Limited to 256 characters.
     */
    public function unsetIdentity(): void
    {
        $this->identity = [];
    }

    /**
     * Returns Attributes.
     * An optional string metadata field you can use to store any data you wish. The string value must
     * contain structurally valid JSON if specified.  **Note** that if the attributes are not set "{}" will
     * be returned.
     */
    public function getAttributes(): ?string
    {
        if (count($this->attributes) == 0) {
            return null;
        }
        return $this->attributes['value'];
    }

    /**
     * Sets Attributes.
     * An optional string metadata field you can use to store any data you wish. The string value must
     * contain structurally valid JSON if specified.  **Note** that if the attributes are not set "{}" will
     * be returned.
     *
     * @maps attributes
     */
    public function setAttributes(?string $attributes): void
    {
        $this->attributes['value'] = $attributes;
    }

    /**
     * Unsets Attributes.
     * An optional string metadata field you can use to store any data you wish. The string value must
     * contain structurally valid JSON if specified.  **Note** that if the attributes are not set "{}" will
     * be returned.
     */
    public function unsetAttributes(): void
    {
        $this->attributes = [];
    }

    /**
     * Returns Messaging Binding.
     * Information about how this participant exchanges messages with the conversation. A JSON parameter
     * consisting of type and address fields of the participant.
     */
    public function getMessagingBinding(): ?array
    {
        if (count($this->messagingBinding) == 0) {
            return null;
        }
        return $this->messagingBinding['value'];
    }

    /**
     * Sets Messaging Binding.
     * Information about how this participant exchanges messages with the conversation. A JSON parameter
     * consisting of type and address fields of the participant.
     *
     * @maps messaging_binding
     */
    public function setMessagingBinding(?array $messagingBinding): void
    {
        $this->messagingBinding['value'] = $messagingBinding;
    }

    /**
     * Unsets Messaging Binding.
     * Information about how this participant exchanges messages with the conversation. A JSON parameter
     * consisting of type and address fields of the participant.
     */
    public function unsetMessagingBinding(): void
    {
        $this->messagingBinding = [];
    }

    /**
     * Returns Role Sid.
     * The SID of a conversation-level [Role](https://www.twilio.com/docs/conversations/api/role-resource)
     * to assign to the participant.
     */
    public function getRoleSid(): ?string
    {
        if (count($this->roleSid) == 0) {
            return null;
        }
        return $this->roleSid['value'];
    }

    /**
     * Sets Role Sid.
     * The SID of a conversation-level [Role](https://www.twilio.com/docs/conversations/api/role-resource)
     * to assign to the participant.
     *
     * @maps role_sid
     */
    public function setRoleSid(?string $roleSid): void
    {
        $this->roleSid['value'] = $roleSid;
    }

    /**
     * Unsets Role Sid.
     * The SID of a conversation-level [Role](https://www.twilio.com/docs/conversations/api/role-resource)
     * to assign to the participant.
     */
    public function unsetRoleSid(): void
    {
        $this->roleSid = [];
    }

    /**
     * Returns Date Created.
     * The date that this resource was created.
     */
    public function getDateCreated(): ?\DateTime
    {
        if (count($this->dateCreated) == 0) {
            return null;
        }
        return $this->dateCreated['value'];
    }

    /**
     * Sets Date Created.
     * The date that this resource was created.
     *
     * @maps date_created
     * @factory \TwilioApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateCreated(?\DateTime $dateCreated): void
    {
        $this->dateCreated['value'] = $dateCreated;
    }

    /**
     * Unsets Date Created.
     * The date that this resource was created.
     */
    public function unsetDateCreated(): void
    {
        $this->dateCreated = [];
    }

    /**
     * Returns Date Updated.
     * The date that this resource was last updated.
     */
    public function getDateUpdated(): ?\DateTime
    {
        if (count($this->dateUpdated) == 0) {
            return null;
        }
        return $this->dateUpdated['value'];
    }

    /**
     * Sets Date Updated.
     * The date that this resource was last updated.
     *
     * @maps date_updated
     * @factory \TwilioApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateUpdated(?\DateTime $dateUpdated): void
    {
        $this->dateUpdated['value'] = $dateUpdated;
    }

    /**
     * Unsets Date Updated.
     * The date that this resource was last updated.
     */
    public function unsetDateUpdated(): void
    {
        $this->dateUpdated = [];
    }

    /**
     * Returns Url.
     * An absolute API resource URL for this participant.
     */
    public function getUrl(): ?string
    {
        if (count($this->url) == 0) {
            return null;
        }
        return $this->url['value'];
    }

    /**
     * Sets Url.
     * An absolute API resource URL for this participant.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url['value'] = $url;
    }

    /**
     * Unsets Url.
     * An absolute API resource URL for this participant.
     */
    public function unsetUrl(): void
    {
        $this->url = [];
    }

    /**
     * Returns Last Read Message Index.
     * Index of last “read” message in the [Conversation](https://www.twilio.
     * com/docs/conversations/api/conversation-resource) for the Participant.
     */
    public function getLastReadMessageIndex(): ?int
    {
        if (count($this->lastReadMessageIndex) == 0) {
            return null;
        }
        return $this->lastReadMessageIndex['value'];
    }

    /**
     * Sets Last Read Message Index.
     * Index of last “read” message in the [Conversation](https://www.twilio.
     * com/docs/conversations/api/conversation-resource) for the Participant.
     *
     * @maps last_read_message_index
     */
    public function setLastReadMessageIndex(?int $lastReadMessageIndex): void
    {
        $this->lastReadMessageIndex['value'] = $lastReadMessageIndex;
    }

    /**
     * Unsets Last Read Message Index.
     * Index of last “read” message in the [Conversation](https://www.twilio.
     * com/docs/conversations/api/conversation-resource) for the Participant.
     */
    public function unsetLastReadMessageIndex(): void
    {
        $this->lastReadMessageIndex = [];
    }

    /**
     * Returns Last Read Timestamp.
     * Timestamp of last “read” message in the [Conversation](https://www.twilio.
     * com/docs/conversations/api/conversation-resource) for the Participant.
     */
    public function getLastReadTimestamp(): ?string
    {
        if (count($this->lastReadTimestamp) == 0) {
            return null;
        }
        return $this->lastReadTimestamp['value'];
    }

    /**
     * Sets Last Read Timestamp.
     * Timestamp of last “read” message in the [Conversation](https://www.twilio.
     * com/docs/conversations/api/conversation-resource) for the Participant.
     *
     * @maps last_read_timestamp
     */
    public function setLastReadTimestamp(?string $lastReadTimestamp): void
    {
        $this->lastReadTimestamp['value'] = $lastReadTimestamp;
    }

    /**
     * Unsets Last Read Timestamp.
     * Timestamp of last “read” message in the [Conversation](https://www.twilio.
     * com/docs/conversations/api/conversation-resource) for the Participant.
     */
    public function unsetLastReadTimestamp(): void
    {
        $this->lastReadTimestamp = [];
    }

    /**
     * Converts the ConversationParticipant object to a human-readable string representation.
     *
     * @return string The string representation of the ConversationParticipant object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ConversationParticipant',
            [
                'accountSid' => $this->getAccountSid(),
                'conversationSid' => $this->getConversationSid(),
                'sid' => $this->getSid(),
                'identity' => $this->getIdentity(),
                'attributes' => $this->getAttributes(),
                'messagingBinding' => $this->getMessagingBinding(),
                'roleSid' => $this->getRoleSid(),
                'dateCreated' => $this->getDateCreated(),
                'dateUpdated' => $this->getDateUpdated(),
                'url' => $this->getUrl(),
                'lastReadMessageIndex' => $this->getLastReadMessageIndex(),
                'lastReadTimestamp' => $this->getLastReadTimestamp(),
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'account_sid',
        'conversation_sid',
        'sid',
        'identity',
        'attributes',
        'messaging_binding',
        'role_sid',
        'date_created',
        'date_updated',
        'url',
        'last_read_message_index',
        'last_read_timestamp'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->accountSid)) {
            $json['account_sid']             = $this->accountSid['value'];
        }
        if (!empty($this->conversationSid)) {
            $json['conversation_sid']        = $this->conversationSid['value'];
        }
        if (!empty($this->sid)) {
            $json['sid']                     = $this->sid['value'];
        }
        if (!empty($this->identity)) {
            $json['identity']                = $this->identity['value'];
        }
        if (!empty($this->attributes)) {
            $json['attributes']              = $this->attributes['value'];
        }
        if (!empty($this->messagingBinding)) {
            $json['messaging_binding']       = $this->messagingBinding['value'];
        }
        if (!empty($this->roleSid)) {
            $json['role_sid']                = $this->roleSid['value'];
        }
        if (!empty($this->dateCreated)) {
            $json['date_created']            = DateTimeHelper::toRfc3339DateTime($this->dateCreated['value']);
        }
        if (!empty($this->dateUpdated)) {
            $json['date_updated']            = DateTimeHelper::toRfc3339DateTime($this->dateUpdated['value']);
        }
        if (!empty($this->url)) {
            $json['url']                     = $this->url['value'];
        }
        if (!empty($this->lastReadMessageIndex)) {
            $json['last_read_message_index'] = $this->lastReadMessageIndex['value'];
        }
        if (!empty($this->lastReadTimestamp)) {
            $json['last_read_timestamp']     = $this->lastReadTimestamp['value'];
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
