<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models;

use stdClass;
use TwilioApIsLib\ApiHelper;
use TwilioApIsLib\Utils\DateTimeHelper;

class ConversationMessage implements \JsonSerializable
{
    /**
     * @var array
     */
    private $accountSid = [];

    /**
     * @var array
     */
    private $conversationSid = [];

    /**
     * @var array
     */
    private $sid = [];

    /**
     * @var int|null
     */
    private $index = 0;

    /**
     * @var array
     */
    private $author = [];

    /**
     * @var array
     */
    private $body = [];

    /**
     * @var array
     */
    private $media = [];

    /**
     * @var array
     */
    private $attributes = [];

    /**
     * @var array
     */
    private $participantSid = [];

    /**
     * @var array
     */
    private $dateCreated = [];

    /**
     * @var array
     */
    private $dateUpdated = [];

    /**
     * @var array
     */
    private $url = [];

    /**
     * @var array
     */
    private $delivery = [];

    /**
     * @var array
     */
    private $links = [];

    /**
     * @var array
     */
    private $contentSid = [];

    /**
     * Returns Account Sid.
     * The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this
     * message.
     */
    public function getAccountSid(): ?string
    {
        if (count($this->accountSid) == 0) {
            return null;
        }
        return $this->accountSid['value'];
    }

    /**
     * Sets Account Sid.
     * The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this
     * message.
     *
     * @maps account_sid
     */
    public function setAccountSid(?string $accountSid): void
    {
        $this->accountSid['value'] = $accountSid;
    }

    /**
     * Unsets Account Sid.
     * The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this
     * message.
     */
    public function unsetAccountSid(): void
    {
        $this->accountSid = [];
    }

    /**
     * Returns Conversation Sid.
     * The unique ID of the [Conversation](https://www.twilio.com/docs/conversations/api/conversation-
     * resource) for this message.
     */
    public function getConversationSid(): ?string
    {
        if (count($this->conversationSid) == 0) {
            return null;
        }
        return $this->conversationSid['value'];
    }

    /**
     * Sets Conversation Sid.
     * The unique ID of the [Conversation](https://www.twilio.com/docs/conversations/api/conversation-
     * resource) for this message.
     *
     * @maps conversation_sid
     */
    public function setConversationSid(?string $conversationSid): void
    {
        $this->conversationSid['value'] = $conversationSid;
    }

    /**
     * Unsets Conversation Sid.
     * The unique ID of the [Conversation](https://www.twilio.com/docs/conversations/api/conversation-
     * resource) for this message.
     */
    public function unsetConversationSid(): void
    {
        $this->conversationSid = [];
    }

    /**
     * Returns Sid.
     * A 34 character string that uniquely identifies this resource.
     */
    public function getSid(): ?string
    {
        if (count($this->sid) == 0) {
            return null;
        }
        return $this->sid['value'];
    }

    /**
     * Sets Sid.
     * A 34 character string that uniquely identifies this resource.
     *
     * @maps sid
     */
    public function setSid(?string $sid): void
    {
        $this->sid['value'] = $sid;
    }

    /**
     * Unsets Sid.
     * A 34 character string that uniquely identifies this resource.
     */
    public function unsetSid(): void
    {
        $this->sid = [];
    }

    /**
     * Returns Index.
     * The index of the message within the [Conversation](https://www.twilio.
     * com/docs/conversations/api/conversation-resource).  Indices may skip numbers, but will always be in
     * order of when the message was received.
     */
    public function getIndex(): ?int
    {
        return $this->index;
    }

    /**
     * Sets Index.
     * The index of the message within the [Conversation](https://www.twilio.
     * com/docs/conversations/api/conversation-resource).  Indices may skip numbers, but will always be in
     * order of when the message was received.
     *
     * @maps index
     */
    public function setIndex(?int $index): void
    {
        $this->index = $index;
    }

    /**
     * Returns Author.
     * The channel specific identifier of the message's author. Defaults to `system`.
     */
    public function getAuthor(): ?string
    {
        if (count($this->author) == 0) {
            return null;
        }
        return $this->author['value'];
    }

    /**
     * Sets Author.
     * The channel specific identifier of the message's author. Defaults to `system`.
     *
     * @maps author
     */
    public function setAuthor(?string $author): void
    {
        $this->author['value'] = $author;
    }

    /**
     * Unsets Author.
     * The channel specific identifier of the message's author. Defaults to `system`.
     */
    public function unsetAuthor(): void
    {
        $this->author = [];
    }

    /**
     * Returns Body.
     * The content of the message, can be up to 1,600 characters long.
     */
    public function getBody(): ?string
    {
        if (count($this->body) == 0) {
            return null;
        }
        return $this->body['value'];
    }

    /**
     * Sets Body.
     * The content of the message, can be up to 1,600 characters long.
     *
     * @maps body
     */
    public function setBody(?string $body): void
    {
        $this->body['value'] = $body;
    }

    /**
     * Unsets Body.
     * The content of the message, can be up to 1,600 characters long.
     */
    public function unsetBody(): void
    {
        $this->body = [];
    }

    /**
     * Returns Media.
     * An array of objects that describe the Message's media, if the message contains media. Each object
     * contains these fields: `content_type` with the MIME type of the media, `filename` with the name of
     * the media, `sid` with the SID of the Media resource, and `size` with the media object's file size in
     * bytes. If the Message has no media, this value is `null`.
     *
     * @return array[]|null
     */
    public function getMedia(): ?array
    {
        if (count($this->media) == 0) {
            return null;
        }
        return $this->media['value'];
    }

    /**
     * Sets Media.
     * An array of objects that describe the Message's media, if the message contains media. Each object
     * contains these fields: `content_type` with the MIME type of the media, `filename` with the name of
     * the media, `sid` with the SID of the Media resource, and `size` with the media object's file size in
     * bytes. If the Message has no media, this value is `null`.
     *
     * @maps media
     *
     * @param array[]|null $media
     */
    public function setMedia(?array $media): void
    {
        $this->media['value'] = $media;
    }

    /**
     * Unsets Media.
     * An array of objects that describe the Message's media, if the message contains media. Each object
     * contains these fields: `content_type` with the MIME type of the media, `filename` with the name of
     * the media, `sid` with the SID of the Media resource, and `size` with the media object's file size in
     * bytes. If the Message has no media, this value is `null`.
     */
    public function unsetMedia(): void
    {
        $this->media = [];
    }

    /**
     * Returns Attributes.
     * A string metadata field you can use to store any data you wish. The string value must contain
     * structurally valid JSON if specified.  **Note** that if the attributes are not set "{}" will be
     * returned.
     */
    public function getAttributes(): ?string
    {
        if (count($this->attributes) == 0) {
            return null;
        }
        return $this->attributes['value'];
    }

    /**
     * Sets Attributes.
     * A string metadata field you can use to store any data you wish. The string value must contain
     * structurally valid JSON if specified.  **Note** that if the attributes are not set "{}" will be
     * returned.
     *
     * @maps attributes
     */
    public function setAttributes(?string $attributes): void
    {
        $this->attributes['value'] = $attributes;
    }

    /**
     * Unsets Attributes.
     * A string metadata field you can use to store any data you wish. The string value must contain
     * structurally valid JSON if specified.  **Note** that if the attributes are not set "{}" will be
     * returned.
     */
    public function unsetAttributes(): void
    {
        $this->attributes = [];
    }

    /**
     * Returns Participant Sid.
     * The unique ID of messages's author participant. Null in case of `system` sent message.
     */
    public function getParticipantSid(): ?string
    {
        if (count($this->participantSid) == 0) {
            return null;
        }
        return $this->participantSid['value'];
    }

    /**
     * Sets Participant Sid.
     * The unique ID of messages's author participant. Null in case of `system` sent message.
     *
     * @maps participant_sid
     */
    public function setParticipantSid(?string $participantSid): void
    {
        $this->participantSid['value'] = $participantSid;
    }

    /**
     * Unsets Participant Sid.
     * The unique ID of messages's author participant. Null in case of `system` sent message.
     */
    public function unsetParticipantSid(): void
    {
        $this->participantSid = [];
    }

    /**
     * Returns Date Created.
     * The date that this resource was created.
     */
    public function getDateCreated(): ?\DateTime
    {
        if (count($this->dateCreated) == 0) {
            return null;
        }
        return $this->dateCreated['value'];
    }

    /**
     * Sets Date Created.
     * The date that this resource was created.
     *
     * @maps date_created
     * @factory \TwilioApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateCreated(?\DateTime $dateCreated): void
    {
        $this->dateCreated['value'] = $dateCreated;
    }

    /**
     * Unsets Date Created.
     * The date that this resource was created.
     */
    public function unsetDateCreated(): void
    {
        $this->dateCreated = [];
    }

    /**
     * Returns Date Updated.
     * The date that this resource was last updated. `null` if the message has not been edited.
     */
    public function getDateUpdated(): ?\DateTime
    {
        if (count($this->dateUpdated) == 0) {
            return null;
        }
        return $this->dateUpdated['value'];
    }

    /**
     * Sets Date Updated.
     * The date that this resource was last updated. `null` if the message has not been edited.
     *
     * @maps date_updated
     * @factory \TwilioApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateUpdated(?\DateTime $dateUpdated): void
    {
        $this->dateUpdated['value'] = $dateUpdated;
    }

    /**
     * Unsets Date Updated.
     * The date that this resource was last updated. `null` if the message has not been edited.
     */
    public function unsetDateUpdated(): void
    {
        $this->dateUpdated = [];
    }

    /**
     * Returns Url.
     * An absolute API resource API URL for this message.
     */
    public function getUrl(): ?string
    {
        if (count($this->url) == 0) {
            return null;
        }
        return $this->url['value'];
    }

    /**
     * Sets Url.
     * An absolute API resource API URL for this message.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url['value'] = $url;
    }

    /**
     * Unsets Url.
     * An absolute API resource API URL for this message.
     */
    public function unsetUrl(): void
    {
        $this->url = [];
    }

    /**
     * Returns Delivery.
     * An object that contains the summary of delivery statuses for the message to non-chat participants.
     */
    public function getDelivery(): ?array
    {
        if (count($this->delivery) == 0) {
            return null;
        }
        return $this->delivery['value'];
    }

    /**
     * Sets Delivery.
     * An object that contains the summary of delivery statuses for the message to non-chat participants.
     *
     * @maps delivery
     */
    public function setDelivery(?array $delivery): void
    {
        $this->delivery['value'] = $delivery;
    }

    /**
     * Unsets Delivery.
     * An object that contains the summary of delivery statuses for the message to non-chat participants.
     */
    public function unsetDelivery(): void
    {
        $this->delivery = [];
    }

    /**
     * Returns Links.
     * Contains an absolute API resource URL to access the delivery & read receipts of this message.
     */
    public function getLinks(): ?array
    {
        if (count($this->links) == 0) {
            return null;
        }
        return $this->links['value'];
    }

    /**
     * Sets Links.
     * Contains an absolute API resource URL to access the delivery & read receipts of this message.
     *
     * @maps links
     */
    public function setLinks(?array $links): void
    {
        $this->links['value'] = $links;
    }

    /**
     * Unsets Links.
     * Contains an absolute API resource URL to access the delivery & read receipts of this message.
     */
    public function unsetLinks(): void
    {
        $this->links = [];
    }

    /**
     * Returns Content Sid.
     * The unique ID of the multi-channel [Rich Content](https://www.twilio.com/docs/content) template.
     */
    public function getContentSid(): ?string
    {
        if (count($this->contentSid) == 0) {
            return null;
        }
        return $this->contentSid['value'];
    }

    /**
     * Sets Content Sid.
     * The unique ID of the multi-channel [Rich Content](https://www.twilio.com/docs/content) template.
     *
     * @maps content_sid
     */
    public function setContentSid(?string $contentSid): void
    {
        $this->contentSid['value'] = $contentSid;
    }

    /**
     * Unsets Content Sid.
     * The unique ID of the multi-channel [Rich Content](https://www.twilio.com/docs/content) template.
     */
    public function unsetContentSid(): void
    {
        $this->contentSid = [];
    }

    /**
     * Converts the ConversationMessage object to a human-readable string representation.
     *
     * @return string The string representation of the ConversationMessage object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ConversationMessage',
            [
                'accountSid' => $this->getAccountSid(),
                'conversationSid' => $this->getConversationSid(),
                'sid' => $this->getSid(),
                'index' => $this->index,
                'author' => $this->getAuthor(),
                'body' => $this->getBody(),
                'media' => $this->getMedia(),
                'attributes' => $this->getAttributes(),
                'participantSid' => $this->getParticipantSid(),
                'dateCreated' => $this->getDateCreated(),
                'dateUpdated' => $this->getDateUpdated(),
                'url' => $this->getUrl(),
                'delivery' => $this->getDelivery(),
                'links' => $this->getLinks(),
                'contentSid' => $this->getContentSid(),
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'account_sid',
        'conversation_sid',
        'sid',
        'index',
        'author',
        'body',
        'media',
        'attributes',
        'participant_sid',
        'date_created',
        'date_updated',
        'url',
        'delivery',
        'links',
        'content_sid'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->accountSid)) {
            $json['account_sid']      = $this->accountSid['value'];
        }
        if (!empty($this->conversationSid)) {
            $json['conversation_sid'] = $this->conversationSid['value'];
        }
        if (!empty($this->sid)) {
            $json['sid']              = $this->sid['value'];
        }
        if (isset($this->index)) {
            $json['index']            = $this->index;
        }
        if (!empty($this->author)) {
            $json['author']           = $this->author['value'];
        }
        if (!empty($this->body)) {
            $json['body']             = $this->body['value'];
        }
        if (!empty($this->media)) {
            $json['media']            = $this->media['value'];
        }
        if (!empty($this->attributes)) {
            $json['attributes']       = $this->attributes['value'];
        }
        if (!empty($this->participantSid)) {
            $json['participant_sid']  = $this->participantSid['value'];
        }
        if (!empty($this->dateCreated)) {
            $json['date_created']     = DateTimeHelper::toRfc3339DateTime($this->dateCreated['value']);
        }
        if (!empty($this->dateUpdated)) {
            $json['date_updated']     = DateTimeHelper::toRfc3339DateTime($this->dateUpdated['value']);
        }
        if (!empty($this->url)) {
            $json['url']              = $this->url['value'];
        }
        if (!empty($this->delivery)) {
            $json['delivery']         = $this->delivery['value'];
        }
        if (!empty($this->links)) {
            $json['links']            = $this->links['value'];
        }
        if (!empty($this->contentSid)) {
            $json['content_sid']      = $this->contentSid['value'];
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
