<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models;

use stdClass;
use TwilioApIsLib\ApiHelper;
use TwilioApIsLib\Utils\DateTimeHelper;

class Entity implements \JsonSerializable
{
    /**
     * @var array
     */
    private $sid = [];

    /**
     * @var array
     */
    private $identity = [];

    /**
     * @var array
     */
    private $accountSid = [];

    /**
     * @var array
     */
    private $serviceSid = [];

    /**
     * @var array
     */
    private $dateCreated = [];

    /**
     * @var array
     */
    private $dateUpdated = [];

    /**
     * @var array
     */
    private $url = [];

    /**
     * @var array
     */
    private $links = [];

    /**
     * Returns Sid.
     * A 34 character string that uniquely identifies this Entity.
     */
    public function getSid(): ?string
    {
        if (count($this->sid) == 0) {
            return null;
        }
        return $this->sid['value'];
    }

    /**
     * Sets Sid.
     * A 34 character string that uniquely identifies this Entity.
     *
     * @maps sid
     */
    public function setSid(?string $sid): void
    {
        $this->sid['value'] = $sid;
    }

    /**
     * Unsets Sid.
     * A 34 character string that uniquely identifies this Entity.
     */
    public function unsetSid(): void
    {
        $this->sid = [];
    }

    /**
     * Returns Identity.
     * The unique external identifier for the Entity of the Service. This identifier should be immutable,
     * not PII, length between 8 and 64 characters, and generated by your external system, such as your
     * user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
     */
    public function getIdentity(): ?string
    {
        if (count($this->identity) == 0) {
            return null;
        }
        return $this->identity['value'];
    }

    /**
     * Sets Identity.
     * The unique external identifier for the Entity of the Service. This identifier should be immutable,
     * not PII, length between 8 and 64 characters, and generated by your external system, such as your
     * user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
     *
     * @maps identity
     */
    public function setIdentity(?string $identity): void
    {
        $this->identity['value'] = $identity;
    }

    /**
     * Unsets Identity.
     * The unique external identifier for the Entity of the Service. This identifier should be immutable,
     * not PII, length between 8 and 64 characters, and generated by your external system, such as your
     * user's UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric characters.
     */
    public function unsetIdentity(): void
    {
        $this->identity = [];
    }

    /**
     * Returns Account Sid.
     * The unique SID identifier of the Account.
     */
    public function getAccountSid(): ?string
    {
        if (count($this->accountSid) == 0) {
            return null;
        }
        return $this->accountSid['value'];
    }

    /**
     * Sets Account Sid.
     * The unique SID identifier of the Account.
     *
     * @maps account_sid
     */
    public function setAccountSid(?string $accountSid): void
    {
        $this->accountSid['value'] = $accountSid;
    }

    /**
     * Unsets Account Sid.
     * The unique SID identifier of the Account.
     */
    public function unsetAccountSid(): void
    {
        $this->accountSid = [];
    }

    /**
     * Returns Service Sid.
     * The unique SID identifier of the Service.
     */
    public function getServiceSid(): ?string
    {
        if (count($this->serviceSid) == 0) {
            return null;
        }
        return $this->serviceSid['value'];
    }

    /**
     * Sets Service Sid.
     * The unique SID identifier of the Service.
     *
     * @maps service_sid
     */
    public function setServiceSid(?string $serviceSid): void
    {
        $this->serviceSid['value'] = $serviceSid;
    }

    /**
     * Unsets Service Sid.
     * The unique SID identifier of the Service.
     */
    public function unsetServiceSid(): void
    {
        $this->serviceSid = [];
    }

    /**
     * Returns Date Created.
     * The date that this Entity was created, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
     * format.
     */
    public function getDateCreated(): ?\DateTime
    {
        if (count($this->dateCreated) == 0) {
            return null;
        }
        return $this->dateCreated['value'];
    }

    /**
     * Sets Date Created.
     * The date that this Entity was created, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
     * format.
     *
     * @maps date_created
     * @factory \TwilioApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateCreated(?\DateTime $dateCreated): void
    {
        $this->dateCreated['value'] = $dateCreated;
    }

    /**
     * Unsets Date Created.
     * The date that this Entity was created, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
     * format.
     */
    public function unsetDateCreated(): void
    {
        $this->dateCreated = [];
    }

    /**
     * Returns Date Updated.
     * The date that this Entity was updated, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
     * format.
     */
    public function getDateUpdated(): ?\DateTime
    {
        if (count($this->dateUpdated) == 0) {
            return null;
        }
        return $this->dateUpdated['value'];
    }

    /**
     * Sets Date Updated.
     * The date that this Entity was updated, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
     * format.
     *
     * @maps date_updated
     * @factory \TwilioApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateUpdated(?\DateTime $dateUpdated): void
    {
        $this->dateUpdated['value'] = $dateUpdated;
    }

    /**
     * Unsets Date Updated.
     * The date that this Entity was updated, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
     * format.
     */
    public function unsetDateUpdated(): void
    {
        $this->dateUpdated = [];
    }

    /**
     * Returns Url.
     * The URL of this resource.
     */
    public function getUrl(): ?string
    {
        if (count($this->url) == 0) {
            return null;
        }
        return $this->url['value'];
    }

    /**
     * Sets Url.
     * The URL of this resource.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url['value'] = $url;
    }

    /**
     * Unsets Url.
     * The URL of this resource.
     */
    public function unsetUrl(): void
    {
        $this->url = [];
    }

    /**
     * Returns Links.
     * Contains a dictionary of URL links to nested resources of this Entity.
     */
    public function getLinks(): ?array
    {
        if (count($this->links) == 0) {
            return null;
        }
        return $this->links['value'];
    }

    /**
     * Sets Links.
     * Contains a dictionary of URL links to nested resources of this Entity.
     *
     * @maps links
     */
    public function setLinks(?array $links): void
    {
        $this->links['value'] = $links;
    }

    /**
     * Unsets Links.
     * Contains a dictionary of URL links to nested resources of this Entity.
     */
    public function unsetLinks(): void
    {
        $this->links = [];
    }

    /**
     * Converts the Entity object to a human-readable string representation.
     *
     * @return string The string representation of the Entity object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Entity',
            [
                'sid' => $this->getSid(),
                'identity' => $this->getIdentity(),
                'accountSid' => $this->getAccountSid(),
                'serviceSid' => $this->getServiceSid(),
                'dateCreated' => $this->getDateCreated(),
                'dateUpdated' => $this->getDateUpdated(),
                'url' => $this->getUrl(),
                'links' => $this->getLinks(),
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'sid',
        'identity',
        'account_sid',
        'service_sid',
        'date_created',
        'date_updated',
        'url',
        'links'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->sid)) {
            $json['sid']          = $this->sid['value'];
        }
        if (!empty($this->identity)) {
            $json['identity']     = $this->identity['value'];
        }
        if (!empty($this->accountSid)) {
            $json['account_sid']  = $this->accountSid['value'];
        }
        if (!empty($this->serviceSid)) {
            $json['service_sid']  = $this->serviceSid['value'];
        }
        if (!empty($this->dateCreated)) {
            $json['date_created'] = DateTimeHelper::toRfc3339DateTime($this->dateCreated['value']);
        }
        if (!empty($this->dateUpdated)) {
            $json['date_updated'] = DateTimeHelper::toRfc3339DateTime($this->dateUpdated['value']);
        }
        if (!empty($this->url)) {
            $json['url']          = $this->url['value'];
        }
        if (!empty($this->links)) {
            $json['links']        = $this->links['value'];
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
