<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models;

use stdClass;
use TwilioApIsLib\ApiHelper;
use TwilioApIsLib\Utils\DateTimeHelper;

class MessagingConfiguration implements \JsonSerializable
{
    /**
     * @var array
     */
    private $accountSid = [];

    /**
     * @var array
     */
    private $serviceSid = [];

    /**
     * @var array
     */
    private $country = [];

    /**
     * @var array
     */
    private $messagingServiceSid = [];

    /**
     * @var array
     */
    private $dateCreated = [];

    /**
     * @var array
     */
    private $dateUpdated = [];

    /**
     * @var array
     */
    private $url = [];

    /**
     * Returns Account Sid.
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Service
     * resource.
     */
    public function getAccountSid(): ?string
    {
        if (count($this->accountSid) == 0) {
            return null;
        }
        return $this->accountSid['value'];
    }

    /**
     * Sets Account Sid.
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Service
     * resource.
     *
     * @maps account_sid
     */
    public function setAccountSid(?string $accountSid): void
    {
        $this->accountSid['value'] = $accountSid;
    }

    /**
     * Unsets Account Sid.
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Service
     * resource.
     */
    public function unsetAccountSid(): void
    {
        $this->accountSid = [];
    }

    /**
     * Returns Service Sid.
     * The SID of the [Service](https://www.twilio.com/docs/verify/api/service) that the resource is
     * associated with.
     */
    public function getServiceSid(): ?string
    {
        if (count($this->serviceSid) == 0) {
            return null;
        }
        return $this->serviceSid['value'];
    }

    /**
     * Sets Service Sid.
     * The SID of the [Service](https://www.twilio.com/docs/verify/api/service) that the resource is
     * associated with.
     *
     * @maps service_sid
     */
    public function setServiceSid(?string $serviceSid): void
    {
        $this->serviceSid['value'] = $serviceSid;
    }

    /**
     * Unsets Service Sid.
     * The SID of the [Service](https://www.twilio.com/docs/verify/api/service) that the resource is
     * associated with.
     */
    public function unsetServiceSid(): void
    {
        $this->serviceSid = [];
    }

    /**
     * Returns Country.
     * The [ISO-3166-1](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code of the country this
     * configuration will be applied to. If this is a global configuration, Country will take the value
     * `all`.
     */
    public function getCountry(): ?string
    {
        if (count($this->country) == 0) {
            return null;
        }
        return $this->country['value'];
    }

    /**
     * Sets Country.
     * The [ISO-3166-1](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code of the country this
     * configuration will be applied to. If this is a global configuration, Country will take the value
     * `all`.
     *
     * @maps country
     */
    public function setCountry(?string $country): void
    {
        $this->country['value'] = $country;
    }

    /**
     * Unsets Country.
     * The [ISO-3166-1](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code of the country this
     * configuration will be applied to. If this is a global configuration, Country will take the value
     * `all`.
     */
    public function unsetCountry(): void
    {
        $this->country = [];
    }

    /**
     * Returns Messaging Service Sid.
     * The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource) to be
     * used to send SMS to the country of this configuration.
     */
    public function getMessagingServiceSid(): ?string
    {
        if (count($this->messagingServiceSid) == 0) {
            return null;
        }
        return $this->messagingServiceSid['value'];
    }

    /**
     * Sets Messaging Service Sid.
     * The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource) to be
     * used to send SMS to the country of this configuration.
     *
     * @maps messaging_service_sid
     */
    public function setMessagingServiceSid(?string $messagingServiceSid): void
    {
        $this->messagingServiceSid['value'] = $messagingServiceSid;
    }

    /**
     * Unsets Messaging Service Sid.
     * The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource) to be
     * used to send SMS to the country of this configuration.
     */
    public function unsetMessagingServiceSid(): void
    {
        $this->messagingServiceSid = [];
    }

    /**
     * Returns Date Created.
     * The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.
     * org/rfc/rfc2822.txt) format.
     */
    public function getDateCreated(): ?\DateTime
    {
        if (count($this->dateCreated) == 0) {
            return null;
        }
        return $this->dateCreated['value'];
    }

    /**
     * Sets Date Created.
     * The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.
     * org/rfc/rfc2822.txt) format.
     *
     * @maps date_created
     * @factory \TwilioApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateCreated(?\DateTime $dateCreated): void
    {
        $this->dateCreated['value'] = $dateCreated;
    }

    /**
     * Unsets Date Created.
     * The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.
     * org/rfc/rfc2822.txt) format.
     */
    public function unsetDateCreated(): void
    {
        $this->dateCreated = [];
    }

    /**
     * Returns Date Updated.
     * The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.
     * org/rfc/rfc2822.txt) format.
     */
    public function getDateUpdated(): ?\DateTime
    {
        if (count($this->dateUpdated) == 0) {
            return null;
        }
        return $this->dateUpdated['value'];
    }

    /**
     * Sets Date Updated.
     * The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.
     * org/rfc/rfc2822.txt) format.
     *
     * @maps date_updated
     * @factory \TwilioApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateUpdated(?\DateTime $dateUpdated): void
    {
        $this->dateUpdated['value'] = $dateUpdated;
    }

    /**
     * Unsets Date Updated.
     * The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.
     * org/rfc/rfc2822.txt) format.
     */
    public function unsetDateUpdated(): void
    {
        $this->dateUpdated = [];
    }

    /**
     * Returns Url.
     * The URL of this resource.
     */
    public function getUrl(): ?string
    {
        if (count($this->url) == 0) {
            return null;
        }
        return $this->url['value'];
    }

    /**
     * Sets Url.
     * The URL of this resource.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url['value'] = $url;
    }

    /**
     * Unsets Url.
     * The URL of this resource.
     */
    public function unsetUrl(): void
    {
        $this->url = [];
    }

    /**
     * Converts the MessagingConfiguration object to a human-readable string representation.
     *
     * @return string The string representation of the MessagingConfiguration object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'MessagingConfiguration',
            [
                'accountSid' => $this->getAccountSid(),
                'serviceSid' => $this->getServiceSid(),
                'country' => $this->getCountry(),
                'messagingServiceSid' => $this->getMessagingServiceSid(),
                'dateCreated' => $this->getDateCreated(),
                'dateUpdated' => $this->getDateUpdated(),
                'url' => $this->getUrl(),
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'account_sid',
        'service_sid',
        'country',
        'messaging_service_sid',
        'date_created',
        'date_updated',
        'url'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->accountSid)) {
            $json['account_sid']           = $this->accountSid['value'];
        }
        if (!empty($this->serviceSid)) {
            $json['service_sid']           = $this->serviceSid['value'];
        }
        if (!empty($this->country)) {
            $json['country']               = $this->country['value'];
        }
        if (!empty($this->messagingServiceSid)) {
            $json['messaging_service_sid'] = $this->messagingServiceSid['value'];
        }
        if (!empty($this->dateCreated)) {
            $json['date_created']          = DateTimeHelper::toRfc3339DateTime($this->dateCreated['value']);
        }
        if (!empty($this->dateUpdated)) {
            $json['date_updated']          = DateTimeHelper::toRfc3339DateTime($this->dateUpdated['value']);
        }
        if (!empty($this->url)) {
            $json['url']                   = $this->url['value'];
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
