<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * The priority of the notification. Can be: `low` or `high` and the default is `high`. A value of
 * `low` optimizes the client app's battery consumption; however, notifications may be delivered with
 * unspecified delay. For FCM and GCM, `low` priority is the same as `Normal` priority. For APNS `low`
 * priority is the same as `5`. A value of `high` sends the notification immediately, and can wake up a
 * sleeping device. For FCM and GCM, `high` is the same as `High` priority. For APNS, `high` is a
 * priority `10`. SMS does not support this property.
 */
class NotifPriority
{
    public const HIGH = 'high';

    public const LOW = 'low';

    private const _ALL_VALUES = [self::HIGH, self::LOW];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for NotifPriority.");
    }
}
