<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models;

use stdClass;
use TwilioApIsLib\ApiHelper;
use TwilioApIsLib\Utils\DateTimeHelper;

class Notification implements \JsonSerializable
{
    /**
     * @var array
     */
    private $sid = [];

    /**
     * @var array
     */
    private $accountSid = [];

    /**
     * @var array
     */
    private $serviceSid = [];

    /**
     * @var array
     */
    private $dateCreated = [];

    /**
     * @var array
     */
    private $identities = [];

    /**
     * @var array
     */
    private $tags = [];

    /**
     * @var array
     */
    private $segments = [];

    /**
     * @var string|null
     */
    private $priority;

    /**
     * @var int|null
     */
    private $ttl = 0;

    /**
     * @var array
     */
    private $title = [];

    /**
     * @var array
     */
    private $body = [];

    /**
     * @var array
     */
    private $sound = [];

    /**
     * @var array
     */
    private $action = [];

    /**
     * @var array
     */
    private $data = [];

    /**
     * @var array
     */
    private $apn = [];

    /**
     * @var array
     */
    private $gcm = [];

    /**
     * @var array
     */
    private $fcm = [];

    /**
     * @var array
     */
    private $sms = [];

    /**
     * @var array
     */
    private $facebookMessenger = [];

    /**
     * @var array
     */
    private $alexa = [];

    /**
     * Returns Sid.
     * The unique string that we created to identify the Notification resource.
     */
    public function getSid(): ?string
    {
        if (count($this->sid) == 0) {
            return null;
        }
        return $this->sid['value'];
    }

    /**
     * Sets Sid.
     * The unique string that we created to identify the Notification resource.
     *
     * @maps sid
     */
    public function setSid(?string $sid): void
    {
        $this->sid['value'] = $sid;
    }

    /**
     * Unsets Sid.
     * The unique string that we created to identify the Notification resource.
     */
    public function unsetSid(): void
    {
        $this->sid = [];
    }

    /**
     * Returns Account Sid.
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Notification
     * resource.
     */
    public function getAccountSid(): ?string
    {
        if (count($this->accountSid) == 0) {
            return null;
        }
        return $this->accountSid['value'];
    }

    /**
     * Sets Account Sid.
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Notification
     * resource.
     *
     * @maps account_sid
     */
    public function setAccountSid(?string $accountSid): void
    {
        $this->accountSid['value'] = $accountSid;
    }

    /**
     * Unsets Account Sid.
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Notification
     * resource.
     */
    public function unsetAccountSid(): void
    {
        $this->accountSid = [];
    }

    /**
     * Returns Service Sid.
     * The SID of the [Service](https://www.twilio.com/docs/notify/api/service-resource) the resource is
     * associated with.
     */
    public function getServiceSid(): ?string
    {
        if (count($this->serviceSid) == 0) {
            return null;
        }
        return $this->serviceSid['value'];
    }

    /**
     * Sets Service Sid.
     * The SID of the [Service](https://www.twilio.com/docs/notify/api/service-resource) the resource is
     * associated with.
     *
     * @maps service_sid
     */
    public function setServiceSid(?string $serviceSid): void
    {
        $this->serviceSid['value'] = $serviceSid;
    }

    /**
     * Unsets Service Sid.
     * The SID of the [Service](https://www.twilio.com/docs/notify/api/service-resource) the resource is
     * associated with.
     */
    public function unsetServiceSid(): void
    {
        $this->serviceSid = [];
    }

    /**
     * Returns Date Created.
     * The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.
     * org/rfc/rfc2822.txt) format.
     */
    public function getDateCreated(): ?\DateTime
    {
        if (count($this->dateCreated) == 0) {
            return null;
        }
        return $this->dateCreated['value'];
    }

    /**
     * Sets Date Created.
     * The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.
     * org/rfc/rfc2822.txt) format.
     *
     * @maps date_created
     * @factory \TwilioApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateCreated(?\DateTime $dateCreated): void
    {
        $this->dateCreated['value'] = $dateCreated;
    }

    /**
     * Unsets Date Created.
     * The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.
     * org/rfc/rfc2822.txt) format.
     */
    public function unsetDateCreated(): void
    {
        $this->dateCreated = [];
    }

    /**
     * Returns Identities.
     * The list of `identity` values of the Users to notify. We will attempt to deliver notifications only
     * to Bindings with an identity in this list.
     *
     * @return string[]|null
     */
    public function getIdentities(): ?array
    {
        if (count($this->identities) == 0) {
            return null;
        }
        return $this->identities['value'];
    }

    /**
     * Sets Identities.
     * The list of `identity` values of the Users to notify. We will attempt to deliver notifications only
     * to Bindings with an identity in this list.
     *
     * @maps identities
     *
     * @param string[]|null $identities
     */
    public function setIdentities(?array $identities): void
    {
        $this->identities['value'] = $identities;
    }

    /**
     * Unsets Identities.
     * The list of `identity` values of the Users to notify. We will attempt to deliver notifications only
     * to Bindings with an identity in this list.
     */
    public function unsetIdentities(): void
    {
        $this->identities = [];
    }

    /**
     * Returns Tags.
     * The tags that select the Bindings to notify. Notifications will be attempted only to Bindings that
     * have all of the tags listed in this property.
     *
     * @return string[]|null
     */
    public function getTags(): ?array
    {
        if (count($this->tags) == 0) {
            return null;
        }
        return $this->tags['value'];
    }

    /**
     * Sets Tags.
     * The tags that select the Bindings to notify. Notifications will be attempted only to Bindings that
     * have all of the tags listed in this property.
     *
     * @maps tags
     *
     * @param string[]|null $tags
     */
    public function setTags(?array $tags): void
    {
        $this->tags['value'] = $tags;
    }

    /**
     * Unsets Tags.
     * The tags that select the Bindings to notify. Notifications will be attempted only to Bindings that
     * have all of the tags listed in this property.
     */
    public function unsetTags(): void
    {
        $this->tags = [];
    }

    /**
     * Returns Segments.
     * The list of Segments to notify. The [Segment](https://www.twilio.com/docs/notify/api/segment-
     * resource) resource is deprecated. Use the `tags` property, instead.
     *
     * @return string[]|null
     */
    public function getSegments(): ?array
    {
        if (count($this->segments) == 0) {
            return null;
        }
        return $this->segments['value'];
    }

    /**
     * Sets Segments.
     * The list of Segments to notify. The [Segment](https://www.twilio.com/docs/notify/api/segment-
     * resource) resource is deprecated. Use the `tags` property, instead.
     *
     * @maps segments
     *
     * @param string[]|null $segments
     */
    public function setSegments(?array $segments): void
    {
        $this->segments['value'] = $segments;
    }

    /**
     * Unsets Segments.
     * The list of Segments to notify. The [Segment](https://www.twilio.com/docs/notify/api/segment-
     * resource) resource is deprecated. Use the `tags` property, instead.
     */
    public function unsetSegments(): void
    {
        $this->segments = [];
    }

    /**
     * Returns Priority.
     * The priority of the notification. Can be: `low` or `high` and the default is `high`. A value of
     * `low` optimizes the client app's battery consumption; however, notifications may be delivered with
     * unspecified delay. For FCM and GCM, `low` priority is the same as `Normal` priority. For APNS `low`
     * priority is the same as `5`. A value of `high` sends the notification immediately, and can wake up a
     * sleeping device. For FCM and GCM, `high` is the same as `High` priority. For APNS, `high` is a
     * priority `10`. SMS does not support this property.
     */
    public function getPriority(): ?string
    {
        return $this->priority;
    }

    /**
     * Sets Priority.
     * The priority of the notification. Can be: `low` or `high` and the default is `high`. A value of
     * `low` optimizes the client app's battery consumption; however, notifications may be delivered with
     * unspecified delay. For FCM and GCM, `low` priority is the same as `Normal` priority. For APNS `low`
     * priority is the same as `5`. A value of `high` sends the notification immediately, and can wake up a
     * sleeping device. For FCM and GCM, `high` is the same as `High` priority. For APNS, `high` is a
     * priority `10`. SMS does not support this property.
     *
     * @maps priority
     * @factory \TwilioApIsLib\Models\NotifPriority::checkValue
     */
    public function setPriority(?string $priority): void
    {
        $this->priority = $priority;
    }

    /**
     * Returns Ttl.
     * How long, in seconds, the notification is valid. Can be an integer between 0 and 2,419,200, which is
     * 4 weeks, the default and the maximum supported time to live (TTL). Delivery should be attempted if
     * the device is offline until the TTL elapses. Zero means that the notification delivery is attempted
     * immediately, only once, and is not stored for future delivery. SMS does not support this property.
     */
    public function getTtl(): ?int
    {
        return $this->ttl;
    }

    /**
     * Sets Ttl.
     * How long, in seconds, the notification is valid. Can be an integer between 0 and 2,419,200, which is
     * 4 weeks, the default and the maximum supported time to live (TTL). Delivery should be attempted if
     * the device is offline until the TTL elapses. Zero means that the notification delivery is attempted
     * immediately, only once, and is not stored for future delivery. SMS does not support this property.
     *
     * @maps ttl
     */
    public function setTtl(?int $ttl): void
    {
        $this->ttl = $ttl;
    }

    /**
     * Returns Title.
     * The notification title. For FCM and GCM, this translates to the `data.twi_title` value. For APNS,
     * this translates to the `aps.alert.title` value. SMS does not support this property. This field is
     * not visible on iOS phones and tablets but appears on Apple Watch and Android devices.
     */
    public function getTitle(): ?string
    {
        if (count($this->title) == 0) {
            return null;
        }
        return $this->title['value'];
    }

    /**
     * Sets Title.
     * The notification title. For FCM and GCM, this translates to the `data.twi_title` value. For APNS,
     * this translates to the `aps.alert.title` value. SMS does not support this property. This field is
     * not visible on iOS phones and tablets but appears on Apple Watch and Android devices.
     *
     * @maps title
     */
    public function setTitle(?string $title): void
    {
        $this->title['value'] = $title;
    }

    /**
     * Unsets Title.
     * The notification title. For FCM and GCM, this translates to the `data.twi_title` value. For APNS,
     * this translates to the `aps.alert.title` value. SMS does not support this property. This field is
     * not visible on iOS phones and tablets but appears on Apple Watch and Android devices.
     */
    public function unsetTitle(): void
    {
        $this->title = [];
    }

    /**
     * Returns Body.
     * The notification text. For FCM and GCM, translates to `data.twi_body`. For APNS, translates to `aps.
     * alert.body`. For SMS, translates to `body`. SMS requires either this `body` value, or `media_urls`
     * attribute defined in the `sms` parameter of the notification.
     */
    public function getBody(): ?string
    {
        if (count($this->body) == 0) {
            return null;
        }
        return $this->body['value'];
    }

    /**
     * Sets Body.
     * The notification text. For FCM and GCM, translates to `data.twi_body`. For APNS, translates to `aps.
     * alert.body`. For SMS, translates to `body`. SMS requires either this `body` value, or `media_urls`
     * attribute defined in the `sms` parameter of the notification.
     *
     * @maps body
     */
    public function setBody(?string $body): void
    {
        $this->body['value'] = $body;
    }

    /**
     * Unsets Body.
     * The notification text. For FCM and GCM, translates to `data.twi_body`. For APNS, translates to `aps.
     * alert.body`. For SMS, translates to `body`. SMS requires either this `body` value, or `media_urls`
     * attribute defined in the `sms` parameter of the notification.
     */
    public function unsetBody(): void
    {
        $this->body = [];
    }

    /**
     * Returns Sound.
     * The name of the sound to be played for the notification. For FCM and GCM, this Translates to `data.
     * twi_sound`.  For APNS, this translates to `aps.sound`.  SMS does not support this property.
     */
    public function getSound(): ?string
    {
        if (count($this->sound) == 0) {
            return null;
        }
        return $this->sound['value'];
    }

    /**
     * Sets Sound.
     * The name of the sound to be played for the notification. For FCM and GCM, this Translates to `data.
     * twi_sound`.  For APNS, this translates to `aps.sound`.  SMS does not support this property.
     *
     * @maps sound
     */
    public function setSound(?string $sound): void
    {
        $this->sound['value'] = $sound;
    }

    /**
     * Unsets Sound.
     * The name of the sound to be played for the notification. For FCM and GCM, this Translates to `data.
     * twi_sound`.  For APNS, this translates to `aps.sound`.  SMS does not support this property.
     */
    public function unsetSound(): void
    {
        $this->sound = [];
    }

    /**
     * Returns Action.
     * The actions to display for the notification. For APNS, translates to the `aps.category` value. For
     * GCM, translates to the `data.twi_action` value. For SMS, this parameter is not supported and is
     * omitted from deliveries to those channels.
     */
    public function getAction(): ?string
    {
        if (count($this->action) == 0) {
            return null;
        }
        return $this->action['value'];
    }

    /**
     * Sets Action.
     * The actions to display for the notification. For APNS, translates to the `aps.category` value. For
     * GCM, translates to the `data.twi_action` value. For SMS, this parameter is not supported and is
     * omitted from deliveries to those channels.
     *
     * @maps action
     */
    public function setAction(?string $action): void
    {
        $this->action['value'] = $action;
    }

    /**
     * Unsets Action.
     * The actions to display for the notification. For APNS, translates to the `aps.category` value. For
     * GCM, translates to the `data.twi_action` value. For SMS, this parameter is not supported and is
     * omitted from deliveries to those channels.
     */
    public function unsetAction(): void
    {
        $this->action = [];
    }

    /**
     * Returns Data.
     * The custom key-value pairs of the notification's payload. For FCM and GCM, this value translates to
     * `data` in the FCM and GCM payloads. FCM and GCM [reserve certain keys](https://firebase.google.
     * com/docs/cloud-messaging/http-server-ref) that cannot be used in those channels. For APNS,
     * attributes of `data` are inserted into the APNS payload as custom properties outside of the `aps`
     * dictionary. In all channels, we reserve keys that start with `twi_` for future use. Custom keys that
     * start with `twi_` are not allowed and are rejected as 400 Bad request with no delivery attempted.
     * For SMS, this parameter is not supported and is omitted from deliveries to those channels.
     */
    public function getData(): ?array
    {
        if (count($this->data) == 0) {
            return null;
        }
        return $this->data['value'];
    }

    /**
     * Sets Data.
     * The custom key-value pairs of the notification's payload. For FCM and GCM, this value translates to
     * `data` in the FCM and GCM payloads. FCM and GCM [reserve certain keys](https://firebase.google.
     * com/docs/cloud-messaging/http-server-ref) that cannot be used in those channels. For APNS,
     * attributes of `data` are inserted into the APNS payload as custom properties outside of the `aps`
     * dictionary. In all channels, we reserve keys that start with `twi_` for future use. Custom keys that
     * start with `twi_` are not allowed and are rejected as 400 Bad request with no delivery attempted.
     * For SMS, this parameter is not supported and is omitted from deliveries to those channels.
     *
     * @maps data
     */
    public function setData(?array $data): void
    {
        $this->data['value'] = $data;
    }

    /**
     * Unsets Data.
     * The custom key-value pairs of the notification's payload. For FCM and GCM, this value translates to
     * `data` in the FCM and GCM payloads. FCM and GCM [reserve certain keys](https://firebase.google.
     * com/docs/cloud-messaging/http-server-ref) that cannot be used in those channels. For APNS,
     * attributes of `data` are inserted into the APNS payload as custom properties outside of the `aps`
     * dictionary. In all channels, we reserve keys that start with `twi_` for future use. Custom keys that
     * start with `twi_` are not allowed and are rejected as 400 Bad request with no delivery attempted.
     * For SMS, this parameter is not supported and is omitted from deliveries to those channels.
     */
    public function unsetData(): void
    {
        $this->data = [];
    }

    /**
     * Returns Apn.
     * The APNS-specific payload that overrides corresponding attributes in the generic payload for APNS
     * Bindings. This property maps to the APNS `Payload` item, therefore the `aps` key must be used to
     * change standard attributes. Adds custom key-value pairs to the root of the dictionary. See the [APNS
     * documentation](https://developer.apple.
     * com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Communicatingw
     * ithAPNs.html) for more details. We reserve keys that start with `twi_` for future use. Custom keys
     * that start with `twi_` are not allowed.
     */
    public function getApn(): ?array
    {
        if (count($this->apn) == 0) {
            return null;
        }
        return $this->apn['value'];
    }

    /**
     * Sets Apn.
     * The APNS-specific payload that overrides corresponding attributes in the generic payload for APNS
     * Bindings. This property maps to the APNS `Payload` item, therefore the `aps` key must be used to
     * change standard attributes. Adds custom key-value pairs to the root of the dictionary. See the [APNS
     * documentation](https://developer.apple.
     * com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Communicatingw
     * ithAPNs.html) for more details. We reserve keys that start with `twi_` for future use. Custom keys
     * that start with `twi_` are not allowed.
     *
     * @maps apn
     */
    public function setApn(?array $apn): void
    {
        $this->apn['value'] = $apn;
    }

    /**
     * Unsets Apn.
     * The APNS-specific payload that overrides corresponding attributes in the generic payload for APNS
     * Bindings. This property maps to the APNS `Payload` item, therefore the `aps` key must be used to
     * change standard attributes. Adds custom key-value pairs to the root of the dictionary. See the [APNS
     * documentation](https://developer.apple.
     * com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Communicatingw
     * ithAPNs.html) for more details. We reserve keys that start with `twi_` for future use. Custom keys
     * that start with `twi_` are not allowed.
     */
    public function unsetApn(): void
    {
        $this->apn = [];
    }

    /**
     * Returns Gcm.
     * The GCM-specific payload that overrides corresponding attributes in the generic payload for GCM
     * Bindings.  This property maps to the root JSON dictionary. Target parameters `to`,
     * `registration_ids`, and `notification_key` are not allowed. We reserve keys that start with `twi_`
     * for future use. Custom keys that start with `twi_` are not allowed.
     */
    public function getGcm(): ?array
    {
        if (count($this->gcm) == 0) {
            return null;
        }
        return $this->gcm['value'];
    }

    /**
     * Sets Gcm.
     * The GCM-specific payload that overrides corresponding attributes in the generic payload for GCM
     * Bindings.  This property maps to the root JSON dictionary. Target parameters `to`,
     * `registration_ids`, and `notification_key` are not allowed. We reserve keys that start with `twi_`
     * for future use. Custom keys that start with `twi_` are not allowed.
     *
     * @maps gcm
     */
    public function setGcm(?array $gcm): void
    {
        $this->gcm['value'] = $gcm;
    }

    /**
     * Unsets Gcm.
     * The GCM-specific payload that overrides corresponding attributes in the generic payload for GCM
     * Bindings.  This property maps to the root JSON dictionary. Target parameters `to`,
     * `registration_ids`, and `notification_key` are not allowed. We reserve keys that start with `twi_`
     * for future use. Custom keys that start with `twi_` are not allowed.
     */
    public function unsetGcm(): void
    {
        $this->gcm = [];
    }

    /**
     * Returns Fcm.
     * The FCM-specific payload that overrides corresponding attributes in the generic payload for FCM
     * Bindings. This property maps to the root JSON dictionary. See the [FCM documentation](https:
     * //firebase.google.com/docs/cloud-messaging/http-server-ref#downstream) for more details. Target
     * parameters `to`, `registration_ids`, `condition`, and `notification_key` are not allowed in this
     * parameter. We reserve keys that start with `twi_` for future use. Custom keys that start with `twi_`
     * are not allowed. FCM also [reserves certain keys](https://firebase.google.com/docs/cloud-
     * messaging/http-server-ref), which cannot be used in that channel.
     */
    public function getFcm(): ?array
    {
        if (count($this->fcm) == 0) {
            return null;
        }
        return $this->fcm['value'];
    }

    /**
     * Sets Fcm.
     * The FCM-specific payload that overrides corresponding attributes in the generic payload for FCM
     * Bindings. This property maps to the root JSON dictionary. See the [FCM documentation](https:
     * //firebase.google.com/docs/cloud-messaging/http-server-ref#downstream) for more details. Target
     * parameters `to`, `registration_ids`, `condition`, and `notification_key` are not allowed in this
     * parameter. We reserve keys that start with `twi_` for future use. Custom keys that start with `twi_`
     * are not allowed. FCM also [reserves certain keys](https://firebase.google.com/docs/cloud-
     * messaging/http-server-ref), which cannot be used in that channel.
     *
     * @maps fcm
     */
    public function setFcm(?array $fcm): void
    {
        $this->fcm['value'] = $fcm;
    }

    /**
     * Unsets Fcm.
     * The FCM-specific payload that overrides corresponding attributes in the generic payload for FCM
     * Bindings. This property maps to the root JSON dictionary. See the [FCM documentation](https:
     * //firebase.google.com/docs/cloud-messaging/http-server-ref#downstream) for more details. Target
     * parameters `to`, `registration_ids`, `condition`, and `notification_key` are not allowed in this
     * parameter. We reserve keys that start with `twi_` for future use. Custom keys that start with `twi_`
     * are not allowed. FCM also [reserves certain keys](https://firebase.google.com/docs/cloud-
     * messaging/http-server-ref), which cannot be used in that channel.
     */
    public function unsetFcm(): void
    {
        $this->fcm = [];
    }

    /**
     * Returns Sms.
     * The SMS-specific payload that overrides corresponding attributes in the generic payload for SMS
     * Bindings.  Each attribute in this value maps to the corresponding `form` parameter of the Twilio
     * [Message](https://www.twilio.com/docs/sms/api/message-resource) resource.  These parameters of the
     * Message resource are supported in snake case format: `body`, `media_urls`, `status_callback`, and
     * `max_price`.  The `status_callback` parameter overrides the corresponding parameter in the messaging
     * service, if configured. The `media_urls` property expects a JSON array.
     */
    public function getSms(): ?array
    {
        if (count($this->sms) == 0) {
            return null;
        }
        return $this->sms['value'];
    }

    /**
     * Sets Sms.
     * The SMS-specific payload that overrides corresponding attributes in the generic payload for SMS
     * Bindings.  Each attribute in this value maps to the corresponding `form` parameter of the Twilio
     * [Message](https://www.twilio.com/docs/sms/api/message-resource) resource.  These parameters of the
     * Message resource are supported in snake case format: `body`, `media_urls`, `status_callback`, and
     * `max_price`.  The `status_callback` parameter overrides the corresponding parameter in the messaging
     * service, if configured. The `media_urls` property expects a JSON array.
     *
     * @maps sms
     */
    public function setSms(?array $sms): void
    {
        $this->sms['value'] = $sms;
    }

    /**
     * Unsets Sms.
     * The SMS-specific payload that overrides corresponding attributes in the generic payload for SMS
     * Bindings.  Each attribute in this value maps to the corresponding `form` parameter of the Twilio
     * [Message](https://www.twilio.com/docs/sms/api/message-resource) resource.  These parameters of the
     * Message resource are supported in snake case format: `body`, `media_urls`, `status_callback`, and
     * `max_price`.  The `status_callback` parameter overrides the corresponding parameter in the messaging
     * service, if configured. The `media_urls` property expects a JSON array.
     */
    public function unsetSms(): void
    {
        $this->sms = [];
    }

    /**
     * Returns Facebook Messenger.
     * Deprecated.
     */
    public function getFacebookMessenger(): ?array
    {
        if (count($this->facebookMessenger) == 0) {
            return null;
        }
        return $this->facebookMessenger['value'];
    }

    /**
     * Sets Facebook Messenger.
     * Deprecated.
     *
     * @maps facebook_messenger
     */
    public function setFacebookMessenger(?array $facebookMessenger): void
    {
        $this->facebookMessenger['value'] = $facebookMessenger;
    }

    /**
     * Unsets Facebook Messenger.
     * Deprecated.
     */
    public function unsetFacebookMessenger(): void
    {
        $this->facebookMessenger = [];
    }

    /**
     * Returns Alexa.
     * Deprecated.
     */
    public function getAlexa(): ?array
    {
        if (count($this->alexa) == 0) {
            return null;
        }
        return $this->alexa['value'];
    }

    /**
     * Sets Alexa.
     * Deprecated.
     *
     * @maps alexa
     */
    public function setAlexa(?array $alexa): void
    {
        $this->alexa['value'] = $alexa;
    }

    /**
     * Unsets Alexa.
     * Deprecated.
     */
    public function unsetAlexa(): void
    {
        $this->alexa = [];
    }

    /**
     * Converts the Notification object to a human-readable string representation.
     *
     * @return string The string representation of the Notification object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Notification',
            [
                'sid' => $this->getSid(),
                'accountSid' => $this->getAccountSid(),
                'serviceSid' => $this->getServiceSid(),
                'dateCreated' => $this->getDateCreated(),
                'identities' => $this->getIdentities(),
                'tags' => $this->getTags(),
                'segments' => $this->getSegments(),
                'priority' => $this->priority,
                'ttl' => $this->ttl,
                'title' => $this->getTitle(),
                'body' => $this->getBody(),
                'sound' => $this->getSound(),
                'action' => $this->getAction(),
                'data' => $this->getData(),
                'apn' => $this->getApn(),
                'gcm' => $this->getGcm(),
                'fcm' => $this->getFcm(),
                'sms' => $this->getSms(),
                'facebookMessenger' => $this->getFacebookMessenger(),
                'alexa' => $this->getAlexa(),
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'sid',
        'account_sid',
        'service_sid',
        'date_created',
        'identities',
        'tags',
        'segments',
        'priority',
        'ttl',
        'title',
        'body',
        'sound',
        'action',
        'data',
        'apn',
        'gcm',
        'fcm',
        'sms',
        'facebook_messenger',
        'alexa'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->sid)) {
            $json['sid']                = $this->sid['value'];
        }
        if (!empty($this->accountSid)) {
            $json['account_sid']        = $this->accountSid['value'];
        }
        if (!empty($this->serviceSid)) {
            $json['service_sid']        = $this->serviceSid['value'];
        }
        if (!empty($this->dateCreated)) {
            $json['date_created']       = DateTimeHelper::toRfc3339DateTime($this->dateCreated['value']);
        }
        if (!empty($this->identities)) {
            $json['identities']         = $this->identities['value'];
        }
        if (!empty($this->tags)) {
            $json['tags']               = $this->tags['value'];
        }
        if (!empty($this->segments)) {
            $json['segments']           = $this->segments['value'];
        }
        if (isset($this->priority)) {
            $json['priority']           = NotifPriority::checkValue($this->priority);
        }
        if (isset($this->ttl)) {
            $json['ttl']                = $this->ttl;
        }
        if (!empty($this->title)) {
            $json['title']              = $this->title['value'];
        }
        if (!empty($this->body)) {
            $json['body']               = $this->body['value'];
        }
        if (!empty($this->sound)) {
            $json['sound']              = $this->sound['value'];
        }
        if (!empty($this->action)) {
            $json['action']             = $this->action['value'];
        }
        if (!empty($this->data)) {
            $json['data']               = $this->data['value'];
        }
        if (!empty($this->apn)) {
            $json['apn']                = $this->apn['value'];
        }
        if (!empty($this->gcm)) {
            $json['gcm']                = $this->gcm['value'];
        }
        if (!empty($this->fcm)) {
            $json['fcm']                = $this->fcm['value'];
        }
        if (!empty($this->sms)) {
            $json['sms']                = $this->sms['value'];
        }
        if (!empty($this->facebookMessenger)) {
            $json['facebook_messenger'] = $this->facebookMessenger['value'];
        }
        if (!empty($this->alexa)) {
            $json['alexa']              = $this->alexa['value'];
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
