<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models;

use stdClass;
use TwilioApIsLib\ApiHelper;
use TwilioApIsLib\Utils\DateTimeHelper;

class RateLimit implements \JsonSerializable
{
    /**
     * @var array
     */
    private $sid = [];

    /**
     * @var array
     */
    private $serviceSid = [];

    /**
     * @var array
     */
    private $accountSid = [];

    /**
     * @var array
     */
    private $uniqueName = [];

    /**
     * @var array
     */
    private $description = [];

    /**
     * @var array
     */
    private $dateCreated = [];

    /**
     * @var array
     */
    private $dateUpdated = [];

    /**
     * @var array
     */
    private $url = [];

    /**
     * @var array
     */
    private $links = [];

    /**
     * Returns Sid.
     * A 34 character string that uniquely identifies this Rate Limit.
     */
    public function getSid(): ?string
    {
        if (count($this->sid) == 0) {
            return null;
        }
        return $this->sid['value'];
    }

    /**
     * Sets Sid.
     * A 34 character string that uniquely identifies this Rate Limit.
     *
     * @maps sid
     */
    public function setSid(?string $sid): void
    {
        $this->sid['value'] = $sid;
    }

    /**
     * Unsets Sid.
     * A 34 character string that uniquely identifies this Rate Limit.
     */
    public function unsetSid(): void
    {
        $this->sid = [];
    }

    /**
     * Returns Service Sid.
     * The SID of the [Service](https://www.twilio.com/docs/verify/api/service) the resource is associated
     * with.
     */
    public function getServiceSid(): ?string
    {
        if (count($this->serviceSid) == 0) {
            return null;
        }
        return $this->serviceSid['value'];
    }

    /**
     * Sets Service Sid.
     * The SID of the [Service](https://www.twilio.com/docs/verify/api/service) the resource is associated
     * with.
     *
     * @maps service_sid
     */
    public function setServiceSid(?string $serviceSid): void
    {
        $this->serviceSid['value'] = $serviceSid;
    }

    /**
     * Unsets Service Sid.
     * The SID of the [Service](https://www.twilio.com/docs/verify/api/service) the resource is associated
     * with.
     */
    public function unsetServiceSid(): void
    {
        $this->serviceSid = [];
    }

    /**
     * Returns Account Sid.
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Rate Limit
     * resource.
     */
    public function getAccountSid(): ?string
    {
        if (count($this->accountSid) == 0) {
            return null;
        }
        return $this->accountSid['value'];
    }

    /**
     * Sets Account Sid.
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Rate Limit
     * resource.
     *
     * @maps account_sid
     */
    public function setAccountSid(?string $accountSid): void
    {
        $this->accountSid['value'] = $accountSid;
    }

    /**
     * Unsets Account Sid.
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Rate Limit
     * resource.
     */
    public function unsetAccountSid(): void
    {
        $this->accountSid = [];
    }

    /**
     * Returns Unique Name.
     * Provides a unique and addressable name to be assigned to this Rate Limit, assigned by the developer,
     * to be optionally used in addition to SID. **This value should not contain PII.**
     */
    public function getUniqueName(): ?string
    {
        if (count($this->uniqueName) == 0) {
            return null;
        }
        return $this->uniqueName['value'];
    }

    /**
     * Sets Unique Name.
     * Provides a unique and addressable name to be assigned to this Rate Limit, assigned by the developer,
     * to be optionally used in addition to SID. **This value should not contain PII.**
     *
     * @maps unique_name
     */
    public function setUniqueName(?string $uniqueName): void
    {
        $this->uniqueName['value'] = $uniqueName;
    }

    /**
     * Unsets Unique Name.
     * Provides a unique and addressable name to be assigned to this Rate Limit, assigned by the developer,
     * to be optionally used in addition to SID. **This value should not contain PII.**
     */
    public function unsetUniqueName(): void
    {
        $this->uniqueName = [];
    }

    /**
     * Returns Description.
     * Description of this Rate Limit
     */
    public function getDescription(): ?string
    {
        if (count($this->description) == 0) {
            return null;
        }
        return $this->description['value'];
    }

    /**
     * Sets Description.
     * Description of this Rate Limit
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description['value'] = $description;
    }

    /**
     * Unsets Description.
     * Description of this Rate Limit
     */
    public function unsetDescription(): void
    {
        $this->description = [];
    }

    /**
     * Returns Date Created.
     * The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.
     * org/rfc/rfc2822.txt) format.
     */
    public function getDateCreated(): ?\DateTime
    {
        if (count($this->dateCreated) == 0) {
            return null;
        }
        return $this->dateCreated['value'];
    }

    /**
     * Sets Date Created.
     * The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.
     * org/rfc/rfc2822.txt) format.
     *
     * @maps date_created
     * @factory \TwilioApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateCreated(?\DateTime $dateCreated): void
    {
        $this->dateCreated['value'] = $dateCreated;
    }

    /**
     * Unsets Date Created.
     * The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.
     * org/rfc/rfc2822.txt) format.
     */
    public function unsetDateCreated(): void
    {
        $this->dateCreated = [];
    }

    /**
     * Returns Date Updated.
     * The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.
     * org/rfc/rfc2822.txt) format.
     */
    public function getDateUpdated(): ?\DateTime
    {
        if (count($this->dateUpdated) == 0) {
            return null;
        }
        return $this->dateUpdated['value'];
    }

    /**
     * Sets Date Updated.
     * The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.
     * org/rfc/rfc2822.txt) format.
     *
     * @maps date_updated
     * @factory \TwilioApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateUpdated(?\DateTime $dateUpdated): void
    {
        $this->dateUpdated['value'] = $dateUpdated;
    }

    /**
     * Unsets Date Updated.
     * The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.
     * org/rfc/rfc2822.txt) format.
     */
    public function unsetDateUpdated(): void
    {
        $this->dateUpdated = [];
    }

    /**
     * Returns Url.
     * The URL of this resource.
     */
    public function getUrl(): ?string
    {
        if (count($this->url) == 0) {
            return null;
        }
        return $this->url['value'];
    }

    /**
     * Sets Url.
     * The URL of this resource.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url['value'] = $url;
    }

    /**
     * Unsets Url.
     * The URL of this resource.
     */
    public function unsetUrl(): void
    {
        $this->url = [];
    }

    /**
     * Returns Links.
     * The URLs of related resources.
     */
    public function getLinks(): ?array
    {
        if (count($this->links) == 0) {
            return null;
        }
        return $this->links['value'];
    }

    /**
     * Sets Links.
     * The URLs of related resources.
     *
     * @maps links
     */
    public function setLinks(?array $links): void
    {
        $this->links['value'] = $links;
    }

    /**
     * Unsets Links.
     * The URLs of related resources.
     */
    public function unsetLinks(): void
    {
        $this->links = [];
    }

    /**
     * Converts the RateLimit object to a human-readable string representation.
     *
     * @return string The string representation of the RateLimit object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'RateLimit',
            [
                'sid' => $this->getSid(),
                'serviceSid' => $this->getServiceSid(),
                'accountSid' => $this->getAccountSid(),
                'uniqueName' => $this->getUniqueName(),
                'description' => $this->getDescription(),
                'dateCreated' => $this->getDateCreated(),
                'dateUpdated' => $this->getDateUpdated(),
                'url' => $this->getUrl(),
                'links' => $this->getLinks(),
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'sid',
        'service_sid',
        'account_sid',
        'unique_name',
        'description',
        'date_created',
        'date_updated',
        'url',
        'links'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->sid)) {
            $json['sid']          = $this->sid['value'];
        }
        if (!empty($this->serviceSid)) {
            $json['service_sid']  = $this->serviceSid['value'];
        }
        if (!empty($this->accountSid)) {
            $json['account_sid']  = $this->accountSid['value'];
        }
        if (!empty($this->uniqueName)) {
            $json['unique_name']  = $this->uniqueName['value'];
        }
        if (!empty($this->description)) {
            $json['description']  = $this->description['value'];
        }
        if (!empty($this->dateCreated)) {
            $json['date_created'] = DateTimeHelper::toRfc3339DateTime($this->dateCreated['value']);
        }
        if (!empty($this->dateUpdated)) {
            $json['date_updated'] = DateTimeHelper::toRfc3339DateTime($this->dateUpdated['value']);
        }
        if (!empty($this->url)) {
            $json['url']          = $this->url['value'];
        }
        if (!empty($this->links)) {
            $json['links']        = $this->links['value'];
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
