<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models;

use stdClass;
use TwilioApIsLib\ApiHelper;
use TwilioApIsLib\Utils\DateTimeHelper;

class Service implements \JsonSerializable
{
    /**
     * @var array
     */
    private $accountSid = [];

    /**
     * @var array
     */
    private $sid = [];

    /**
     * @var array
     */
    private $friendlyName = [];

    /**
     * @var array
     */
    private $dateCreated = [];

    /**
     * @var array
     */
    private $dateUpdated = [];

    /**
     * @var array
     */
    private $url = [];

    /**
     * @var array
     */
    private $links = [];

    /**
     * Returns Account Sid.
     * The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this
     * service.
     */
    public function getAccountSid(): ?string
    {
        if (count($this->accountSid) == 0) {
            return null;
        }
        return $this->accountSid['value'];
    }

    /**
     * Sets Account Sid.
     * The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this
     * service.
     *
     * @maps account_sid
     */
    public function setAccountSid(?string $accountSid): void
    {
        $this->accountSid['value'] = $accountSid;
    }

    /**
     * Unsets Account Sid.
     * The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this
     * service.
     */
    public function unsetAccountSid(): void
    {
        $this->accountSid = [];
    }

    /**
     * Returns Sid.
     * A 34 character string that uniquely identifies this resource.
     */
    public function getSid(): ?string
    {
        if (count($this->sid) == 0) {
            return null;
        }
        return $this->sid['value'];
    }

    /**
     * Sets Sid.
     * A 34 character string that uniquely identifies this resource.
     *
     * @maps sid
     */
    public function setSid(?string $sid): void
    {
        $this->sid['value'] = $sid;
    }

    /**
     * Unsets Sid.
     * A 34 character string that uniquely identifies this resource.
     */
    public function unsetSid(): void
    {
        $this->sid = [];
    }

    /**
     * Returns Friendly Name.
     * The human-readable name of this service, limited to 256 characters. Optional.
     */
    public function getFriendlyName(): ?string
    {
        if (count($this->friendlyName) == 0) {
            return null;
        }
        return $this->friendlyName['value'];
    }

    /**
     * Sets Friendly Name.
     * The human-readable name of this service, limited to 256 characters. Optional.
     *
     * @maps friendly_name
     */
    public function setFriendlyName(?string $friendlyName): void
    {
        $this->friendlyName['value'] = $friendlyName;
    }

    /**
     * Unsets Friendly Name.
     * The human-readable name of this service, limited to 256 characters. Optional.
     */
    public function unsetFriendlyName(): void
    {
        $this->friendlyName = [];
    }

    /**
     * Returns Date Created.
     * The date that this resource was created.
     */
    public function getDateCreated(): ?\DateTime
    {
        if (count($this->dateCreated) == 0) {
            return null;
        }
        return $this->dateCreated['value'];
    }

    /**
     * Sets Date Created.
     * The date that this resource was created.
     *
     * @maps date_created
     * @factory \TwilioApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateCreated(?\DateTime $dateCreated): void
    {
        $this->dateCreated['value'] = $dateCreated;
    }

    /**
     * Unsets Date Created.
     * The date that this resource was created.
     */
    public function unsetDateCreated(): void
    {
        $this->dateCreated = [];
    }

    /**
     * Returns Date Updated.
     * The date that this resource was last updated.
     */
    public function getDateUpdated(): ?\DateTime
    {
        if (count($this->dateUpdated) == 0) {
            return null;
        }
        return $this->dateUpdated['value'];
    }

    /**
     * Sets Date Updated.
     * The date that this resource was last updated.
     *
     * @maps date_updated
     * @factory \TwilioApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateUpdated(?\DateTime $dateUpdated): void
    {
        $this->dateUpdated['value'] = $dateUpdated;
    }

    /**
     * Unsets Date Updated.
     * The date that this resource was last updated.
     */
    public function unsetDateUpdated(): void
    {
        $this->dateUpdated = [];
    }

    /**
     * Returns Url.
     * An absolute API resource URL for this service.
     */
    public function getUrl(): ?string
    {
        if (count($this->url) == 0) {
            return null;
        }
        return $this->url['value'];
    }

    /**
     * Sets Url.
     * An absolute API resource URL for this service.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url['value'] = $url;
    }

    /**
     * Unsets Url.
     * An absolute API resource URL for this service.
     */
    public function unsetUrl(): void
    {
        $this->url = [];
    }

    /**
     * Returns Links.
     * Contains absolute API resource URLs to access conversations, users, roles, bindings and
     * configuration of this service.
     */
    public function getLinks(): ?array
    {
        if (count($this->links) == 0) {
            return null;
        }
        return $this->links['value'];
    }

    /**
     * Sets Links.
     * Contains absolute API resource URLs to access conversations, users, roles, bindings and
     * configuration of this service.
     *
     * @maps links
     */
    public function setLinks(?array $links): void
    {
        $this->links['value'] = $links;
    }

    /**
     * Unsets Links.
     * Contains absolute API resource URLs to access conversations, users, roles, bindings and
     * configuration of this service.
     */
    public function unsetLinks(): void
    {
        $this->links = [];
    }

    /**
     * Converts the Service object to a human-readable string representation.
     *
     * @return string The string representation of the Service object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Service',
            [
                'accountSid' => $this->getAccountSid(),
                'sid' => $this->getSid(),
                'friendlyName' => $this->getFriendlyName(),
                'dateCreated' => $this->getDateCreated(),
                'dateUpdated' => $this->getDateUpdated(),
                'url' => $this->getUrl(),
                'links' => $this->getLinks(),
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['account_sid', 'sid', 'friendly_name', 'date_created', 'date_updated', 'url', 'links'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->accountSid)) {
            $json['account_sid']   = $this->accountSid['value'];
        }
        if (!empty($this->sid)) {
            $json['sid']           = $this->sid['value'];
        }
        if (!empty($this->friendlyName)) {
            $json['friendly_name'] = $this->friendlyName['value'];
        }
        if (!empty($this->dateCreated)) {
            $json['date_created']  = DateTimeHelper::toRfc3339DateTime($this->dateCreated['value']);
        }
        if (!empty($this->dateUpdated)) {
            $json['date_updated']  = DateTimeHelper::toRfc3339DateTime($this->dateUpdated['value']);
        }
        if (!empty($this->url)) {
            $json['url']           = $this->url['value'];
        }
        if (!empty($this->links)) {
            $json['links']         = $this->links['value'];
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
