<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models;

use stdClass;
use TwilioApIsLib\ApiHelper;
use TwilioApIsLib\Utils\DateTimeHelper;

class ServiceConversationScopedWebhook implements \JsonSerializable
{
    /**
     * @var array
     */
    private $sid = [];

    /**
     * @var array
     */
    private $accountSid = [];

    /**
     * @var array
     */
    private $chatServiceSid = [];

    /**
     * @var array
     */
    private $conversationSid = [];

    /**
     * @var array
     */
    private $target = [];

    /**
     * @var array
     */
    private $url = [];

    /**
     * @var array
     */
    private $configuration = [];

    /**
     * @var array
     */
    private $dateCreated = [];

    /**
     * @var array
     */
    private $dateUpdated = [];

    /**
     * Returns Sid.
     * A 34 character string that uniquely identifies this resource.
     */
    public function getSid(): ?string
    {
        if (count($this->sid) == 0) {
            return null;
        }
        return $this->sid['value'];
    }

    /**
     * Sets Sid.
     * A 34 character string that uniquely identifies this resource.
     *
     * @maps sid
     */
    public function setSid(?string $sid): void
    {
        $this->sid['value'] = $sid;
    }

    /**
     * Unsets Sid.
     * A 34 character string that uniquely identifies this resource.
     */
    public function unsetSid(): void
    {
        $this->sid = [];
    }

    /**
     * Returns Account Sid.
     * The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this
     * conversation.
     */
    public function getAccountSid(): ?string
    {
        if (count($this->accountSid) == 0) {
            return null;
        }
        return $this->accountSid['value'];
    }

    /**
     * Sets Account Sid.
     * The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this
     * conversation.
     *
     * @maps account_sid
     */
    public function setAccountSid(?string $accountSid): void
    {
        $this->accountSid['value'] = $accountSid;
    }

    /**
     * Unsets Account Sid.
     * The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this
     * conversation.
     */
    public function unsetAccountSid(): void
    {
        $this->accountSid = [];
    }

    /**
     * Returns Chat Service Sid.
     * The SID of the [Conversation Service](https://www.twilio.com/docs/conversations/api/service-
     * resource) the Participant resource is associated with.
     */
    public function getChatServiceSid(): ?string
    {
        if (count($this->chatServiceSid) == 0) {
            return null;
        }
        return $this->chatServiceSid['value'];
    }

    /**
     * Sets Chat Service Sid.
     * The SID of the [Conversation Service](https://www.twilio.com/docs/conversations/api/service-
     * resource) the Participant resource is associated with.
     *
     * @maps chat_service_sid
     */
    public function setChatServiceSid(?string $chatServiceSid): void
    {
        $this->chatServiceSid['value'] = $chatServiceSid;
    }

    /**
     * Unsets Chat Service Sid.
     * The SID of the [Conversation Service](https://www.twilio.com/docs/conversations/api/service-
     * resource) the Participant resource is associated with.
     */
    public function unsetChatServiceSid(): void
    {
        $this->chatServiceSid = [];
    }

    /**
     * Returns Conversation Sid.
     * The unique ID of the [Conversation](https://www.twilio.com/docs/conversations/api/conversation-
     * resource) for this webhook.
     */
    public function getConversationSid(): ?string
    {
        if (count($this->conversationSid) == 0) {
            return null;
        }
        return $this->conversationSid['value'];
    }

    /**
     * Sets Conversation Sid.
     * The unique ID of the [Conversation](https://www.twilio.com/docs/conversations/api/conversation-
     * resource) for this webhook.
     *
     * @maps conversation_sid
     */
    public function setConversationSid(?string $conversationSid): void
    {
        $this->conversationSid['value'] = $conversationSid;
    }

    /**
     * Unsets Conversation Sid.
     * The unique ID of the [Conversation](https://www.twilio.com/docs/conversations/api/conversation-
     * resource) for this webhook.
     */
    public function unsetConversationSid(): void
    {
        $this->conversationSid = [];
    }

    /**
     * Returns Target.
     * The target of this webhook: `webhook`, `studio`, `trigger`
     */
    public function getTarget(): ?string
    {
        if (count($this->target) == 0) {
            return null;
        }
        return $this->target['value'];
    }

    /**
     * Sets Target.
     * The target of this webhook: `webhook`, `studio`, `trigger`
     *
     * @maps target
     */
    public function setTarget(?string $target): void
    {
        $this->target['value'] = $target;
    }

    /**
     * Unsets Target.
     * The target of this webhook: `webhook`, `studio`, `trigger`
     */
    public function unsetTarget(): void
    {
        $this->target = [];
    }

    /**
     * Returns Url.
     * An absolute API resource URL for this webhook.
     */
    public function getUrl(): ?string
    {
        if (count($this->url) == 0) {
            return null;
        }
        return $this->url['value'];
    }

    /**
     * Sets Url.
     * An absolute API resource URL for this webhook.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url['value'] = $url;
    }

    /**
     * Unsets Url.
     * An absolute API resource URL for this webhook.
     */
    public function unsetUrl(): void
    {
        $this->url = [];
    }

    /**
     * Returns Configuration.
     * The configuration of this webhook. Is defined based on target.
     */
    public function getConfiguration(): ?array
    {
        if (count($this->configuration) == 0) {
            return null;
        }
        return $this->configuration['value'];
    }

    /**
     * Sets Configuration.
     * The configuration of this webhook. Is defined based on target.
     *
     * @maps configuration
     */
    public function setConfiguration(?array $configuration): void
    {
        $this->configuration['value'] = $configuration;
    }

    /**
     * Unsets Configuration.
     * The configuration of this webhook. Is defined based on target.
     */
    public function unsetConfiguration(): void
    {
        $this->configuration = [];
    }

    /**
     * Returns Date Created.
     * The date that this resource was created.
     */
    public function getDateCreated(): ?\DateTime
    {
        if (count($this->dateCreated) == 0) {
            return null;
        }
        return $this->dateCreated['value'];
    }

    /**
     * Sets Date Created.
     * The date that this resource was created.
     *
     * @maps date_created
     * @factory \TwilioApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateCreated(?\DateTime $dateCreated): void
    {
        $this->dateCreated['value'] = $dateCreated;
    }

    /**
     * Unsets Date Created.
     * The date that this resource was created.
     */
    public function unsetDateCreated(): void
    {
        $this->dateCreated = [];
    }

    /**
     * Returns Date Updated.
     * The date that this resource was last updated.
     */
    public function getDateUpdated(): ?\DateTime
    {
        if (count($this->dateUpdated) == 0) {
            return null;
        }
        return $this->dateUpdated['value'];
    }

    /**
     * Sets Date Updated.
     * The date that this resource was last updated.
     *
     * @maps date_updated
     * @factory \TwilioApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateUpdated(?\DateTime $dateUpdated): void
    {
        $this->dateUpdated['value'] = $dateUpdated;
    }

    /**
     * Unsets Date Updated.
     * The date that this resource was last updated.
     */
    public function unsetDateUpdated(): void
    {
        $this->dateUpdated = [];
    }

    /**
     * Converts the ServiceConversationScopedWebhook object to a human-readable string representation.
     *
     * @return string The string representation of the ServiceConversationScopedWebhook object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ServiceConversationScopedWebhook',
            [
                'sid' => $this->getSid(),
                'accountSid' => $this->getAccountSid(),
                'chatServiceSid' => $this->getChatServiceSid(),
                'conversationSid' => $this->getConversationSid(),
                'target' => $this->getTarget(),
                'url' => $this->getUrl(),
                'configuration' => $this->getConfiguration(),
                'dateCreated' => $this->getDateCreated(),
                'dateUpdated' => $this->getDateUpdated(),
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'sid',
        'account_sid',
        'chat_service_sid',
        'conversation_sid',
        'target',
        'url',
        'configuration',
        'date_created',
        'date_updated'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->sid)) {
            $json['sid']              = $this->sid['value'];
        }
        if (!empty($this->accountSid)) {
            $json['account_sid']      = $this->accountSid['value'];
        }
        if (!empty($this->chatServiceSid)) {
            $json['chat_service_sid'] = $this->chatServiceSid['value'];
        }
        if (!empty($this->conversationSid)) {
            $json['conversation_sid'] = $this->conversationSid['value'];
        }
        if (!empty($this->target)) {
            $json['target']           = $this->target['value'];
        }
        if (!empty($this->url)) {
            $json['url']              = $this->url['value'];
        }
        if (!empty($this->configuration)) {
            $json['configuration']    = $this->configuration['value'];
        }
        if (!empty($this->dateCreated)) {
            $json['date_created']     = DateTimeHelper::toRfc3339DateTime($this->dateCreated['value']);
        }
        if (!empty($this->dateUpdated)) {
            $json['date_updated']     = DateTimeHelper::toRfc3339DateTime($this->dateUpdated['value']);
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
