<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models;

use stdClass;
use TwilioApIsLib\ApiHelper;
use TwilioApIsLib\Utils\DateTimeHelper;

class ServiceUserConversation implements \JsonSerializable
{
    /**
     * @var array
     */
    private $accountSid = [];

    /**
     * @var array
     */
    private $chatServiceSid = [];

    /**
     * @var array
     */
    private $conversationSid = [];

    /**
     * @var array
     */
    private $unreadMessagesCount = [];

    /**
     * @var array
     */
    private $lastReadMessageIndex = [];

    /**
     * @var array
     */
    private $participantSid = [];

    /**
     * @var array
     */
    private $userSid = [];

    /**
     * @var array
     */
    private $friendlyName = [];

    /**
     * @var string|null
     */
    private $conversationState;

    /**
     * @var array
     */
    private $timers = [];

    /**
     * @var array
     */
    private $attributes = [];

    /**
     * @var array
     */
    private $dateCreated = [];

    /**
     * @var array
     */
    private $dateUpdated = [];

    /**
     * @var array
     */
    private $createdBy = [];

    /**
     * @var string|null
     */
    private $notificationLevel;

    /**
     * @var array
     */
    private $uniqueName = [];

    /**
     * @var array
     */
    private $url = [];

    /**
     * @var array
     */
    private $links = [];

    /**
     * Returns Account Sid.
     * The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this
     * conversation.
     */
    public function getAccountSid(): ?string
    {
        if (count($this->accountSid) == 0) {
            return null;
        }
        return $this->accountSid['value'];
    }

    /**
     * Sets Account Sid.
     * The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this
     * conversation.
     *
     * @maps account_sid
     */
    public function setAccountSid(?string $accountSid): void
    {
        $this->accountSid['value'] = $accountSid;
    }

    /**
     * Unsets Account Sid.
     * The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this
     * conversation.
     */
    public function unsetAccountSid(): void
    {
        $this->accountSid = [];
    }

    /**
     * Returns Chat Service Sid.
     * The unique ID of the [Conversation Service](https://www.twilio.com/docs/conversations/api/service-
     * resource) this conversation belongs to.
     */
    public function getChatServiceSid(): ?string
    {
        if (count($this->chatServiceSid) == 0) {
            return null;
        }
        return $this->chatServiceSid['value'];
    }

    /**
     * Sets Chat Service Sid.
     * The unique ID of the [Conversation Service](https://www.twilio.com/docs/conversations/api/service-
     * resource) this conversation belongs to.
     *
     * @maps chat_service_sid
     */
    public function setChatServiceSid(?string $chatServiceSid): void
    {
        $this->chatServiceSid['value'] = $chatServiceSid;
    }

    /**
     * Unsets Chat Service Sid.
     * The unique ID of the [Conversation Service](https://www.twilio.com/docs/conversations/api/service-
     * resource) this conversation belongs to.
     */
    public function unsetChatServiceSid(): void
    {
        $this->chatServiceSid = [];
    }

    /**
     * Returns Conversation Sid.
     * The unique ID of the [Conversation](https://www.twilio.com/docs/conversations/api/conversation-
     * resource) for this User Conversation.
     */
    public function getConversationSid(): ?string
    {
        if (count($this->conversationSid) == 0) {
            return null;
        }
        return $this->conversationSid['value'];
    }

    /**
     * Sets Conversation Sid.
     * The unique ID of the [Conversation](https://www.twilio.com/docs/conversations/api/conversation-
     * resource) for this User Conversation.
     *
     * @maps conversation_sid
     */
    public function setConversationSid(?string $conversationSid): void
    {
        $this->conversationSid['value'] = $conversationSid;
    }

    /**
     * Unsets Conversation Sid.
     * The unique ID of the [Conversation](https://www.twilio.com/docs/conversations/api/conversation-
     * resource) for this User Conversation.
     */
    public function unsetConversationSid(): void
    {
        $this->conversationSid = [];
    }

    /**
     * Returns Unread Messages Count.
     * The number of unread Messages in the Conversation for the Participant.
     */
    public function getUnreadMessagesCount(): ?int
    {
        if (count($this->unreadMessagesCount) == 0) {
            return null;
        }
        return $this->unreadMessagesCount['value'];
    }

    /**
     * Sets Unread Messages Count.
     * The number of unread Messages in the Conversation for the Participant.
     *
     * @maps unread_messages_count
     */
    public function setUnreadMessagesCount(?int $unreadMessagesCount): void
    {
        $this->unreadMessagesCount['value'] = $unreadMessagesCount;
    }

    /**
     * Unsets Unread Messages Count.
     * The number of unread Messages in the Conversation for the Participant.
     */
    public function unsetUnreadMessagesCount(): void
    {
        $this->unreadMessagesCount = [];
    }

    /**
     * Returns Last Read Message Index.
     * The index of the last Message in the Conversation that the Participant has read.
     */
    public function getLastReadMessageIndex(): ?int
    {
        if (count($this->lastReadMessageIndex) == 0) {
            return null;
        }
        return $this->lastReadMessageIndex['value'];
    }

    /**
     * Sets Last Read Message Index.
     * The index of the last Message in the Conversation that the Participant has read.
     *
     * @maps last_read_message_index
     */
    public function setLastReadMessageIndex(?int $lastReadMessageIndex): void
    {
        $this->lastReadMessageIndex['value'] = $lastReadMessageIndex;
    }

    /**
     * Unsets Last Read Message Index.
     * The index of the last Message in the Conversation that the Participant has read.
     */
    public function unsetLastReadMessageIndex(): void
    {
        $this->lastReadMessageIndex = [];
    }

    /**
     * Returns Participant Sid.
     * The unique ID of the [participant](https://www.twilio.com/docs/conversations/api/conversation-
     * participant-resource) the user conversation belongs to.
     */
    public function getParticipantSid(): ?string
    {
        if (count($this->participantSid) == 0) {
            return null;
        }
        return $this->participantSid['value'];
    }

    /**
     * Sets Participant Sid.
     * The unique ID of the [participant](https://www.twilio.com/docs/conversations/api/conversation-
     * participant-resource) the user conversation belongs to.
     *
     * @maps participant_sid
     */
    public function setParticipantSid(?string $participantSid): void
    {
        $this->participantSid['value'] = $participantSid;
    }

    /**
     * Unsets Participant Sid.
     * The unique ID of the [participant](https://www.twilio.com/docs/conversations/api/conversation-
     * participant-resource) the user conversation belongs to.
     */
    public function unsetParticipantSid(): void
    {
        $this->participantSid = [];
    }

    /**
     * Returns User Sid.
     * The unique string that identifies the [User resource](https://www.twilio.
     * com/docs/conversations/api/user-resource).
     */
    public function getUserSid(): ?string
    {
        if (count($this->userSid) == 0) {
            return null;
        }
        return $this->userSid['value'];
    }

    /**
     * Sets User Sid.
     * The unique string that identifies the [User resource](https://www.twilio.
     * com/docs/conversations/api/user-resource).
     *
     * @maps user_sid
     */
    public function setUserSid(?string $userSid): void
    {
        $this->userSid['value'] = $userSid;
    }

    /**
     * Unsets User Sid.
     * The unique string that identifies the [User resource](https://www.twilio.
     * com/docs/conversations/api/user-resource).
     */
    public function unsetUserSid(): void
    {
        $this->userSid = [];
    }

    /**
     * Returns Friendly Name.
     * The human-readable name of this conversation, limited to 256 characters. Optional.
     */
    public function getFriendlyName(): ?string
    {
        if (count($this->friendlyName) == 0) {
            return null;
        }
        return $this->friendlyName['value'];
    }

    /**
     * Sets Friendly Name.
     * The human-readable name of this conversation, limited to 256 characters. Optional.
     *
     * @maps friendly_name
     */
    public function setFriendlyName(?string $friendlyName): void
    {
        $this->friendlyName['value'] = $friendlyName;
    }

    /**
     * Unsets Friendly Name.
     * The human-readable name of this conversation, limited to 256 characters. Optional.
     */
    public function unsetFriendlyName(): void
    {
        $this->friendlyName = [];
    }

    /**
     * Returns Conversation State.
     * The current state of this User Conversation. One of `inactive`, `active` or `closed`.
     */
    public function getConversationState(): ?string
    {
        return $this->conversationState;
    }

    /**
     * Sets Conversation State.
     * The current state of this User Conversation. One of `inactive`, `active` or `closed`.
     *
     * @maps conversation_state
     * @factory \TwilioApIsLib\Models\ServiceUserConversationState::checkValue
     */
    public function setConversationState(?string $conversationState): void
    {
        $this->conversationState = $conversationState;
    }

    /**
     * Returns Timers.
     * Timer date values representing state update for this conversation.
     */
    public function getTimers(): ?array
    {
        if (count($this->timers) == 0) {
            return null;
        }
        return $this->timers['value'];
    }

    /**
     * Sets Timers.
     * Timer date values representing state update for this conversation.
     *
     * @maps timers
     */
    public function setTimers(?array $timers): void
    {
        $this->timers['value'] = $timers;
    }

    /**
     * Unsets Timers.
     * Timer date values representing state update for this conversation.
     */
    public function unsetTimers(): void
    {
        $this->timers = [];
    }

    /**
     * Returns Attributes.
     * An optional string metadata field you can use to store any data you wish. The string value must
     * contain structurally valid JSON if specified.  **Note** that if the attributes are not set "{}" will
     * be returned.
     */
    public function getAttributes(): ?string
    {
        if (count($this->attributes) == 0) {
            return null;
        }
        return $this->attributes['value'];
    }

    /**
     * Sets Attributes.
     * An optional string metadata field you can use to store any data you wish. The string value must
     * contain structurally valid JSON if specified.  **Note** that if the attributes are not set "{}" will
     * be returned.
     *
     * @maps attributes
     */
    public function setAttributes(?string $attributes): void
    {
        $this->attributes['value'] = $attributes;
    }

    /**
     * Unsets Attributes.
     * An optional string metadata field you can use to store any data you wish. The string value must
     * contain structurally valid JSON if specified.  **Note** that if the attributes are not set "{}" will
     * be returned.
     */
    public function unsetAttributes(): void
    {
        $this->attributes = [];
    }

    /**
     * Returns Date Created.
     * The date that this conversation was created, given in ISO 8601 format.
     */
    public function getDateCreated(): ?\DateTime
    {
        if (count($this->dateCreated) == 0) {
            return null;
        }
        return $this->dateCreated['value'];
    }

    /**
     * Sets Date Created.
     * The date that this conversation was created, given in ISO 8601 format.
     *
     * @maps date_created
     * @factory \TwilioApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateCreated(?\DateTime $dateCreated): void
    {
        $this->dateCreated['value'] = $dateCreated;
    }

    /**
     * Unsets Date Created.
     * The date that this conversation was created, given in ISO 8601 format.
     */
    public function unsetDateCreated(): void
    {
        $this->dateCreated = [];
    }

    /**
     * Returns Date Updated.
     * The date that this conversation was last updated, given in ISO 8601 format.
     */
    public function getDateUpdated(): ?\DateTime
    {
        if (count($this->dateUpdated) == 0) {
            return null;
        }
        return $this->dateUpdated['value'];
    }

    /**
     * Sets Date Updated.
     * The date that this conversation was last updated, given in ISO 8601 format.
     *
     * @maps date_updated
     * @factory \TwilioApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateUpdated(?\DateTime $dateUpdated): void
    {
        $this->dateUpdated['value'] = $dateUpdated;
    }

    /**
     * Unsets Date Updated.
     * The date that this conversation was last updated, given in ISO 8601 format.
     */
    public function unsetDateUpdated(): void
    {
        $this->dateUpdated = [];
    }

    /**
     * Returns Created By.
     * Identity of the creator of this Conversation.
     */
    public function getCreatedBy(): ?string
    {
        if (count($this->createdBy) == 0) {
            return null;
        }
        return $this->createdBy['value'];
    }

    /**
     * Sets Created By.
     * Identity of the creator of this Conversation.
     *
     * @maps created_by
     */
    public function setCreatedBy(?string $createdBy): void
    {
        $this->createdBy['value'] = $createdBy;
    }

    /**
     * Unsets Created By.
     * Identity of the creator of this Conversation.
     */
    public function unsetCreatedBy(): void
    {
        $this->createdBy = [];
    }

    /**
     * Returns Notification Level.
     * The Notification Level of this User Conversation. One of `default` or `muted`.
     */
    public function getNotificationLevel(): ?string
    {
        return $this->notificationLevel;
    }

    /**
     * Sets Notification Level.
     * The Notification Level of this User Conversation. One of `default` or `muted`.
     *
     * @maps notification_level
     * @factory \TwilioApIsLib\Models\ServiceUserConversationNotificationLevel::checkValue
     */
    public function setNotificationLevel(?string $notificationLevel): void
    {
        $this->notificationLevel = $notificationLevel;
    }

    /**
     * Returns Unique Name.
     * An application-defined string that uniquely identifies the Conversation resource. It can be used to
     * address the resource in place of the resource's `conversation_sid` in the URL.
     */
    public function getUniqueName(): ?string
    {
        if (count($this->uniqueName) == 0) {
            return null;
        }
        return $this->uniqueName['value'];
    }

    /**
     * Sets Unique Name.
     * An application-defined string that uniquely identifies the Conversation resource. It can be used to
     * address the resource in place of the resource's `conversation_sid` in the URL.
     *
     * @maps unique_name
     */
    public function setUniqueName(?string $uniqueName): void
    {
        $this->uniqueName['value'] = $uniqueName;
    }

    /**
     * Unsets Unique Name.
     * An application-defined string that uniquely identifies the Conversation resource. It can be used to
     * address the resource in place of the resource's `conversation_sid` in the URL.
     */
    public function unsetUniqueName(): void
    {
        $this->uniqueName = [];
    }

    /**
     * Returns Url.
     */
    public function getUrl(): ?string
    {
        if (count($this->url) == 0) {
            return null;
        }
        return $this->url['value'];
    }

    /**
     * Sets Url.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url['value'] = $url;
    }

    /**
     * Unsets Url.
     */
    public function unsetUrl(): void
    {
        $this->url = [];
    }

    /**
     * Returns Links.
     * Contains absolute URLs to access the [participant](https://www.twilio.
     * com/docs/conversations/api/conversation-participant-resource) and [conversation](https://www.twilio.
     * com/docs/conversations/api/conversation-resource) of this conversation.
     */
    public function getLinks(): ?array
    {
        if (count($this->links) == 0) {
            return null;
        }
        return $this->links['value'];
    }

    /**
     * Sets Links.
     * Contains absolute URLs to access the [participant](https://www.twilio.
     * com/docs/conversations/api/conversation-participant-resource) and [conversation](https://www.twilio.
     * com/docs/conversations/api/conversation-resource) of this conversation.
     *
     * @maps links
     */
    public function setLinks(?array $links): void
    {
        $this->links['value'] = $links;
    }

    /**
     * Unsets Links.
     * Contains absolute URLs to access the [participant](https://www.twilio.
     * com/docs/conversations/api/conversation-participant-resource) and [conversation](https://www.twilio.
     * com/docs/conversations/api/conversation-resource) of this conversation.
     */
    public function unsetLinks(): void
    {
        $this->links = [];
    }

    /**
     * Converts the ServiceUserConversation object to a human-readable string representation.
     *
     * @return string The string representation of the ServiceUserConversation object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ServiceUserConversation',
            [
                'accountSid' => $this->getAccountSid(),
                'chatServiceSid' => $this->getChatServiceSid(),
                'conversationSid' => $this->getConversationSid(),
                'unreadMessagesCount' => $this->getUnreadMessagesCount(),
                'lastReadMessageIndex' => $this->getLastReadMessageIndex(),
                'participantSid' => $this->getParticipantSid(),
                'userSid' => $this->getUserSid(),
                'friendlyName' => $this->getFriendlyName(),
                'conversationState' => $this->conversationState,
                'timers' => $this->getTimers(),
                'attributes' => $this->getAttributes(),
                'dateCreated' => $this->getDateCreated(),
                'dateUpdated' => $this->getDateUpdated(),
                'createdBy' => $this->getCreatedBy(),
                'notificationLevel' => $this->notificationLevel,
                'uniqueName' => $this->getUniqueName(),
                'url' => $this->getUrl(),
                'links' => $this->getLinks(),
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'account_sid',
        'chat_service_sid',
        'conversation_sid',
        'unread_messages_count',
        'last_read_message_index',
        'participant_sid',
        'user_sid',
        'friendly_name',
        'conversation_state',
        'timers',
        'attributes',
        'date_created',
        'date_updated',
        'created_by',
        'notification_level',
        'unique_name',
        'url',
        'links'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->accountSid)) {
            $json['account_sid']             = $this->accountSid['value'];
        }
        if (!empty($this->chatServiceSid)) {
            $json['chat_service_sid']        = $this->chatServiceSid['value'];
        }
        if (!empty($this->conversationSid)) {
            $json['conversation_sid']        = $this->conversationSid['value'];
        }
        if (!empty($this->unreadMessagesCount)) {
            $json['unread_messages_count']   = $this->unreadMessagesCount['value'];
        }
        if (!empty($this->lastReadMessageIndex)) {
            $json['last_read_message_index'] = $this->lastReadMessageIndex['value'];
        }
        if (!empty($this->participantSid)) {
            $json['participant_sid']         = $this->participantSid['value'];
        }
        if (!empty($this->userSid)) {
            $json['user_sid']                = $this->userSid['value'];
        }
        if (!empty($this->friendlyName)) {
            $json['friendly_name']           = $this->friendlyName['value'];
        }
        if (isset($this->conversationState)) {
            $json['conversation_state']      = ServiceUserConversationState::checkValue($this->conversationState);
        }
        if (!empty($this->timers)) {
            $json['timers']                  = $this->timers['value'];
        }
        if (!empty($this->attributes)) {
            $json['attributes']              = $this->attributes['value'];
        }
        if (!empty($this->dateCreated)) {
            $json['date_created']            = DateTimeHelper::toRfc3339DateTime($this->dateCreated['value']);
        }
        if (!empty($this->dateUpdated)) {
            $json['date_updated']            = DateTimeHelper::toRfc3339DateTime($this->dateUpdated['value']);
        }
        if (!empty($this->createdBy)) {
            $json['created_by']              = $this->createdBy['value'];
        }
        if (isset($this->notificationLevel)) {
            $json['notification_level']      =
                ServiceUserConversationNotificationLevel::checkValue(
                    $this->notificationLevel
                );
        }
        if (!empty($this->uniqueName)) {
            $json['unique_name']             = $this->uniqueName['value'];
        }
        if (!empty($this->url)) {
            $json['url']                     = $this->url['value'];
        }
        if (!empty($this->links)) {
            $json['links']                   = $this->links['value'];
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
