<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models;

use stdClass;
use TwilioApIsLib\ApiHelper;
use TwilioApIsLib\Utils\DateTimeHelper;

class TaskChannel implements \JsonSerializable
{
    /**
     * @var array
     */
    private $accountSid = [];

    /**
     * @var array
     */
    private $dateCreated = [];

    /**
     * @var array
     */
    private $dateUpdated = [];

    /**
     * @var array
     */
    private $friendlyName = [];

    /**
     * @var array
     */
    private $sid = [];

    /**
     * @var array
     */
    private $uniqueName = [];

    /**
     * @var array
     */
    private $workspaceSid = [];

    /**
     * @var array
     */
    private $channelOptimizedRouting = [];

    /**
     * @var array
     */
    private $url = [];

    /**
     * @var array
     */
    private $links = [];

    /**
     * Returns Account Sid.
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Task Channel
     * resource.
     */
    public function getAccountSid(): ?string
    {
        if (count($this->accountSid) == 0) {
            return null;
        }
        return $this->accountSid['value'];
    }

    /**
     * Sets Account Sid.
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Task Channel
     * resource.
     *
     * @maps account_sid
     */
    public function setAccountSid(?string $accountSid): void
    {
        $this->accountSid['value'] = $accountSid;
    }

    /**
     * Unsets Account Sid.
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Task Channel
     * resource.
     */
    public function unsetAccountSid(): void
    {
        $this->accountSid = [];
    }

    /**
     * Returns Date Created.
     * The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.
     * org/wiki/ISO_8601) format.
     */
    public function getDateCreated(): ?\DateTime
    {
        if (count($this->dateCreated) == 0) {
            return null;
        }
        return $this->dateCreated['value'];
    }

    /**
     * Sets Date Created.
     * The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.
     * org/wiki/ISO_8601) format.
     *
     * @maps date_created
     * @factory \TwilioApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateCreated(?\DateTime $dateCreated): void
    {
        $this->dateCreated['value'] = $dateCreated;
    }

    /**
     * Unsets Date Created.
     * The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.
     * org/wiki/ISO_8601) format.
     */
    public function unsetDateCreated(): void
    {
        $this->dateCreated = [];
    }

    /**
     * Returns Date Updated.
     * The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.
     * wikipedia.org/wiki/ISO_8601) format.
     */
    public function getDateUpdated(): ?\DateTime
    {
        if (count($this->dateUpdated) == 0) {
            return null;
        }
        return $this->dateUpdated['value'];
    }

    /**
     * Sets Date Updated.
     * The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.
     * wikipedia.org/wiki/ISO_8601) format.
     *
     * @maps date_updated
     * @factory \TwilioApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateUpdated(?\DateTime $dateUpdated): void
    {
        $this->dateUpdated['value'] = $dateUpdated;
    }

    /**
     * Unsets Date Updated.
     * The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.
     * wikipedia.org/wiki/ISO_8601) format.
     */
    public function unsetDateUpdated(): void
    {
        $this->dateUpdated = [];
    }

    /**
     * Returns Friendly Name.
     * The string that you assigned to describe the resource.
     */
    public function getFriendlyName(): ?string
    {
        if (count($this->friendlyName) == 0) {
            return null;
        }
        return $this->friendlyName['value'];
    }

    /**
     * Sets Friendly Name.
     * The string that you assigned to describe the resource.
     *
     * @maps friendly_name
     */
    public function setFriendlyName(?string $friendlyName): void
    {
        $this->friendlyName['value'] = $friendlyName;
    }

    /**
     * Unsets Friendly Name.
     * The string that you assigned to describe the resource.
     */
    public function unsetFriendlyName(): void
    {
        $this->friendlyName = [];
    }

    /**
     * Returns Sid.
     * The unique string that we created to identify the Task Channel resource.
     */
    public function getSid(): ?string
    {
        if (count($this->sid) == 0) {
            return null;
        }
        return $this->sid['value'];
    }

    /**
     * Sets Sid.
     * The unique string that we created to identify the Task Channel resource.
     *
     * @maps sid
     */
    public function setSid(?string $sid): void
    {
        $this->sid['value'] = $sid;
    }

    /**
     * Unsets Sid.
     * The unique string that we created to identify the Task Channel resource.
     */
    public function unsetSid(): void
    {
        $this->sid = [];
    }

    /**
     * Returns Unique Name.
     * An application-defined string that uniquely identifies the Task Channel, such as `voice` or `sms`.
     */
    public function getUniqueName(): ?string
    {
        if (count($this->uniqueName) == 0) {
            return null;
        }
        return $this->uniqueName['value'];
    }

    /**
     * Sets Unique Name.
     * An application-defined string that uniquely identifies the Task Channel, such as `voice` or `sms`.
     *
     * @maps unique_name
     */
    public function setUniqueName(?string $uniqueName): void
    {
        $this->uniqueName['value'] = $uniqueName;
    }

    /**
     * Unsets Unique Name.
     * An application-defined string that uniquely identifies the Task Channel, such as `voice` or `sms`.
     */
    public function unsetUniqueName(): void
    {
        $this->uniqueName = [];
    }

    /**
     * Returns Workspace Sid.
     * The SID of the Workspace that contains the Task Channel.
     */
    public function getWorkspaceSid(): ?string
    {
        if (count($this->workspaceSid) == 0) {
            return null;
        }
        return $this->workspaceSid['value'];
    }

    /**
     * Sets Workspace Sid.
     * The SID of the Workspace that contains the Task Channel.
     *
     * @maps workspace_sid
     */
    public function setWorkspaceSid(?string $workspaceSid): void
    {
        $this->workspaceSid['value'] = $workspaceSid;
    }

    /**
     * Unsets Workspace Sid.
     * The SID of the Workspace that contains the Task Channel.
     */
    public function unsetWorkspaceSid(): void
    {
        $this->workspaceSid = [];
    }

    /**
     * Returns Channel Optimized Routing.
     * Whether the Task Channel will prioritize Workers that have been idle. When `true`, Workers that have
     * been idle the longest are prioritized.
     */
    public function getChannelOptimizedRouting(): ?bool
    {
        if (count($this->channelOptimizedRouting) == 0) {
            return null;
        }
        return $this->channelOptimizedRouting['value'];
    }

    /**
     * Sets Channel Optimized Routing.
     * Whether the Task Channel will prioritize Workers that have been idle. When `true`, Workers that have
     * been idle the longest are prioritized.
     *
     * @maps channel_optimized_routing
     */
    public function setChannelOptimizedRouting(?bool $channelOptimizedRouting): void
    {
        $this->channelOptimizedRouting['value'] = $channelOptimizedRouting;
    }

    /**
     * Unsets Channel Optimized Routing.
     * Whether the Task Channel will prioritize Workers that have been idle. When `true`, Workers that have
     * been idle the longest are prioritized.
     */
    public function unsetChannelOptimizedRouting(): void
    {
        $this->channelOptimizedRouting = [];
    }

    /**
     * Returns Url.
     * The absolute URL of the Task Channel resource.
     */
    public function getUrl(): ?string
    {
        if (count($this->url) == 0) {
            return null;
        }
        return $this->url['value'];
    }

    /**
     * Sets Url.
     * The absolute URL of the Task Channel resource.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url['value'] = $url;
    }

    /**
     * Unsets Url.
     * The absolute URL of the Task Channel resource.
     */
    public function unsetUrl(): void
    {
        $this->url = [];
    }

    /**
     * Returns Links.
     * The URLs of related resources.
     */
    public function getLinks(): ?array
    {
        if (count($this->links) == 0) {
            return null;
        }
        return $this->links['value'];
    }

    /**
     * Sets Links.
     * The URLs of related resources.
     *
     * @maps links
     */
    public function setLinks(?array $links): void
    {
        $this->links['value'] = $links;
    }

    /**
     * Unsets Links.
     * The URLs of related resources.
     */
    public function unsetLinks(): void
    {
        $this->links = [];
    }

    /**
     * Converts the TaskChannel object to a human-readable string representation.
     *
     * @return string The string representation of the TaskChannel object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'TaskChannel',
            [
                'accountSid' => $this->getAccountSid(),
                'dateCreated' => $this->getDateCreated(),
                'dateUpdated' => $this->getDateUpdated(),
                'friendlyName' => $this->getFriendlyName(),
                'sid' => $this->getSid(),
                'uniqueName' => $this->getUniqueName(),
                'workspaceSid' => $this->getWorkspaceSid(),
                'channelOptimizedRouting' => $this->getChannelOptimizedRouting(),
                'url' => $this->getUrl(),
                'links' => $this->getLinks(),
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'account_sid',
        'date_created',
        'date_updated',
        'friendly_name',
        'sid',
        'unique_name',
        'workspace_sid',
        'channel_optimized_routing',
        'url',
        'links'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->accountSid)) {
            $json['account_sid']               = $this->accountSid['value'];
        }
        if (!empty($this->dateCreated)) {
            $json['date_created']              = DateTimeHelper::toRfc3339DateTime($this->dateCreated['value']);
        }
        if (!empty($this->dateUpdated)) {
            $json['date_updated']              = DateTimeHelper::toRfc3339DateTime($this->dateUpdated['value']);
        }
        if (!empty($this->friendlyName)) {
            $json['friendly_name']             = $this->friendlyName['value'];
        }
        if (!empty($this->sid)) {
            $json['sid']                       = $this->sid['value'];
        }
        if (!empty($this->uniqueName)) {
            $json['unique_name']               = $this->uniqueName['value'];
        }
        if (!empty($this->workspaceSid)) {
            $json['workspace_sid']             = $this->workspaceSid['value'];
        }
        if (!empty($this->channelOptimizedRouting)) {
            $json['channel_optimized_routing'] = $this->channelOptimizedRouting['value'];
        }
        if (!empty($this->url)) {
            $json['url']                       = $this->url['value'];
        }
        if (!empty($this->links)) {
            $json['links']                     = $this->links['value'];
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
