<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class VerificationAttemptEnumCallStatus
{
    public const QUEUED = 'queued';

    public const INPROGRESS = 'in-progress';

    public const COMPLETED = 'completed';

    public const BUSY = 'busy';

    public const FAILED = 'failed';

    public const NOANSWER = 'no-answer';

    public const RINGING = 'ringing';

    public const CANCELED = 'canceled';

    private const _ALL_VALUES = [
        self::QUEUED,
        self::INPROGRESS,
        self::COMPLETED,
        self::BUSY,
        self::FAILED,
        self::NOANSWER,
        self::RINGING,
        self::CANCELED
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for VerificationAttemptEnumCallStatus.");
    }
}
