<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * A string specifying the conversion status of the verification. A conversion happens when the user is
 * able to provide the correct code. Possible values are `CONVERTED` and `UNCONVERTED`.
 */
class VerificationAttemptEnumConversionStatus
{
    public const CONVERTED = 'converted';

    public const UNCONVERTED = 'unconverted';

    private const _ALL_VALUES = [self::CONVERTED, self::UNCONVERTED];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for VerificationAttemptEnumConversionStatus.");
    }
}
