<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models;

use stdClass;
use TwilioApIsLib\ApiHelper;
use TwilioApIsLib\Utils\DateTimeHelper;

class VerificationAttempt implements \JsonSerializable
{
    /**
     * @var array
     */
    private $sid = [];

    /**
     * @var array
     */
    private $accountSid = [];

    /**
     * @var array
     */
    private $serviceSid = [];

    /**
     * @var array
     */
    private $verificationSid = [];

    /**
     * @var array
     */
    private $dateCreated = [];

    /**
     * @var array
     */
    private $dateUpdated = [];

    /**
     * @var string|null
     */
    private $conversionStatus;

    /**
     * @var string|null
     */
    private $channel;

    /**
     * @var array
     */
    private $price = [];

    /**
     * @var array
     */
    private $channelData = [];

    /**
     * @var array
     */
    private $url = [];

    /**
     * Returns Sid.
     * The SID that uniquely identifies the verification attempt resource.
     */
    public function getSid(): ?string
    {
        if (count($this->sid) == 0) {
            return null;
        }
        return $this->sid['value'];
    }

    /**
     * Sets Sid.
     * The SID that uniquely identifies the verification attempt resource.
     *
     * @maps sid
     */
    public function setSid(?string $sid): void
    {
        $this->sid['value'] = $sid;
    }

    /**
     * Unsets Sid.
     * The SID that uniquely identifies the verification attempt resource.
     */
    public function unsetSid(): void
    {
        $this->sid = [];
    }

    /**
     * Returns Account Sid.
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Verification
     * resource.
     */
    public function getAccountSid(): ?string
    {
        if (count($this->accountSid) == 0) {
            return null;
        }
        return $this->accountSid['value'];
    }

    /**
     * Sets Account Sid.
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Verification
     * resource.
     *
     * @maps account_sid
     */
    public function setAccountSid(?string $accountSid): void
    {
        $this->accountSid['value'] = $accountSid;
    }

    /**
     * Unsets Account Sid.
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Verification
     * resource.
     */
    public function unsetAccountSid(): void
    {
        $this->accountSid = [];
    }

    /**
     * Returns Service Sid.
     * The SID of the [Service](https://www.twilio.com/docs/verify/api/service) used to generate the
     * attempt.
     */
    public function getServiceSid(): ?string
    {
        if (count($this->serviceSid) == 0) {
            return null;
        }
        return $this->serviceSid['value'];
    }

    /**
     * Sets Service Sid.
     * The SID of the [Service](https://www.twilio.com/docs/verify/api/service) used to generate the
     * attempt.
     *
     * @maps service_sid
     */
    public function setServiceSid(?string $serviceSid): void
    {
        $this->serviceSid['value'] = $serviceSid;
    }

    /**
     * Unsets Service Sid.
     * The SID of the [Service](https://www.twilio.com/docs/verify/api/service) used to generate the
     * attempt.
     */
    public function unsetServiceSid(): void
    {
        $this->serviceSid = [];
    }

    /**
     * Returns Verification Sid.
     * The SID of the [Verification](https://www.twilio.com/docs/verify/api/verification) that generated
     * the attempt.
     */
    public function getVerificationSid(): ?string
    {
        if (count($this->verificationSid) == 0) {
            return null;
        }
        return $this->verificationSid['value'];
    }

    /**
     * Sets Verification Sid.
     * The SID of the [Verification](https://www.twilio.com/docs/verify/api/verification) that generated
     * the attempt.
     *
     * @maps verification_sid
     */
    public function setVerificationSid(?string $verificationSid): void
    {
        $this->verificationSid['value'] = $verificationSid;
    }

    /**
     * Unsets Verification Sid.
     * The SID of the [Verification](https://www.twilio.com/docs/verify/api/verification) that generated
     * the attempt.
     */
    public function unsetVerificationSid(): void
    {
        $this->verificationSid = [];
    }

    /**
     * Returns Date Created.
     * The date that this Attempt was created, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
     * format.
     */
    public function getDateCreated(): ?\DateTime
    {
        if (count($this->dateCreated) == 0) {
            return null;
        }
        return $this->dateCreated['value'];
    }

    /**
     * Sets Date Created.
     * The date that this Attempt was created, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
     * format.
     *
     * @maps date_created
     * @factory \TwilioApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateCreated(?\DateTime $dateCreated): void
    {
        $this->dateCreated['value'] = $dateCreated;
    }

    /**
     * Unsets Date Created.
     * The date that this Attempt was created, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
     * format.
     */
    public function unsetDateCreated(): void
    {
        $this->dateCreated = [];
    }

    /**
     * Returns Date Updated.
     * The date that this Attempt was updated, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
     * format.
     */
    public function getDateUpdated(): ?\DateTime
    {
        if (count($this->dateUpdated) == 0) {
            return null;
        }
        return $this->dateUpdated['value'];
    }

    /**
     * Sets Date Updated.
     * The date that this Attempt was updated, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
     * format.
     *
     * @maps date_updated
     * @factory \TwilioApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setDateUpdated(?\DateTime $dateUpdated): void
    {
        $this->dateUpdated['value'] = $dateUpdated;
    }

    /**
     * Unsets Date Updated.
     * The date that this Attempt was updated, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
     * format.
     */
    public function unsetDateUpdated(): void
    {
        $this->dateUpdated = [];
    }

    /**
     * Returns Conversion Status.
     * A string specifying the conversion status of the verification. A conversion happens when the user is
     * able to provide the correct code. Possible values are `CONVERTED` and `UNCONVERTED`.
     */
    public function getConversionStatus(): ?string
    {
        return $this->conversionStatus;
    }

    /**
     * Sets Conversion Status.
     * A string specifying the conversion status of the verification. A conversion happens when the user is
     * able to provide the correct code. Possible values are `CONVERTED` and `UNCONVERTED`.
     *
     * @maps conversion_status
     * @factory \TwilioApIsLib\Models\VerificationAttemptEnumConversionStatus::checkValue
     */
    public function setConversionStatus(?string $conversionStatus): void
    {
        $this->conversionStatus = $conversionStatus;
    }

    /**
     * Returns Channel.
     * A string specifying the communication channel used for the verification attempt.
     */
    public function getChannel(): ?string
    {
        return $this->channel;
    }

    /**
     * Sets Channel.
     * A string specifying the communication channel used for the verification attempt.
     *
     * @maps channel
     * @factory \TwilioApIsLib\Models\VerificationAttemptEnumChannels::checkValue
     */
    public function setChannel(?string $channel): void
    {
        $this->channel = $channel;
    }

    /**
     * Returns Price.
     * An object containing the charge for this verification attempt related to the channel costs and the
     * currency used. The costs related to the succeeded verifications are not included. May not be
     * immediately available. More information on pricing is available [here](https://www.twilio.com/en-
     * us/verify/pricing).
     */
    public function getPrice(): ?array
    {
        if (count($this->price) == 0) {
            return null;
        }
        return $this->price['value'];
    }

    /**
     * Sets Price.
     * An object containing the charge for this verification attempt related to the channel costs and the
     * currency used. The costs related to the succeeded verifications are not included. May not be
     * immediately available. More information on pricing is available [here](https://www.twilio.com/en-
     * us/verify/pricing).
     *
     * @maps price
     */
    public function setPrice(?array $price): void
    {
        $this->price['value'] = $price;
    }

    /**
     * Unsets Price.
     * An object containing the charge for this verification attempt related to the channel costs and the
     * currency used. The costs related to the succeeded verifications are not included. May not be
     * immediately available. More information on pricing is available [here](https://www.twilio.com/en-
     * us/verify/pricing).
     */
    public function unsetPrice(): void
    {
        $this->price = [];
    }

    /**
     * Returns Channel Data.
     * An object containing the channel specific information for an attempt.
     */
    public function getChannelData(): ?array
    {
        if (count($this->channelData) == 0) {
            return null;
        }
        return $this->channelData['value'];
    }

    /**
     * Sets Channel Data.
     * An object containing the channel specific information for an attempt.
     *
     * @maps channel_data
     */
    public function setChannelData(?array $channelData): void
    {
        $this->channelData['value'] = $channelData;
    }

    /**
     * Unsets Channel Data.
     * An object containing the channel specific information for an attempt.
     */
    public function unsetChannelData(): void
    {
        $this->channelData = [];
    }

    /**
     * Returns Url.
     */
    public function getUrl(): ?string
    {
        if (count($this->url) == 0) {
            return null;
        }
        return $this->url['value'];
    }

    /**
     * Sets Url.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url['value'] = $url;
    }

    /**
     * Unsets Url.
     */
    public function unsetUrl(): void
    {
        $this->url = [];
    }

    /**
     * Converts the VerificationAttempt object to a human-readable string representation.
     *
     * @return string The string representation of the VerificationAttempt object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'VerificationAttempt',
            [
                'sid' => $this->getSid(),
                'accountSid' => $this->getAccountSid(),
                'serviceSid' => $this->getServiceSid(),
                'verificationSid' => $this->getVerificationSid(),
                'dateCreated' => $this->getDateCreated(),
                'dateUpdated' => $this->getDateUpdated(),
                'conversionStatus' => $this->conversionStatus,
                'channel' => $this->channel,
                'price' => $this->getPrice(),
                'channelData' => $this->getChannelData(),
                'url' => $this->getUrl(),
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'sid',
        'account_sid',
        'service_sid',
        'verification_sid',
        'date_created',
        'date_updated',
        'conversion_status',
        'channel',
        'price',
        'channel_data',
        'url'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->sid)) {
            $json['sid']               = $this->sid['value'];
        }
        if (!empty($this->accountSid)) {
            $json['account_sid']       = $this->accountSid['value'];
        }
        if (!empty($this->serviceSid)) {
            $json['service_sid']       = $this->serviceSid['value'];
        }
        if (!empty($this->verificationSid)) {
            $json['verification_sid']  = $this->verificationSid['value'];
        }
        if (!empty($this->dateCreated)) {
            $json['date_created']      = DateTimeHelper::toRfc3339DateTime($this->dateCreated['value']);
        }
        if (!empty($this->dateUpdated)) {
            $json['date_updated']      = DateTimeHelper::toRfc3339DateTime($this->dateUpdated['value']);
        }
        if (isset($this->conversionStatus)) {
            $json['conversion_status'] = VerificationAttemptEnumConversionStatus::checkValue($this->conversionStatus);
        }
        if (isset($this->channel)) {
            $json['channel']           = VerificationAttemptEnumChannels::checkValue($this->channel);
        }
        if (!empty($this->price)) {
            $json['price']             = $this->price['value'];
        }
        if (!empty($this->channelData)) {
            $json['channel_data']      = $this->channelData['value'];
        }
        if (!empty($this->url)) {
            $json['url']               = $this->url['value'];
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
