<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models;

use stdClass;
use TwilioApIsLib\ApiHelper;

class WorkersRealTimeStatistics implements \JsonSerializable
{
    /**
     * @var array
     */
    private $accountSid = [];

    /**
     * @var array
     */
    private $activityStatistics = [];

    /**
     * @var int|null
     */
    private $totalWorkers = 0;

    /**
     * @var array
     */
    private $workspaceSid = [];

    /**
     * @var array
     */
    private $url = [];

    /**
     * Returns Account Sid.
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Worker
     * resource.
     */
    public function getAccountSid(): ?string
    {
        if (count($this->accountSid) == 0) {
            return null;
        }
        return $this->accountSid['value'];
    }

    /**
     * Sets Account Sid.
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Worker
     * resource.
     *
     * @maps account_sid
     */
    public function setAccountSid(?string $accountSid): void
    {
        $this->accountSid['value'] = $accountSid;
    }

    /**
     * Unsets Account Sid.
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Worker
     * resource.
     */
    public function unsetAccountSid(): void
    {
        $this->accountSid = [];
    }

    /**
     * Returns Activity Statistics.
     * The number of current Workers by Activity.
     *
     * @return array[]|null
     */
    public function getActivityStatistics(): ?array
    {
        if (count($this->activityStatistics) == 0) {
            return null;
        }
        return $this->activityStatistics['value'];
    }

    /**
     * Sets Activity Statistics.
     * The number of current Workers by Activity.
     *
     * @maps activity_statistics
     *
     * @param array[]|null $activityStatistics
     */
    public function setActivityStatistics(?array $activityStatistics): void
    {
        $this->activityStatistics['value'] = $activityStatistics;
    }

    /**
     * Unsets Activity Statistics.
     * The number of current Workers by Activity.
     */
    public function unsetActivityStatistics(): void
    {
        $this->activityStatistics = [];
    }

    /**
     * Returns Total Workers.
     * The total number of Workers.
     */
    public function getTotalWorkers(): ?int
    {
        return $this->totalWorkers;
    }

    /**
     * Sets Total Workers.
     * The total number of Workers.
     *
     * @maps total_workers
     */
    public function setTotalWorkers(?int $totalWorkers): void
    {
        $this->totalWorkers = $totalWorkers;
    }

    /**
     * Returns Workspace Sid.
     * The SID of the Workspace that contains the Workers.
     */
    public function getWorkspaceSid(): ?string
    {
        if (count($this->workspaceSid) == 0) {
            return null;
        }
        return $this->workspaceSid['value'];
    }

    /**
     * Sets Workspace Sid.
     * The SID of the Workspace that contains the Workers.
     *
     * @maps workspace_sid
     */
    public function setWorkspaceSid(?string $workspaceSid): void
    {
        $this->workspaceSid['value'] = $workspaceSid;
    }

    /**
     * Unsets Workspace Sid.
     * The SID of the Workspace that contains the Workers.
     */
    public function unsetWorkspaceSid(): void
    {
        $this->workspaceSid = [];
    }

    /**
     * Returns Url.
     * The absolute URL of the Workers statistics resource.
     */
    public function getUrl(): ?string
    {
        if (count($this->url) == 0) {
            return null;
        }
        return $this->url['value'];
    }

    /**
     * Sets Url.
     * The absolute URL of the Workers statistics resource.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url['value'] = $url;
    }

    /**
     * Unsets Url.
     * The absolute URL of the Workers statistics resource.
     */
    public function unsetUrl(): void
    {
        $this->url = [];
    }

    /**
     * Converts the WorkersRealTimeStatistics object to a human-readable string representation.
     *
     * @return string The string representation of the WorkersRealTimeStatistics object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'WorkersRealTimeStatistics',
            [
                'accountSid' => $this->getAccountSid(),
                'activityStatistics' => $this->getActivityStatistics(),
                'totalWorkers' => $this->totalWorkers,
                'workspaceSid' => $this->getWorkspaceSid(),
                'url' => $this->getUrl(),
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = ['account_sid', 'activity_statistics', 'total_workers', 'workspace_sid', 'url'];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->accountSid)) {
            $json['account_sid']         = $this->accountSid['value'];
        }
        if (!empty($this->activityStatistics)) {
            $json['activity_statistics'] = $this->activityStatistics['value'];
        }
        if (isset($this->totalWorkers)) {
            $json['total_workers']       = $this->totalWorkers;
        }
        if (!empty($this->workspaceSid)) {
            $json['workspace_sid']       = $this->workspaceSid['value'];
        }
        if (!empty($this->url)) {
            $json['url']                 = $this->url['value'];
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
