<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib\Models;

use stdClass;
use TwilioApIsLib\ApiHelper;

class WorkspaceRealTimeStatistics implements \JsonSerializable
{
    /**
     * @var array
     */
    private $accountSid = [];

    /**
     * @var array
     */
    private $activityStatistics = [];

    /**
     * @var int|null
     */
    private $longestTaskWaitingAge = 0;

    /**
     * @var array
     */
    private $longestTaskWaitingSid = [];

    /**
     * @var array
     */
    private $tasksByPriority = [];

    /**
     * @var array
     */
    private $tasksByStatus = [];

    /**
     * @var int|null
     */
    private $totalTasks = 0;

    /**
     * @var int|null
     */
    private $totalWorkers = 0;

    /**
     * @var array
     */
    private $workspaceSid = [];

    /**
     * @var array
     */
    private $url = [];

    /**
     * Returns Account Sid.
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Workspace
     * resource.
     */
    public function getAccountSid(): ?string
    {
        if (count($this->accountSid) == 0) {
            return null;
        }
        return $this->accountSid['value'];
    }

    /**
     * Sets Account Sid.
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Workspace
     * resource.
     *
     * @maps account_sid
     */
    public function setAccountSid(?string $accountSid): void
    {
        $this->accountSid['value'] = $accountSid;
    }

    /**
     * Unsets Account Sid.
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Workspace
     * resource.
     */
    public function unsetAccountSid(): void
    {
        $this->accountSid = [];
    }

    /**
     * Returns Activity Statistics.
     * The number of current Workers by Activity.
     *
     * @return array[]|null
     */
    public function getActivityStatistics(): ?array
    {
        if (count($this->activityStatistics) == 0) {
            return null;
        }
        return $this->activityStatistics['value'];
    }

    /**
     * Sets Activity Statistics.
     * The number of current Workers by Activity.
     *
     * @maps activity_statistics
     *
     * @param array[]|null $activityStatistics
     */
    public function setActivityStatistics(?array $activityStatistics): void
    {
        $this->activityStatistics['value'] = $activityStatistics;
    }

    /**
     * Unsets Activity Statistics.
     * The number of current Workers by Activity.
     */
    public function unsetActivityStatistics(): void
    {
        $this->activityStatistics = [];
    }

    /**
     * Returns Longest Task Waiting Age.
     * The age of the longest waiting Task.
     */
    public function getLongestTaskWaitingAge(): ?int
    {
        return $this->longestTaskWaitingAge;
    }

    /**
     * Sets Longest Task Waiting Age.
     * The age of the longest waiting Task.
     *
     * @maps longest_task_waiting_age
     */
    public function setLongestTaskWaitingAge(?int $longestTaskWaitingAge): void
    {
        $this->longestTaskWaitingAge = $longestTaskWaitingAge;
    }

    /**
     * Returns Longest Task Waiting Sid.
     * The SID of the longest waiting Task.
     */
    public function getLongestTaskWaitingSid(): ?string
    {
        if (count($this->longestTaskWaitingSid) == 0) {
            return null;
        }
        return $this->longestTaskWaitingSid['value'];
    }

    /**
     * Sets Longest Task Waiting Sid.
     * The SID of the longest waiting Task.
     *
     * @maps longest_task_waiting_sid
     */
    public function setLongestTaskWaitingSid(?string $longestTaskWaitingSid): void
    {
        $this->longestTaskWaitingSid['value'] = $longestTaskWaitingSid;
    }

    /**
     * Unsets Longest Task Waiting Sid.
     * The SID of the longest waiting Task.
     */
    public function unsetLongestTaskWaitingSid(): void
    {
        $this->longestTaskWaitingSid = [];
    }

    /**
     * Returns Tasks by Priority.
     * The number of Tasks by priority. For example: `{"0": "10", "99": "5"}` shows 10 Tasks at priority 0
     * and 5 at priority 99.
     */
    public function getTasksByPriority(): ?array
    {
        if (count($this->tasksByPriority) == 0) {
            return null;
        }
        return $this->tasksByPriority['value'];
    }

    /**
     * Sets Tasks by Priority.
     * The number of Tasks by priority. For example: `{"0": "10", "99": "5"}` shows 10 Tasks at priority 0
     * and 5 at priority 99.
     *
     * @maps tasks_by_priority
     */
    public function setTasksByPriority(?array $tasksByPriority): void
    {
        $this->tasksByPriority['value'] = $tasksByPriority;
    }

    /**
     * Unsets Tasks by Priority.
     * The number of Tasks by priority. For example: `{"0": "10", "99": "5"}` shows 10 Tasks at priority 0
     * and 5 at priority 99.
     */
    public function unsetTasksByPriority(): void
    {
        $this->tasksByPriority = [];
    }

    /**
     * Returns Tasks by Status.
     * The number of Tasks by their current status. For example: `{"pending": "1", "reserved": "3",
     * "assigned": "2", "completed": "5"}`.
     */
    public function getTasksByStatus(): ?array
    {
        if (count($this->tasksByStatus) == 0) {
            return null;
        }
        return $this->tasksByStatus['value'];
    }

    /**
     * Sets Tasks by Status.
     * The number of Tasks by their current status. For example: `{"pending": "1", "reserved": "3",
     * "assigned": "2", "completed": "5"}`.
     *
     * @maps tasks_by_status
     */
    public function setTasksByStatus(?array $tasksByStatus): void
    {
        $this->tasksByStatus['value'] = $tasksByStatus;
    }

    /**
     * Unsets Tasks by Status.
     * The number of Tasks by their current status. For example: `{"pending": "1", "reserved": "3",
     * "assigned": "2", "completed": "5"}`.
     */
    public function unsetTasksByStatus(): void
    {
        $this->tasksByStatus = [];
    }

    /**
     * Returns Total Tasks.
     * The total number of Tasks.
     */
    public function getTotalTasks(): ?int
    {
        return $this->totalTasks;
    }

    /**
     * Sets Total Tasks.
     * The total number of Tasks.
     *
     * @maps total_tasks
     */
    public function setTotalTasks(?int $totalTasks): void
    {
        $this->totalTasks = $totalTasks;
    }

    /**
     * Returns Total Workers.
     * The total number of Workers in the Workspace.
     */
    public function getTotalWorkers(): ?int
    {
        return $this->totalWorkers;
    }

    /**
     * Sets Total Workers.
     * The total number of Workers in the Workspace.
     *
     * @maps total_workers
     */
    public function setTotalWorkers(?int $totalWorkers): void
    {
        $this->totalWorkers = $totalWorkers;
    }

    /**
     * Returns Workspace Sid.
     * The SID of the Workspace.
     */
    public function getWorkspaceSid(): ?string
    {
        if (count($this->workspaceSid) == 0) {
            return null;
        }
        return $this->workspaceSid['value'];
    }

    /**
     * Sets Workspace Sid.
     * The SID of the Workspace.
     *
     * @maps workspace_sid
     */
    public function setWorkspaceSid(?string $workspaceSid): void
    {
        $this->workspaceSid['value'] = $workspaceSid;
    }

    /**
     * Unsets Workspace Sid.
     * The SID of the Workspace.
     */
    public function unsetWorkspaceSid(): void
    {
        $this->workspaceSid = [];
    }

    /**
     * Returns Url.
     * The absolute URL of the Workspace statistics resource.
     */
    public function getUrl(): ?string
    {
        if (count($this->url) == 0) {
            return null;
        }
        return $this->url['value'];
    }

    /**
     * Sets Url.
     * The absolute URL of the Workspace statistics resource.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url['value'] = $url;
    }

    /**
     * Unsets Url.
     * The absolute URL of the Workspace statistics resource.
     */
    public function unsetUrl(): void
    {
        $this->url = [];
    }

    /**
     * Converts the WorkspaceRealTimeStatistics object to a human-readable string representation.
     *
     * @return string The string representation of the WorkspaceRealTimeStatistics object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'WorkspaceRealTimeStatistics',
            [
                'accountSid' => $this->getAccountSid(),
                'activityStatistics' => $this->getActivityStatistics(),
                'longestTaskWaitingAge' => $this->longestTaskWaitingAge,
                'longestTaskWaitingSid' => $this->getLongestTaskWaitingSid(),
                'tasksByPriority' => $this->getTasksByPriority(),
                'tasksByStatus' => $this->getTasksByStatus(),
                'totalTasks' => $this->totalTasks,
                'totalWorkers' => $this->totalWorkers,
                'workspaceSid' => $this->getWorkspaceSid(),
                'url' => $this->getUrl(),
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'account_sid',
        'activity_statistics',
        'longest_task_waiting_age',
        'longest_task_waiting_sid',
        'tasks_by_priority',
        'tasks_by_status',
        'total_tasks',
        'total_workers',
        'workspace_sid',
        'url'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->accountSid)) {
            $json['account_sid']              = $this->accountSid['value'];
        }
        if (!empty($this->activityStatistics)) {
            $json['activity_statistics']      = $this->activityStatistics['value'];
        }
        if (isset($this->longestTaskWaitingAge)) {
            $json['longest_task_waiting_age'] = $this->longestTaskWaitingAge;
        }
        if (!empty($this->longestTaskWaitingSid)) {
            $json['longest_task_waiting_sid'] = $this->longestTaskWaitingSid['value'];
        }
        if (!empty($this->tasksByPriority)) {
            $json['tasks_by_priority']        = $this->tasksByPriority['value'];
        }
        if (!empty($this->tasksByStatus)) {
            $json['tasks_by_status']          = $this->tasksByStatus['value'];
        }
        if (isset($this->totalTasks)) {
            $json['total_tasks']              = $this->totalTasks;
        }
        if (isset($this->totalWorkers)) {
            $json['total_workers']            = $this->totalWorkers;
        }
        if (!empty($this->workspaceSid)) {
            $json['workspace_sid']            = $this->workspaceSid['value'];
        }
        if (!empty($this->url)) {
            $json['url']                      = $this->url['value'];
        }
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
