<?php

declare(strict_types=1);

/*
 * TwilioApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TwilioApIsLib;

/**
 * Baseurl aliases
 */
class Server
{
    public const DEFAULT_ = 'default';

    public const DEFAULT1 = 'default1';

    public const DEFAULT2 = 'default2';

    public const DEFAULT3 = 'default3';

    public const DEFAULT4 = 'default4';

    public const DEFAULT5 = 'default5';
}
